before:
  hooks:
    # to avoid goreleaser error due to `make deps` on CI: git is currently in a dirty state
    # we should never see go.mod be dirty because we `go build -mod=readonly`, but we can't well control go.sum updates
    - git checkout go.sum

builds:
  - binary: '{{ .ProjectName }}_{{ .Version }}'
    id: "default"
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{ .Version }}
    gcflags:
      - all=-trimpath={{ .Env.GOPATH }}
    asmflags:
      - all=-trimpath={{ .Env.GOPATH }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: linux
        goarch: amd64
      - goos: linux
        goarch: arm64
    env:
      - CGO_ENABLED=0
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: darwin-fips
    builder: prebuilt
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: "prebuilt/darwin-fips_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/{{ .ProjectName }}_{{ .Version }}"
  - binary: '{{ .ProjectName }}_{{ .Version }}'
    id: "linux-amd64-build"
    flags:
      - -mod=readonly
      - -tags=netgo
    ldflags:
      - -s -w -X main.version={{ .Version }}
      - -linkmode 'external' -extldflags '-static'
    gcflags:
      - all=-trimpath={{ .Env.GOPATH }}
    asmflags:
      - all=-trimpath={{ .Env.GOPATH }}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - GOEXPERIMENT=boringcrypto
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: '{{ .CommitTimestamp }}'
  - binary: '{{ .ProjectName }}_{{ .Version }}'
    id: "linux-arm64-build"
    flags:
      - -mod=readonly
      - -tags=netgo
    ldflags:
      - -s -w -X main.version={{ .Version }}
      - -linkmode 'external' -extldflags '-static'
    gcflags:
      - all=-trimpath={{ .Env.GOPATH }}
    asmflags:
      - all=-trimpath={{ .Env.GOPATH }}
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - GOEXPERIMENT=boringcrypto
      - CC=aarch64-linux-gnu-gcc
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: archive
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    builds:
      - default
      - linux-amd64-build
      - linux-arm64-build
    files:
      - README.md
      - LICENSE
      - legal/**/*
  - id: archive-fips
    name_template: '{{ .ProjectName }}_fips_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    builds:
      - darwin-fips
    files:
      - README.md
      - LICENSE
      - legal/**/*

checksum:
  # This suffix is required for Terraform Registry
  # https://www.terraform.io/docs/registry/providers/publishing.html#manually-preparing-a-release
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

signs:
  - artifacts: checksum
    cmd: gpg
    args: ['--batch', '-u', '{{ .Env.GPG_FINGERPRINT }}', '--output', '${signature}', '--detach-sign', '${artifact}', '--pinentry-mode', 'loopback']
    stdin: '{{ .Env.GPG_PASSWORD }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '[ci skip]$'
      - make fmt
      - fix go.sum
      - go mod tidy

release:
  draft: true
