// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.21.0; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dnsRecordDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: dnsRecordDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The ID of the DNS record.",
			},
			paramEnvironment: environmentDataSourceSchema(),
			paramDisplayName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The name of the DNS record.",
			},
			paramDomain: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The fully qualified domain name of the DNS record.",
			},
			paramGateway: {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						paramId: {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
				Description: "The gateway to which this belongs.",
			},
			paramPrivateLinkAccessPoint: privateLinkAccessPointDnsRecordDataSourceSchema(),
		},
	}
}

func privateLinkAccessPointDnsRecordDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "ID of the target resource.",
				},
			},
		},
		Computed: true,
	}
}

func dnsRecordDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	dnsRecordId := d.Get(paramId).(string)
	if dnsRecordId == "" {
		return diag.Errorf("error reading DNS record: DNS record id is missing")
	}
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	tflog.Debug(ctx, fmt.Sprintf("Reading DNS record %q=%q", paramId, dnsRecordId), map[string]interface{}{dnsRecordLoggingKey: dnsRecordId})

	c := meta.(*Client)
	dnsRecord, resp, err := executeDnsRecordRead(c.networkingAccessPointV1ApiContext(ctx), c, environmentId, dnsRecordId)
	if err != nil {
		return diag.Errorf("error reading DNS record %q: %s", dnsRecordId, createDescriptiveError(err, resp))
	}
	dnsRecordJson, err := json.Marshal(dnsRecord)
	if err != nil {
		return diag.Errorf("error reading DNS record %q: error marshaling %#v to json: %s", dnsRecordId, dnsRecord, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched DNS record %q: %s", dnsRecordId, dnsRecordJson), map[string]interface{}{dnsRecordLoggingKey: dnsRecordId})

	if _, err := setDnsRecordAttributes(d, dnsRecord); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}
