// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	flinkv2 "github.com/confluentinc/ccloud-sdk-go-v2/flink/v2"
)

func flinkRegionDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: flinkRegionDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The ID of the Flink region.",
			},
			paramCloud: {
				Type:             schema.TypeString,
				Required:         true,
				ValidateFunc:     validation.StringInSlice(acceptedCloudProviders, false),
				DiffSuppressFunc: suppressSameValueIgnoringCase,
				Description:      "The cloud service provider that hosts the region.",
			},
			paramRegion: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The region name.",
			},
			paramRestEndpoint: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The regional API endpoint for Flink compute pools.",
			},
			paramRestEndpointPrivate: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The private regional API endpoint for Flink compute pools.",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
		},
	}
}

// flinkRegionDataSourceRead selects a single Flink region from the List
// endpoint using the required filters. The endpoint has no GET-by-id, so the filters are
// the lookup: zero matches and more than one match are both errors.
func flinkRegionDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	cloud := d.Get(paramCloud).(string)
	regionName := d.Get(paramRegion).(string)

	tflog.Debug(ctx, fmt.Sprintf("Reading Flink region with %q=%q, %q=%q", paramCloud, cloud, paramRegion, regionName))

	c := meta.(*Client)
	flinkRegionList, resp, err := executeListFlinkRegions(ctx, c, cloud, regionName)
	if err != nil {
		return diag.Errorf("error reading Flink region: %s", createDescriptiveError(err, resp))
	}
	flinkRegionJson, err := json.Marshal(flinkRegionList)
	if err != nil {
		return diag.Errorf("error reading Flink region: error marshaling %#v to json: %s", flinkRegionList, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched Flink regions: %s", flinkRegionJson))

	if len(flinkRegionList.GetData()) == 0 {
		return diag.Errorf("error reading Flink region: there aren't any Flink regions with %q=%q, %q=%q", paramCloud, cloud, paramRegion, regionName)
	}
	if len(flinkRegionList.GetData()) > 1 {
		return diag.Errorf("error reading Flink region: there are multiple Flink regions with %q=%q, %q=%q", paramCloud, cloud, paramRegion, regionName)
	}

	if _, err := setFlinkRegionAttributes(d, flinkRegionList.GetData()[0]); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

func executeListFlinkRegions(ctx context.Context, c *Client, cloud string, regionName string) (flinkv2.FcpmV2RegionList, *http.Response, error) {
	req := c.flinkV2Client.RegionsFcpmV2Api.ListFcpmV2Regions(c.flinkV2ApiContext(ctx)).PageSize(listFlinkRegionsPageSize).Cloud(cloud).RegionName(regionName)
	return req.Execute()
}

func setFlinkRegionAttributes(d *schema.ResourceData, flinkRegion flinkv2.FcpmV2Region) (*schema.ResourceData, error) {
	if err := d.Set(paramCloud, flinkRegion.GetCloud()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramRegion, flinkRegion.GetRegionName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramRestEndpoint, flinkRegion.GetHttpEndpoint()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramRestEndpointPrivate, flinkRegion.GetPrivateHttpEndpoint()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramApiVersion, flinkRegion.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, flinkRegion.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(flinkRegion.GetId())
	return d, nil
}
