// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func ipGroupDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: ipGroupDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The ID of the ip group.",
			},
			paramGroupName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A human readable name for an IP Group. Can contain any unicode letter or number, the ASCII space character, or any of the following special characters: `[`, `]`, `|`, `&`, `+`, `-`, `_`, `/`, `.`, `,`.",
			},
			paramCidrBlocks: {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Computed:    true,
				Description: "A list of CIDRs.",
			},
		},
	}
}

func ipGroupDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	ipGroupId := d.Get(paramId).(string)
	tflog.Debug(ctx, fmt.Sprintf("Reading ip group %q=%q", paramId, ipGroupId), map[string]interface{}{ipGroupLoggingKey: ipGroupId})

	c := meta.(*Client)
	ipGroup, resp, err := executeIpGroupRead(c.iamIpFilteringV2ApiContext(ctx), c, ipGroupId)
	if err != nil {
		return diag.Errorf("error reading ip group %q: %s", ipGroupId, createDescriptiveError(err, resp))
	}
	ipGroupJson, err := json.Marshal(ipGroup)
	if err != nil {
		return diag.Errorf("error reading ip group %q: error marshaling %#v to json: %s", ipGroupId, ipGroup, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched ip group %q: %s", ipGroupId, ipGroupJson), map[string]interface{}{ipGroupLoggingKey: ipGroupId})

	if _, err := setIpGroupAttributes(d, ipGroup); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}
