// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.21.0; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func byokKeyDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: byokKeyDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The ID of the BYOK key.",
			},
			paramAws:   awsByokKeyDataSourceSchema(),
			paramAzure: azureByokKeyDataSourceSchema(),
			paramGcp:   gcpByokKeyDataSourceSchema(),
		},
	}
}

func awsByokKeyDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAwsKeyArn: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The Amazon Resource Name (ARN) of an AWS KMS key.",
				},
				paramAwsRoles: {
					Type:        schema.TypeSet,
					Elem:        &schema.Schema{Type: schema.TypeString},
					Computed:    true,
					Description: "The Amazon Resource Names (ARNs) of IAM Roles created for this key-environment combination.",
				},
			},
		},
		Computed: true,
	}
}

func azureByokKeyDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAzureKeyId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The unique Key Object Identifier URL without version of an Azure Key Vault key.",
				},
				paramAzureKeyVaultId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Key Vault ID containing the key",
				},
				paramAzureTenantId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Tenant ID (uuid) hosting the Key Vault containing the key",
				},
				paramAzureApplicationId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The Application ID created for this key-environment combination.",
				},
			},
		},
		Computed: true,
	}
}

func gcpByokKeyDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramGcpKeyId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The Google Cloud Platform key ID.",
				},
				paramGcpSecurityGroup: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The Google security group created for this key.",
				},
			},
		},
		Computed: true,
	}
}

func byokKeyDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	byokKeyId := d.Get(paramId).(string)
	if byokKeyId == "" {
		return diag.Errorf("error reading BYOK key: BYOK key id is missing")
	}

	tflog.Debug(ctx, fmt.Sprintf("Reading BYOK key %q=%q", paramId, byokKeyId), map[string]interface{}{byokKeyLoggingKey: byokKeyId})

	c := meta.(*Client)
	byokKey, resp, err := executeByokKeyRead(c.byokV1ApiContext(ctx), c, byokKeyId)
	if err != nil {
		return diag.Errorf("error reading BYOK key %q: %s", byokKeyId, createDescriptiveError(err, resp))
	}
	byokKeyJson, err := json.Marshal(byokKey)
	if err != nil {
		return diag.Errorf("error reading BYOK key %q: error marshaling %#v to json: %s", byokKeyId, byokKey, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched BYOK key %q: %s", byokKeyId, byokKeyJson), map[string]interface{}{byokKeyLoggingKey: byokKeyId})

	if _, err := setByokKeyAttributes(d, byokKey); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}
