// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.23.0; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	networkingv1 "github.com/confluentinc/ccloud-sdk-go-v2/networking/v1"
)

func transitGatewayAttachmentDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: transitGatewayAttachmentDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The ID of the transit gateway attachment.",
			},
			paramEnvironment: environmentDataSourceSchema(),
			paramDisplayName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The name of the TGW attachment",
			},
			paramNetwork: {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						paramId: {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
				Description: "The network to which this belongs.",
			},
			paramAws: awsTransitGatewayAttachmentDataSourceSchema(),
		},
	}
}

func awsTransitGatewayAttachmentDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramRamResourceShareArn: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The full AWS Resource Name (ARN) for the AWS Resource Access Manager (RAM) Share of the Transit Gateways that you want Confluent Cloud to be attached to.",
				},
				paramTransitGatewayId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The ID of the AWS Transit Gateway that you want Confluent CLoud to be attached to.",
				},
				paramRoutes: {
					Type:        schema.TypeList,
					Elem:        &schema.Schema{Type: schema.TypeString},
					Computed:    true,
					Description: "List of destination routes.",
				},
				paramTransitGatewayAttachmentId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The ID of the AWS Transit Gateway VPC Attachment that attaches Confluent VPC to Transit Gateway.",
				},
			},
		},
		Computed: true,
	}
}

func transitGatewayAttachmentDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	transitGatewayAttachmentId := d.Get(paramId).(string)
	displayName := d.Get(paramDisplayName).(string)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if environmentId == "" {
		return diag.Errorf("error reading transit gateway attachment: environment ID is missing")
	}

	if transitGatewayAttachmentId != "" {
		return transitGatewayAttachmentDataSourceReadUsingId(ctx, d, meta, environmentId, transitGatewayAttachmentId)
	} else if displayName != "" {
		return transitGatewayAttachmentDataSourceReadUsingDisplayName(ctx, d, meta, environmentId, displayName)
	}
	return diag.Errorf("error reading transit gateway attachment: exactly one of %q or %q must be specified but they're both empty", paramId, paramDisplayName)
}

func transitGatewayAttachmentDataSourceReadUsingDisplayName(ctx context.Context, d *schema.ResourceData, meta interface{}, environmentId string, displayName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading transit gateway attachment %q=%q", paramDisplayName, displayName))

	c := meta.(*Client)
	transitGatewayAttachments, err := loadTransitGatewayAttachments(ctx, c, environmentId)
	if err != nil {
		return diag.Errorf("error reading transit gateway attachment %q: %s", displayName, createDescriptiveError(err))
	}
	if hasMultipleTransitGatewayAttachmentsWithDisplayName(transitGatewayAttachments, displayName) {
		return diag.Errorf("error reading transit gateway attachment: there are multiple transit gateway attachments with %q=%q", paramDisplayName, displayName)
	}
	for _, transitGatewayAttachment := range transitGatewayAttachments {
		spec := transitGatewayAttachment.GetSpec()
		if spec.GetDisplayName() == displayName {
			if _, err := setTransitGatewayAttachmentAttributes(d, transitGatewayAttachment); err != nil {
				return diag.FromErr(createDescriptiveError(err))
			}
			return nil
		}
	}

	return diag.Errorf("error reading transit gateway attachment: transit gateway attachment with %q=%q was not found", paramDisplayName, displayName)
}

func hasMultipleTransitGatewayAttachmentsWithDisplayName(transitGatewayAttachments []networkingv1.NetworkingV1TransitGatewayAttachment, displayName string) bool {
	count := 0
	for _, transitGatewayAttachment := range transitGatewayAttachments {
		spec := transitGatewayAttachment.GetSpec()
		if spec.GetDisplayName() == displayName {
			count += 1
		}
	}
	return count > 1
}

func transitGatewayAttachmentDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, environmentId string, transitGatewayAttachmentId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading transit gateway attachment %q=%q", paramId, transitGatewayAttachmentId), map[string]interface{}{transitGatewayAttachmentLoggingKey: transitGatewayAttachmentId})

	c := meta.(*Client)
	transitGatewayAttachment, resp, err := executeTransitGatewayAttachmentRead(c.networkingV1ApiContext(ctx), c, environmentId, transitGatewayAttachmentId)
	if err != nil {
		return diag.Errorf("error reading transit gateway attachment %q: %s", transitGatewayAttachmentId, createDescriptiveError(err, resp))
	}
	transitGatewayAttachmentJson, err := json.Marshal(transitGatewayAttachment)
	if err != nil {
		return diag.Errorf("error reading transit gateway attachment %q: error marshaling %#v to json: %s", transitGatewayAttachmentId, transitGatewayAttachment, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched transit gateway attachment %q: %s", transitGatewayAttachmentId, transitGatewayAttachmentJson), map[string]interface{}{transitGatewayAttachmentLoggingKey: transitGatewayAttachmentId})

	if _, err := setTransitGatewayAttachmentAttributes(d, transitGatewayAttachment); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

// loadTransitGatewayAttachments paginates through every page of the List endpoint and returns all
// transit gateway attachments.
//
// Emitted because terraform.emit_list_all_helper is set, which happens for either of two
// reasons: a caller outside this file needs it (importers.go is the usual one), or one of the
// data source's alternate lookup keys has to scan client-side, because the SDK's List request
// either has no filter method for that key or could not be checked for one (no --sdk-path given).
// Which reason applies is not derivable here, so grep for callers before removing it.
func loadTransitGatewayAttachments(ctx context.Context, c *Client, environmentId string) ([]networkingv1.NetworkingV1TransitGatewayAttachment, error) {
	transitGatewayAttachments := make([]networkingv1.NetworkingV1TransitGatewayAttachment, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListTransitGatewayAttachments(ctx, c, environmentId, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading transit gateway attachments: %s", createDescriptiveError(err, resp))
		}
		transitGatewayAttachments = append(transitGatewayAttachments, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading transit gateway attachments: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return transitGatewayAttachments, nil
}

func executeListTransitGatewayAttachments(ctx context.Context, c *Client, environmentId string, pageToken string) (networkingv1.NetworkingV1TransitGatewayAttachmentList, *http.Response, error) {
	if pageToken != "" {
		return c.networkingV1Client.TransitGatewayAttachmentsNetworkingV1Api.ListNetworkingV1TransitGatewayAttachments(c.networkingV1ApiContext(ctx)).Environment(environmentId).PageSize(listTransitGatewayAttachmentsPageSize).PageToken(pageToken).Execute()
	} else {
		return c.networkingV1Client.TransitGatewayAttachmentsNetworkingV1Api.ListNetworkingV1TransitGatewayAttachments(c.networkingV1ApiContext(ctx)).Environment(environmentId).PageSize(listTransitGatewayAttachmentsPageSize).Execute()
	}
}
