// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	iamv2 "github.com/confluentinc/ccloud-sdk-go-v2/iam/v2"
)

func serviceAccountDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: serviceAccountDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The ID of the service account.",
			},
			paramDisplayName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "A human-readable name for the Service Account",
			},
			paramDescription: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A free-form description of the Service Account",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
		},
	}
}

func serviceAccountDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	serviceAccountId := d.Get(paramId).(string)
	displayName := d.Get(paramDisplayName).(string)

	if serviceAccountId != "" {
		return serviceAccountDataSourceReadUsingId(ctx, d, meta, serviceAccountId)
	} else if displayName != "" {
		return serviceAccountDataSourceReadUsingDisplayName(ctx, d, meta, displayName)
	}
	return diag.Errorf("error reading service account: exactly one of %q or %q must be specified but they're both empty", paramId, paramDisplayName)
}

func serviceAccountDataSourceReadUsingDisplayName(ctx context.Context, d *schema.ResourceData, meta interface{}, displayName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading service account %q=%q", paramDisplayName, displayName))

	c := meta.(*Client)
	serviceAccountList, resp, err := c.iamV2Client.ServiceAccountsIamV2Api.ListIamV2ServiceAccounts(c.iamV2ApiContext(ctx)).DisplayName(strings.Fields(displayName)).Execute()
	if err != nil {
		return diag.Errorf("error reading service account %q: %s", displayName, createDescriptiveError(err, resp))
	}
	serviceAccounts := serviceAccountList.GetData()
	if len(serviceAccounts) == 0 {
		return diag.Errorf("error reading service account: service account with %q=%q was not found", paramDisplayName, displayName)
	}
	if len(serviceAccounts) > 1 {
		return diag.Errorf("error reading service account: there are multiple service accounts with %q=%q", paramDisplayName, displayName)
	}
	serviceAccount := serviceAccounts[0]
	serviceAccountJson, err := json.Marshal(serviceAccount)
	if err != nil {
		return diag.Errorf("error reading service account %q: error marshaling %#v to json: %s", displayName, serviceAccount, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched service account %q: %s", serviceAccount.GetId(), serviceAccountJson), map[string]interface{}{serviceAccountLoggingKey: serviceAccount.GetId()})

	if _, err := setServiceAccountAttributes(d, serviceAccount); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

func serviceAccountDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, serviceAccountId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading service account %q=%q", paramId, serviceAccountId), map[string]interface{}{serviceAccountLoggingKey: serviceAccountId})

	c := meta.(*Client)
	serviceAccount, resp, err := executeServiceAccountRead(c.iamV2ApiContext(ctx), c, serviceAccountId)
	if err != nil {
		return diag.Errorf("error reading service account %q: %s", serviceAccountId, createDescriptiveError(err, resp))
	}
	serviceAccountJson, err := json.Marshal(serviceAccount)
	if err != nil {
		return diag.Errorf("error reading service account %q: error marshaling %#v to json: %s", serviceAccountId, serviceAccount, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched service account %q: %s", serviceAccountId, serviceAccountJson), map[string]interface{}{serviceAccountLoggingKey: serviceAccountId})

	if _, err := setServiceAccountAttributes(d, serviceAccount); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

// loadServiceAccounts paginates through every page of the List endpoint and returns all
// service accounts. Used by the provider's bulk state-import flow (importers.go).
func loadServiceAccounts(ctx context.Context, c *Client) ([]iamv2.IamV2ServiceAccount, error) {
	serviceAccounts := make([]iamv2.IamV2ServiceAccount, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListServiceAccounts(ctx, c, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading service accounts: %s", createDescriptiveError(err, resp))
		}
		serviceAccounts = append(serviceAccounts, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading service accounts: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return serviceAccounts, nil
}

func executeListServiceAccounts(ctx context.Context, c *Client, pageToken string) (iamv2.IamV2ServiceAccountList, *http.Response, error) {
	if pageToken != "" {
		return c.iamV2Client.ServiceAccountsIamV2Api.ListIamV2ServiceAccounts(c.iamV2ApiContext(ctx)).PageSize(listServiceAccountsPageSize).PageToken(pageToken).Execute()
	} else {
		return c.iamV2Client.ServiceAccountsIamV2Api.ListIamV2ServiceAccounts(c.iamV2ApiContext(ctx)).PageSize(listServiceAccountsPageSize).Execute()
	}
}
