// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func orgComputePoolConfigDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: orgComputePoolConfigDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The unique identifier for the org compute pool config.",
			},
			paramDefaultPoolEnabled: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether default compute pools are enabled for the organization. When enabled, environments can have default compute pools created automatically.",
			},
			paramMaxCFU: {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "Maximum number of Confluent Flink Units (CFUs) that default compute pools in this organization should auto-scale to.",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
		},
	}
}

func orgComputePoolConfigDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Reading org compute pool config")

	c := meta.(*Client)
	orgComputePoolConfig, resp, err := executeOrgComputePoolConfigRead(c.flinkV2ApiContext(ctx), c)
	if err != nil {
		return diag.Errorf("error reading org compute pool config: %s", createDescriptiveError(err, resp))
	}
	orgComputePoolConfigJson, err := json.Marshal(orgComputePoolConfig)
	if err != nil {
		return diag.Errorf("error reading org compute pool config: error marshaling %#v to json: %s", orgComputePoolConfig, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched org compute pool config: %s", orgComputePoolConfigJson))

	if _, err := setOrgComputePoolConfigAttributes(d, orgComputePoolConfig); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	return nil
}
