// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/walkerus/go-wiremock"
)

const (
	switchover_endpointDataSourceScenarioName = "confluent_switchover_endpoint Data Source Lifecycle"
)

func TestAccDataSourceSwitchoverSwitchoverEndpoint(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readSwitchoverEndpointResponse, _ := ioutil.ReadFile("../testdata/switchover_endpoint/read_created_switchover_endpoint.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/switchover/v1/switchover-endpoints/%s", switchover_endpointId))).
		InScenario(switchover_endpointDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readSwitchoverEndpointResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "prod-kafka-dr-endpoint"
	endpoints := ""
	environment := "env-00000"
	switchoverPair := "sw-00000"
	target := "west-platt"
	switchover_endpointDataSourceLabel := "test_switchover_endpoint_data_source_label"
	fullSwitchoverEndpointDataSourceLabel := fmt.Sprintf("data.confluent_switchover_endpoint.%s", switchover_endpointDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceSwitchoverSwitchoverEndpointConfig(mockServerUrl, switchover_endpointDataSourceLabel, environment),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "id", switchover_endpointId),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "dr_endpoint", "glkc-sw-abc-se-12345.global.confluent.cloud"),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "endpoints", endpoints),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "environment.0.id", environment),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "switchover_pair.0.id", switchoverPair),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "target", target),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "api_version", "switchover/v1"),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "kind", "SwitchoverEndpoint"),
					resource.TestCheckResourceAttr(fullSwitchoverEndpointDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/switchover-endpoint=se-12345"),
				),
			},
		},
	})
}

func testAccCheckDataSourceSwitchoverSwitchoverEndpointConfig(mockServerUrl, switchover_endpointDataSourceLabel string, environmentId string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	data "confluent_switchover_endpoint" "%s" {
		id = "%s"
		environment {
			id = "%s"
		}
	}
	`, mockServerUrl, switchover_endpointDataSourceLabel, switchover_endpointId, environmentId)
}
