// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func integrationDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: integrationDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The ID of the integration.",
			},
			paramDisplayName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A human readable name for the particular integration",
			},
			paramDescription: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A human readable description for the particular integration",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Integration.",
			},
			paramSlackTarget:     slackTargetIntegrationDataSourceSchema(),
			paramRoleEmailTarget: roleEmailTargetIntegrationDataSourceSchema(),
			paramUserEmailTarget: userEmailTargetIntegrationDataSourceSchema(),
			paramWebhookTarget:   webhookTargetIntegrationDataSourceSchema(),
			paramMsTeamsTarget:   msTeamsTargetIntegrationDataSourceSchema(),
			paramInAppTarget:     inAppTargetIntegrationDataSourceSchema(),
		},
	}
}

func slackTargetIntegrationDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramSlackTargetWebhookUrl: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func roleEmailTargetIntegrationDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramRoleEmailTargetRoleName: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func userEmailTargetIntegrationDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramUserEmailTargetUser: {
					Type: schema.TypeList,
					Elem: &schema.Resource{
						Schema: map[string]*schema.Schema{
							paramId: {
								Type:     schema.TypeString,
								Computed: true,
							},
						},
					},
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func webhookTargetIntegrationDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramWebhookTargetUrl: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func msTeamsTargetIntegrationDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramMsTeamsTargetWebhookUrl: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func inAppTargetIntegrationDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramInAppTargetUser: {
					Type: schema.TypeList,
					Elem: &schema.Resource{
						Schema: map[string]*schema.Schema{
							paramId: {
								Type:     schema.TypeString,
								Computed: true,
							},
						},
					},
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func integrationDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	integrationId := d.Get(paramId).(string)
	if integrationId == "" {
		return diag.Errorf("error reading integration: integration id is missing")
	}

	tflog.Debug(ctx, fmt.Sprintf("Reading integration %q=%q", paramId, integrationId), map[string]interface{}{integrationLoggingKey: integrationId})

	c := meta.(*Client)
	integration, resp, err := executeIntegrationRead(c.notificationsV1ApiContext(ctx), c, integrationId)
	if err != nil {
		return diag.Errorf("error reading integration %q: %s", integrationId, createDescriptiveError(err, resp))
	}
	integrationJson, err := json.Marshal(integration)
	if err != nil {
		return diag.Errorf("error reading integration %q: error marshaling %#v to json: %s", integrationId, integration, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched integration %q: %s", integrationId, integrationJson), map[string]interface{}{integrationLoggingKey: integrationId})

	if _, err := setIntegrationAttributes(d, integration); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}
