// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.13.0; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func certificateAuthorityDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: certificateAuthorityDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The ID of the certificate authority.",
			},
			paramDisplayName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The human-readable name of the certificate authority.",
			},
			paramDescription: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A description of the certificate authority.",
			},
			paramFingerprints: {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Computed:    true,
				Description: "The fingerprints for each certificate in the certificate chain. These are SHA-1 encoded strings that act as unique identifiers for the certificates in the chain.",
			},
			paramExpirationDates: {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Computed:    true,
				Description: "The expiration dates of certificates in the chain.",
			},
			paramSerialNumbers: {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Computed:    true,
				Description: "The serial numbers for each certificate in the certificate chain.",
			},
			paramCertificateChainFilename: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The file name of the uploaded pem file for this certificate authority.",
			},
			paramCrlSource: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The source specifies whether the Certificate Revocation List (CRL) is updated from either local file uploaded (LOCAL) or from url of CRL (URL).",
			},
			paramCrlUrl: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The url from which to fetch the CRL for the certificate authority if crl_source is URL.",
			},
			paramCrlUpdatedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The timestamp for when CRL was last updated.",
			},
			paramState: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The current state of the certificate authority.",
			},
			paramRequireCrlOnClientCertificate: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether to require CRL validation on client certificates. If `require_crl_on_client_certificate` is true, then a CRL must be configured. At time of mTLS auth, if the client certificate is revoked in the CRL or the client issuer does not match the CRL issuer, certificate verification will fail even if TLS handshake is successful (OpenSSL -crl_check default behavior). If `require_crl_on_client_certificate` is false, this mTLS identity provider cannot configure a new CRL.",
			},
		},
	}
}

func certificateAuthorityDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	certificateAuthorityId := d.Get(paramId).(string)
	tflog.Debug(ctx, fmt.Sprintf("Reading certificate authority %q=%q", paramId, certificateAuthorityId), map[string]interface{}{certificateAuthorityLoggingKey: certificateAuthorityId})

	c := meta.(*Client)
	certificateAuthority, resp, err := executeCertificateAuthorityRead(c.certificateAuthorityV2ApiContext(ctx), c, certificateAuthorityId)
	if err != nil {
		return diag.Errorf("error reading certificate authority %q: %s", certificateAuthorityId, createDescriptiveError(err, resp))
	}
	certificateAuthorityJson, err := json.Marshal(certificateAuthority)
	if err != nil {
		return diag.Errorf("error reading certificate authority %q: error marshaling %#v to json: %s", certificateAuthorityId, certificateAuthority, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched certificate authority %q: %s", certificateAuthorityId, certificateAuthorityJson), map[string]interface{}{certificateAuthorityLoggingKey: certificateAuthorityId})

	if _, err := setCertificateAuthorityAttributes(d, certificateAuthority); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}
