// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	orgv2 "github.com/confluentinc/ccloud-sdk-go-v2/org/v2"
)

func environmentDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: environmentDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The ID of the environment.",
			},
			paramDisplayName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "A human-readable name for the Environment",
			},
			paramStreamGovernanceConfig: {
				Type:     schema.TypeList,
				MaxItems: 1,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						paramPackage: {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
				Description: "Stream Governance configurations for the environment",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Environment.",
			},
		},
	}
}

func environmentDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	environmentId := d.Get(paramId).(string)
	displayName := d.Get(paramDisplayName).(string)

	if environmentId != "" {
		return environmentDataSourceReadUsingId(ctx, d, meta, environmentId)
	} else if displayName != "" {
		return environmentDataSourceReadUsingDisplayName(ctx, d, meta, displayName)
	}
	return diag.Errorf("error reading environment: exactly one of %q or %q must be specified but they're both empty", paramId, paramDisplayName)
}

func environmentDataSourceReadUsingDisplayName(ctx context.Context, d *schema.ResourceData, meta interface{}, displayName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading environment %q=%q", paramDisplayName, displayName))

	c := meta.(*Client)
	environments, err := loadEnvironments(ctx, c)
	if err != nil {
		return diag.Errorf("error reading environment %q: %s", displayName, createDescriptiveError(err))
	}
	var matchedEnvironment orgv2.OrgV2Environment
	matchCount := 0
	for _, environment := range environments {
		if environment.GetDisplayName() == displayName {
			matchedEnvironment = environment
			matchCount++
		}
	}
	if matchCount == 0 {
		return diag.Errorf("error reading environment: environment with %q=%q was not found", paramDisplayName, displayName)
	}
	if matchCount > 1 {
		return diag.Errorf("error reading environment: there are multiple environments with %q=%q", paramDisplayName, displayName)
	}

	if _, err := setEnvironmentAttributes(d, matchedEnvironment); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

func environmentDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, environmentId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading environment %q=%q", paramId, environmentId), map[string]interface{}{environmentLoggingKey: environmentId})

	c := meta.(*Client)
	environment, resp, err := executeEnvironmentRead(c.orgV2ApiContext(ctx), c, environmentId)
	if err != nil {
		return diag.Errorf("error reading environment %q: %s", environmentId, createDescriptiveError(err, resp))
	}
	environmentJson, err := json.Marshal(environment)
	if err != nil {
		return diag.Errorf("error reading environment %q: error marshaling %#v to json: %s", environmentId, environment, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched environment %q: %s", environmentId, environmentJson), map[string]interface{}{environmentLoggingKey: environmentId})

	if _, err := setEnvironmentAttributes(d, environment); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

// loadEnvironments paginates through every page of the List endpoint and returns all
// environments. Used by the provider's bulk state-import flow (importers.go).
func loadEnvironments(ctx context.Context, c *Client) ([]orgv2.OrgV2Environment, error) {
	environments := make([]orgv2.OrgV2Environment, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListEnvironments(ctx, c, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading environments: %s", createDescriptiveError(err, resp))
		}
		environments = append(environments, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading environments: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return environments, nil
}

func executeListEnvironments(ctx context.Context, c *Client, pageToken string) (orgv2.OrgV2EnvironmentList, *http.Response, error) {
	if pageToken != "" {
		return c.orgV2Client.EnvironmentsOrgV2Api.ListOrgV2Environments(c.orgV2ApiContext(ctx)).PageSize(listEnvironmentsPageSize).PageToken(pageToken).Execute()
	} else {
		return c.orgV2Client.EnvironmentsOrgV2Api.ListOrgV2Environments(c.orgV2ApiContext(ctx)).PageSize(listEnvironmentsPageSize).Execute()
	}
}
