// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/walkerus/go-wiremock"
)

const (
	keyDataSourceScenarioName = "confluent_byok_key Data Source Lifecycle"
	keyId                     = "dlz-f3a90de"
)

func TestAccDataSourceByokAwsKey(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readAwsKeyResponse, _ := ioutil.ReadFile("../testdata/byok_key/read_created_aws_key.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/byok/v1/keys/%s", keyId))).
		InScenario(keyDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readAwsKeyResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	keyDataSourceLabel := "test_aws_key_data_source_label"
	fullKeyDataSourceLabel := fmt.Sprintf("data.confluent_byok_key.%s", keyDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceByokKeyConfig(mockServerUrl, keyDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullKeyDataSourceLabel, "id", keyId),
					resource.TestCheckResourceAttrSet(fullKeyDataSourceLabel, fmt.Sprintf("%s.0.%s", paramAws, paramAwsKeyArn)),
				),
			},
		},
	})
}

func TestAccDataSourceByokAzureKey(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readAzureKeyResponse, _ := ioutil.ReadFile("../testdata/byok_key/read_created_azure_key.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/byok/v1/keys/%s", keyId))).
		InScenario(keyDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readAzureKeyResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	keyDataSourceLabel := "test_azure_key_data_source_label"
	fullKeyDataSourceLabel := fmt.Sprintf("data.confluent_byok_key.%s", keyDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceByokKeyConfig(mockServerUrl, keyDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullKeyDataSourceLabel, "id", keyId),
					resource.TestCheckResourceAttrSet(fullKeyDataSourceLabel, fmt.Sprintf("%s.0.%s", paramAzure, paramAzureKeyId)),
					resource.TestCheckResourceAttrSet(fullKeyDataSourceLabel, fmt.Sprintf("%s.0.%s", paramAzure, paramAzureKeyVaultId)),
					resource.TestCheckResourceAttrSet(fullKeyDataSourceLabel, fmt.Sprintf("%s.0.%s", paramAzure, paramAzureTenantId)),
				),
			},
		},
	})
}

func TestAccDataSourceByokGcpKey(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readGcpKeyResponse, _ := ioutil.ReadFile("../testdata/byok_key/read_created_gcp_key.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/byok/v1/keys/%s", keyId))).
		InScenario(keyDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readGcpKeyResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	keyDataSourceLabel := "test_gcp_key_data_source_label"
	fullKeyDataSourceLabel := fmt.Sprintf("data.confluent_byok_key.%s", keyDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceByokKeyConfig(mockServerUrl, keyDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullKeyDataSourceLabel, "id", keyId),
					resource.TestCheckResourceAttrSet(fullKeyDataSourceLabel, fmt.Sprintf("%s.0.%s", paramGcp, paramGcpKeyId)),
					resource.TestCheckResourceAttr(fullKeyDataSourceLabel, fmt.Sprintf("%s.0.%s", paramGcp, paramGcpSecurityGroup), "testgroupid@domain.com"),
				),
			},
		},
	})
}

func testAccCheckDataSourceByokKeyConfig(mockServerUrl, keyDataSourceLabel string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	data "confluent_byok_key" "%s" {
		id = "%s"
	}
	`, mockServerUrl, keyDataSourceLabel, keyId)
}
