// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.17.1; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	flinkv2 "github.com/confluentinc/ccloud-sdk-go-v2/flink/v2"
)

func computePoolDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: computePoolDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The ID of the compute pool.",
			},
			paramEnvironment: environmentDataSourceSchema(),
			paramCloud: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The cloud service provider that runs the compute pool.",
			},
			paramDefaultPool: {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Indicate whether the Flink compute pool is a default compute pool or not.",
			},
			paramDisplayName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The name of the Flink compute pool.",
			},
			paramMaxCfu: {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "Maximum number of Confluent Flink Units (CFUs) that the Flink compute pool should auto-scale to.",
			},
			paramRegion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Flink compute pools in the region provided will be able to use this identity pool",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Compute Pool.",
			},
		},
	}
}

func computePoolDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	computePoolId := d.Get(paramId).(string)
	displayName := d.Get(paramDisplayName).(string)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if environmentId == "" {
		return diag.Errorf("error reading compute pool: environment Id is missing")
	}

	if computePoolId != "" {
		return computePoolDataSourceReadUsingId(ctx, d, meta, environmentId, computePoolId)
	} else if displayName != "" {
		return computePoolDataSourceReadUsingDisplayName(ctx, d, meta, environmentId, displayName)
	}
	return diag.Errorf("error reading compute pool: exactly one of %q or %q must be specified but they're both empty", paramId, paramDisplayName)
}

func computePoolDataSourceReadUsingDisplayName(ctx context.Context, d *schema.ResourceData, meta interface{}, environmentId string, displayName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading compute pool %q=%q", paramDisplayName, displayName))

	c := meta.(*Client)
	computePools, err := loadComputePools(ctx, c, environmentId)
	if err != nil {
		return diag.Errorf("error reading compute pool %q: %s", displayName, createDescriptiveError(err))
	}
	if hasMultipleComputePoolsWithDisplayName(computePools, displayName) {
		return diag.Errorf("error reading compute pool: there are multiple compute pools with %q=%q", paramDisplayName, displayName)
	}
	for _, computePool := range computePools {
		spec := computePool.GetSpec()
		if spec.GetDisplayName() == displayName {
			if _, err := setComputePoolAttributes(d, computePool); err != nil {
				return diag.FromErr(createDescriptiveError(err))
			}
			return nil
		}
	}

	return diag.Errorf("error reading compute pool: compute pool with %q=%q was not found", paramDisplayName, displayName)
}

func hasMultipleComputePoolsWithDisplayName(computePools []flinkv2.FcpmV2ComputePool, displayName string) bool {
	count := 0
	for _, computePool := range computePools {
		spec := computePool.GetSpec()
		if spec.GetDisplayName() == displayName {
			count += 1
		}
	}
	return count > 1
}

func computePoolDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, environmentId string, computePoolId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading compute pool %q=%q", paramId, computePoolId), map[string]interface{}{computePoolLoggingKey: computePoolId})

	c := meta.(*Client)
	computePool, resp, err := executeComputePoolRead(c.flinkV2ApiContext(ctx), c, environmentId, computePoolId)
	if err != nil {
		return diag.Errorf("error reading compute pool %q: %s", computePoolId, createDescriptiveError(err, resp))
	}
	computePoolJson, err := json.Marshal(computePool)
	if err != nil {
		return diag.Errorf("error reading compute pool %q: error marshaling %#v to json: %s", computePoolId, computePool, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched compute pool %q: %s", computePoolId, computePoolJson), map[string]interface{}{computePoolLoggingKey: computePoolId})

	if _, err := setComputePoolAttributes(d, computePool); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

// loadComputePools paginates through every page of the List endpoint and returns all
// compute pools.
//
// Emitted because terraform.emit_list_all_helper is set, which happens for either of two
// reasons: a caller outside this file needs it (importers.go is the usual one), or a
// display_name lookup has to scan client-side, because the SDK's List request either has no
// DisplayName(...) filter method or could not be checked for one (no --sdk-path given).
// Which reason applies is not derivable here, so grep for callers before removing it.
func loadComputePools(ctx context.Context, c *Client, environmentId string) ([]flinkv2.FcpmV2ComputePool, error) {
	computePools := make([]flinkv2.FcpmV2ComputePool, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListComputePools(ctx, c, environmentId, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading compute pools: %s", createDescriptiveError(err, resp))
		}
		computePools = append(computePools, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading compute pools: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return computePools, nil
}

func executeListComputePools(ctx context.Context, c *Client, environmentId string, pageToken string) (flinkv2.FcpmV2ComputePoolList, *http.Response, error) {
	if pageToken != "" {
		return c.flinkV2Client.ComputePoolsFcpmV2Api.ListFcpmV2ComputePools(c.flinkV2ApiContext(ctx)).Environment(environmentId).PageSize(listComputePoolsPageSize).PageToken(pageToken).Execute()
	} else {
		return c.flinkV2Client.ComputePoolsFcpmV2Api.ListFcpmV2ComputePools(c.flinkV2ApiContext(ctx)).Environment(environmentId).PageSize(listComputePoolsPageSize).Execute()
	}
}
