// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/walkerus/go-wiremock"
)

const (
	integrationDataSourceScenarioName = "confluent_notifications_integration Data Source Lifecycle"
)

func TestAccDataSourceNotificationsSlackTarget(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readSlackTargetResponse, _ := ioutil.ReadFile("../testdata/notifications_integration/read_created_slack_target.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/integrations/%s", integrationId))).
		InScenario(integrationDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readSlackTargetResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "Slack integration"
	description := "A Slack channel integration"
	integrationDataSourceLabel := "test_slack_target_data_source_label"
	fullIntegrationDataSourceLabel := fmt.Sprintf("data.confluent_notifications_integration.%s", integrationDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsIntegrationConfig(mockServerUrl, integrationDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "id", integrationId),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "description", description),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "kind", "Integration"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/integration=i-12345"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, fmt.Sprintf("%s.0.%s", paramSlackTarget, paramSlackTargetWebhookUrl), "https://hooks.slack.com/services/{id}/{id}/{id}"),
				),
			},
		},
	})
}

func TestAccDataSourceNotificationsRoleEmailTarget(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readRoleEmailTargetResponse, _ := ioutil.ReadFile("../testdata/notifications_integration/read_created_role_email_target.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/integrations/%s", integrationId))).
		InScenario(integrationDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readRoleEmailTargetResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "Slack integration"
	description := "A Slack channel integration"
	integrationDataSourceLabel := "test_role_email_target_data_source_label"
	fullIntegrationDataSourceLabel := fmt.Sprintf("data.confluent_notifications_integration.%s", integrationDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsIntegrationConfig(mockServerUrl, integrationDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "id", integrationId),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "description", description),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "kind", "Integration"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/integration=i-12345"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, fmt.Sprintf("%s.0.%s", paramRoleEmailTarget, paramRoleEmailTargetRoleName), "OrganizationAdmin"),
				),
			},
		},
	})
}

func TestAccDataSourceNotificationsUserEmailTarget(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readUserEmailTargetResponse, _ := ioutil.ReadFile("../testdata/notifications_integration/read_created_user_email_target.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/integrations/%s", integrationId))).
		InScenario(integrationDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readUserEmailTargetResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "Slack integration"
	description := "A Slack channel integration"
	integrationDataSourceLabel := "test_user_email_target_data_source_label"
	fullIntegrationDataSourceLabel := fmt.Sprintf("data.confluent_notifications_integration.%s", integrationDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsIntegrationConfig(mockServerUrl, integrationDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "id", integrationId),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "description", description),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "kind", "Integration"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/integration=i-12345"),
					resource.TestCheckResourceAttrSet(fullIntegrationDataSourceLabel, fmt.Sprintf("%s.0.%s.0.id", paramUserEmailTarget, paramUserEmailTargetUser)),
				),
			},
		},
	})
}

func TestAccDataSourceNotificationsWebhookTarget(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readWebhookTargetResponse, _ := ioutil.ReadFile("../testdata/notifications_integration/read_created_webhook_target.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/integrations/%s", integrationId))).
		InScenario(integrationDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readWebhookTargetResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "Slack integration"
	description := "A Slack channel integration"
	integrationDataSourceLabel := "test_webhook_target_data_source_label"
	fullIntegrationDataSourceLabel := fmt.Sprintf("data.confluent_notifications_integration.%s", integrationDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsIntegrationConfig(mockServerUrl, integrationDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "id", integrationId),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "description", description),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "kind", "Integration"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/integration=i-12345"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, fmt.Sprintf("%s.0.%s", paramWebhookTarget, paramWebhookTargetUrl), "https://my.webhook.url/{id}"),
				),
			},
		},
	})
}

func TestAccDataSourceNotificationsMsTeamsTarget(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readMsTeamsTargetResponse, _ := ioutil.ReadFile("../testdata/notifications_integration/read_created_ms_teams_target.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/integrations/%s", integrationId))).
		InScenario(integrationDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readMsTeamsTargetResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "Slack integration"
	description := "A Slack channel integration"
	integrationDataSourceLabel := "test_ms_teams_target_data_source_label"
	fullIntegrationDataSourceLabel := fmt.Sprintf("data.confluent_notifications_integration.%s", integrationDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsIntegrationConfig(mockServerUrl, integrationDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "id", integrationId),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "description", description),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "kind", "Integration"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/integration=i-12345"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, fmt.Sprintf("%s.0.%s", paramMsTeamsTarget, paramMsTeamsTargetWebhookUrl), "https://admin.webhook.office.com/webhookb2/{id}/IncomingWebhook/{id}"),
				),
			},
		},
	})
}

func TestAccDataSourceNotificationsInAppTarget(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readInAppTargetResponse, _ := ioutil.ReadFile("../testdata/notifications_integration/read_created_in_app_target.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/integrations/%s", integrationId))).
		InScenario(integrationDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readInAppTargetResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "Slack integration"
	description := "A Slack channel integration"
	integrationDataSourceLabel := "test_in_app_target_data_source_label"
	fullIntegrationDataSourceLabel := fmt.Sprintf("data.confluent_notifications_integration.%s", integrationDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsIntegrationConfig(mockServerUrl, integrationDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "id", integrationId),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "description", description),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "kind", "Integration"),
					resource.TestCheckResourceAttr(fullIntegrationDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/integration=i-12345"),
					resource.TestCheckResourceAttrSet(fullIntegrationDataSourceLabel, fmt.Sprintf("%s.0.%s.0.id", paramInAppTarget, paramInAppTargetUser)),
				),
			},
		},
	})
}

func testAccCheckDataSourceNotificationsIntegrationConfig(mockServerUrl, integrationDataSourceLabel string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	data "confluent_notifications_integration" "%s" {
		id = %q
	}
	`, mockServerUrl, integrationDataSourceLabel, integrationId)
}
