// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.22.2; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	iamv2 "github.com/confluentinc/ccloud-sdk-go-v2/iam/v2"
)

func userDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: userDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramFullName, paramEmail},
				Description:  "The ID of the user.",
			},
			paramEmail: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramFullName, paramEmail},
				Description:  "The user's email address",
			},
			paramFullName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramFullName, paramEmail},
				Description:  "The user's full name",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
		},
	}
}

func userDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	userId := d.Get(paramId).(string)
	fullName := d.Get(paramFullName).(string)
	email := d.Get(paramEmail).(string)

	if userId != "" {
		return userDataSourceReadUsingId(ctx, d, meta, userId)
	} else if fullName != "" {
		return userDataSourceReadUsingFullName(ctx, d, meta, fullName)
	} else if email != "" {
		return userDataSourceReadUsingEmail(ctx, d, meta, email)
	}
	return diag.Errorf("error reading user: exactly one of %q, %q or %q must be specified but they're all empty", paramId, paramFullName, paramEmail)
}

func userDataSourceReadUsingFullName(ctx context.Context, d *schema.ResourceData, meta interface{}, fullName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading user %q=%q", paramFullName, fullName))

	c := meta.(*Client)
	users, err := loadUsers(ctx, c)
	if err != nil {
		return diag.Errorf("error reading user %q: %s", fullName, createDescriptiveError(err))
	}
	if hasMultipleUsersWithFullName(users, fullName) {
		return diag.Errorf("error reading user: there are multiple users with %q=%q", paramFullName, fullName)
	}
	for _, user := range users {
		if user.GetFullName() == fullName {
			if _, err := setUserAttributes(d, user); err != nil {
				return diag.FromErr(createDescriptiveError(err))
			}
			return nil
		}
	}

	return diag.Errorf("error reading user: user with %q=%q was not found", paramFullName, fullName)
}

func hasMultipleUsersWithFullName(users []iamv2.IamV2User, fullName string) bool {
	count := 0
	for _, user := range users {
		if user.GetFullName() == fullName {
			count += 1
		}
	}
	return count > 1
}

func userDataSourceReadUsingEmail(ctx context.Context, d *schema.ResourceData, meta interface{}, email string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading user %q=%q", paramEmail, email))

	c := meta.(*Client)
	users, err := loadUsers(ctx, c)
	if err != nil {
		return diag.Errorf("error reading user %q: %s", email, createDescriptiveError(err))
	}
	if hasMultipleUsersWithEmail(users, email) {
		return diag.Errorf("error reading user: there are multiple users with %q=%q", paramEmail, email)
	}
	for _, user := range users {
		if user.GetEmail() == email {
			if _, err := setUserAttributes(d, user); err != nil {
				return diag.FromErr(createDescriptiveError(err))
			}
			return nil
		}
	}

	return diag.Errorf("error reading user: user with %q=%q was not found", paramEmail, email)
}

func hasMultipleUsersWithEmail(users []iamv2.IamV2User, email string) bool {
	count := 0
	for _, user := range users {
		if user.GetEmail() == email {
			count += 1
		}
	}
	return count > 1
}

func userDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, userId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading user %q=%q", paramId, userId), map[string]interface{}{userLoggingKey: userId})

	c := meta.(*Client)
	user, resp, err := executeUserRead(c.iamV2ApiContext(ctx), c, userId)
	if err != nil {
		return diag.Errorf("error reading user %q: %s", userId, createDescriptiveError(err, resp))
	}
	userJson, err := json.Marshal(user)
	if err != nil {
		return diag.Errorf("error reading user %q: error marshaling %#v to json: %s", userId, user, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched user %q: %s", userId, userJson), map[string]interface{}{userLoggingKey: userId})

	if _, err := setUserAttributes(d, user); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

func executeUserRead(ctx context.Context, c *Client, userId string) (iamv2.IamV2User, *http.Response, error) {
	req := c.iamV2Client.UsersIamV2Api.GetIamV2User(c.iamV2ApiContext(ctx), userId)
	return req.Execute()
}

func setUserAttributes(d *schema.ResourceData, user iamv2.IamV2User) (*schema.ResourceData, error) {
	if err := d.Set(paramEmail, user.GetEmail()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramFullName, user.GetFullName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramApiVersion, user.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, user.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(user.GetId())
	return d, nil
}

// loadUsers paginates through every page of the List endpoint and returns all
// users.
//
// Emitted because terraform.emit_list_all_helper is set, which happens for either of two
// reasons: a caller outside this file needs it (importers.go is the usual one), or one of the
// data source's alternate lookup keys has to scan client-side, because the SDK's List request
// either has no filter method for that key or could not be checked for one (no --sdk-path given).
// Which reason applies is not derivable here, so grep for callers before removing it.
func loadUsers(ctx context.Context, c *Client) ([]iamv2.IamV2User, error) {
	users := make([]iamv2.IamV2User, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListUsers(ctx, c, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading users: %s", createDescriptiveError(err, resp))
		}
		users = append(users, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading users: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return users, nil
}

func executeListUsers(ctx context.Context, c *Client, pageToken string) (iamv2.IamV2UserList, *http.Response, error) {
	if pageToken != "" {
		return c.iamV2Client.UsersIamV2Api.ListIamV2Users(c.iamV2ApiContext(ctx)).PageSize(listUsersPageSize).PageToken(pageToken).Execute()
	} else {
		return c.iamV2Client.UsersIamV2Api.ListIamV2Users(c.iamV2ApiContext(ctx)).PageSize(listUsersPageSize).Execute()
	}
}
