// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.24.1; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func connectArtifactDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: connectArtifactDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The ID of the Connect artifact.",
			},
			paramEnvironment: environmentDataSourceSchema(),

			paramCloud: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Cloud provider where the Connect Artifact archive is uploaded.",
			},
			paramContentFormat: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Archive format of the Connect Artifact.",
			},
			paramDescription: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Description of the Connect Artifact.",
			},
			paramDisplayName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Unique name of the Connect Artifact archive per cloud, environment scope.",
			},
			paramStatus: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Specifies the current processing state of a CloudConnectArtifact.",
			},
		},
	}
}

func connectArtifactDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	connectArtifactId := d.Get(paramId).(string)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	cloudId := d.Get(paramCloud).(string)
	tflog.Debug(ctx, fmt.Sprintf("Reading Connect artifact %q=%q", paramId, connectArtifactId), map[string]interface{}{connectArtifactLoggingKey: connectArtifactId})

	c := meta.(*Client)
	connectArtifact, resp, err := executeConnectArtifactRead(c.camV1ApiContext(ctx), c, environmentId, cloudId, connectArtifactId)
	if err != nil {
		return diag.Errorf("error reading Connect artifact %q: %s", connectArtifactId, createDescriptiveError(err, resp))
	}
	connectArtifactJson, err := json.Marshal(connectArtifact)
	if err != nil {
		return diag.Errorf("error reading Connect artifact %q: error marshaling %#v to json: %s", connectArtifactId, connectArtifact, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched Connect artifact %q: %s", connectArtifactId, connectArtifactJson), map[string]interface{}{connectArtifactLoggingKey: connectArtifactId})

	if _, err := setConnectArtifactAttributes(d, connectArtifact); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}
