// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	ssov2 "github.com/confluentinc/ccloud-sdk-go-v2/sso/v2"
)

func groupMappingDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: groupMappingDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The ID of the group mapping.",
			},
			paramDisplayName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The name of the group mapping.",
			},
			paramDescription: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A description explaining the purpose and use of the group mapping.",
			},
			paramFilter: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A single group identifier or a condition based on [supported CEL operators](https://docs.confluent.io/cloud/current/access-management/authenticate/sso/group-mapping/overview.html#supported-cel-operators-for-group-mapping) that defines which groups are included.",
			},
		},
	}
}

func groupMappingDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	groupMappingId := d.Get(paramId).(string)
	displayName := d.Get(paramDisplayName).(string)

	if groupMappingId != "" {
		return groupMappingDataSourceReadUsingId(ctx, d, meta, groupMappingId)
	} else if displayName != "" {
		return groupMappingDataSourceReadUsingDisplayName(ctx, d, meta, displayName)
	}
	return diag.Errorf("error reading group mapping: exactly one of %q or %q must be specified but they're both empty", paramId, paramDisplayName)
}

func groupMappingDataSourceReadUsingDisplayName(ctx context.Context, d *schema.ResourceData, meta interface{}, displayName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading group mapping %q=%q", paramDisplayName, displayName))

	c := meta.(*Client)
	groupMappings, err := loadGroupMappings(ctx, c)
	if err != nil {
		return diag.Errorf("error reading group mapping %q: %s", displayName, createDescriptiveError(err))
	}
	if hasMultipleGroupMappingsWithDisplayName(groupMappings, displayName) {
		return diag.Errorf("error reading group mapping: there are multiple group mappings with %q=%q", paramDisplayName, displayName)
	}
	for _, groupMapping := range groupMappings {
		if groupMapping.GetDisplayName() == displayName {
			if _, err := setGroupMappingAttributes(d, groupMapping); err != nil {
				return diag.FromErr(createDescriptiveError(err))
			}
			return nil
		}
	}

	return diag.Errorf("error reading group mapping: group mapping with %q=%q was not found", paramDisplayName, displayName)
}

func hasMultipleGroupMappingsWithDisplayName(groupMappings []ssov2.IamV2SsoGroupMapping, displayName string) bool {
	count := 0
	for _, groupMapping := range groupMappings {
		if groupMapping.GetDisplayName() == displayName {
			count += 1
		}
	}
	return count > 1
}

func groupMappingDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, groupMappingId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading group mapping %q=%q", paramId, groupMappingId), map[string]interface{}{groupMappingLoggingKey: groupMappingId})

	c := meta.(*Client)
	groupMapping, resp, err := executeGroupMappingRead(c.ssoV2ApiContext(ctx), c, groupMappingId)
	if err != nil {
		return diag.Errorf("error reading group mapping %q: %s", groupMappingId, createDescriptiveError(err, resp))
	}
	groupMappingJson, err := json.Marshal(groupMapping)
	if err != nil {
		return diag.Errorf("error reading group mapping %q: error marshaling %#v to json: %s", groupMappingId, groupMapping, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched group mapping %q: %s", groupMappingId, groupMappingJson), map[string]interface{}{groupMappingLoggingKey: groupMappingId})

	if _, err := setGroupMappingAttributes(d, groupMapping); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

// loadGroupMappings paginates through every page of the List endpoint and returns all
// group mappings. Used by the provider's bulk state-import flow (importers.go).
func loadGroupMappings(ctx context.Context, c *Client) ([]ssov2.IamV2SsoGroupMapping, error) {
	groupMappings := make([]ssov2.IamV2SsoGroupMapping, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListGroupMappings(ctx, c, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading group mappings: %s", createDescriptiveError(err, resp))
		}
		groupMappings = append(groupMappings, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading group mappings: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return groupMappings, nil
}

func executeListGroupMappings(ctx context.Context, c *Client, pageToken string) (ssov2.IamV2SsoGroupMappingList, *http.Response, error) {
	if pageToken != "" {
		return c.ssoV2Client.GroupMappingsIamV2SsoApi.ListIamV2SsoGroupMappings(c.ssoV2ApiContext(ctx)).PageSize(listGroupMappingsPageSize).PageToken(pageToken).Execute()
	} else {
		return c.ssoV2Client.GroupMappingsIamV2SsoApi.ListIamV2SsoGroupMappings(c.ssoV2ApiContext(ctx)).PageSize(listGroupMappingsPageSize).Execute()
	}
}
