// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/walkerus/go-wiremock"
)

const (
	switchover_pairDataSourceScenarioName = "confluent_switchover_pair Data Source Lifecycle"
)

func TestAccDataSourceSwitchoverSwitchoverPair(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readSwitchoverPairResponse, _ := ioutil.ReadFile("../testdata/switchover_pair/read_created_switchover_pair.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/switchover/v1/switchover-pairs/%s", switchover_pairId))).
		InScenario(switchover_pairDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readSwitchoverPairResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	activeMember := "west"
	displayName := "prod-kafka-dr"
	environment := "env-00000"
	members := ""
	switchover_pairDataSourceLabel := "test_switchover_pair_data_source_label"
	fullSwitchoverPairDataSourceLabel := fmt.Sprintf("data.confluent_switchover_pair.%s", switchover_pairDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceSwitchoverSwitchoverPairConfig(mockServerUrl, switchover_pairDataSourceLabel, environment),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "id", switchover_pairId),
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "active_member", activeMember),
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "environment.0.id", environment),
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "members", members),
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "api_version", "switchover/v1"),
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "kind", "SwitchoverPair"),
					resource.TestCheckResourceAttr(fullSwitchoverPairDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/switchover-pair=sw-12345"),
				),
			},
		},
	})
}

func testAccCheckDataSourceSwitchoverSwitchoverPairConfig(mockServerUrl, switchover_pairDataSourceLabel string, environmentId string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	data "confluent_switchover_pair" "%s" {
		id = "%s"
		environment {
			id = "%s"
		}
	}
	`, mockServerUrl, switchover_pairDataSourceLabel, switchover_pairId, environmentId)
}
