// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.8.4; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/walkerus/go-wiremock"
)

const (
	subscriptionDataSourceScenarioName = "confluent_notifications_subscription Data Source Lifecycle"
)

func TestAccDataSourceNotificationsSubscription(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readSubscriptionResponse, _ := ioutil.ReadFile("../testdata/notifications_subscription/read_created_subscription.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/subscriptions/%s", subscriptionId))).
		InScenario(subscriptionDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readSubscriptionResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	currentState := "ENABLED"
	notificationType := "not-abc123"
	subscriptionDataSourceLabel := "test_subscription_data_source_label"
	fullSubscriptionDataSourceLabel := fmt.Sprintf("data.confluent_notifications_subscription.%s", subscriptionDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsSubscriptionConfig(mockServerUrl, subscriptionDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullSubscriptionDataSourceLabel, "id", subscriptionId),
					resource.TestCheckResourceAttr(fullSubscriptionDataSourceLabel, "current_state", currentState),
					resource.TestCheckResourceAttr(fullSubscriptionDataSourceLabel, "notification_type.0.id", notificationType),
					resource.TestCheckResourceAttr(fullSubscriptionDataSourceLabel, "integrations.#", "1"),
					resource.TestCheckTypeSetElemAttr(fullSubscriptionDataSourceLabel, "integrations.*", ""),
					resource.TestCheckResourceAttr(fullSubscriptionDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullSubscriptionDataSourceLabel, "kind", "Subscription"),
					resource.TestCheckResourceAttr(fullSubscriptionDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/subscription=s-12345"),
				),
			},
		},
	})
}

func testAccCheckDataSourceNotificationsSubscriptionConfig(mockServerUrl, subscriptionDataSourceLabel string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	data "confluent_notifications_subscription" "%s" {
		id = %q
	}
	`, mockServerUrl, subscriptionDataSourceLabel, subscriptionId)
}
