// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	identityproviderv2 "github.com/confluentinc/ccloud-sdk-go-v2/identity-provider/v2"
)

func identityProviderDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: identityProviderDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The ID of the identity provider.",
			},
			paramDisplayName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The human-readable name of the OAuth identity provider.",
			},
			paramDescription: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A description of the identity provider.",
			},
			paramIdentityClaim: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The JSON Web Token (JWT) claim to extract the authenticating identity to Confluent resources from [Registered Claim Names](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1). This appears in audit log records. Note: if the client specifies mapping to one identity pool ID, the identity claim configured with that pool will be used instead. Note - The attribute is in an [Early Access lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)",
			},
			paramIssuer: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A publicly accessible URL uniquely identifying the OAuth identity provider authorized to issue access tokens.",
			},
			paramJwksUri: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A publicly accessible JSON Web Key Set (JWKS) URI for the OAuth identity provider. JWKS provides a set of cryptographic keys used to verify the authenticity and integrity of JSON Web Tokens (JWTs) issued by the OAuth identity provider.",
			},
		},
	}
}

func identityProviderDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	identityProviderId := d.Get(paramId).(string)
	displayName := d.Get(paramDisplayName).(string)

	if identityProviderId != "" {
		return identityProviderDataSourceReadUsingId(ctx, d, meta, identityProviderId)
	} else if displayName != "" {
		return identityProviderDataSourceReadUsingDisplayName(ctx, d, meta, displayName)
	}
	return diag.Errorf("error reading identity provider: exactly one of %q or %q must be specified but they're both empty", paramId, paramDisplayName)
}

func identityProviderDataSourceReadUsingDisplayName(ctx context.Context, d *schema.ResourceData, meta interface{}, displayName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading identity provider %q=%q", paramDisplayName, displayName))

	c := meta.(*Client)
	identityProviders, err := loadIdentityProviders(ctx, c)
	if err != nil {
		return diag.Errorf("error reading identity provider %q: %s", displayName, createDescriptiveError(err))
	}
	var matchedIdentityProvider identityproviderv2.IamV2IdentityProvider
	matchCount := 0
	for _, identityProvider := range identityProviders {
		if identityProvider.GetDisplayName() == displayName {
			matchedIdentityProvider = identityProvider
			matchCount++
		}
	}
	if matchCount == 0 {
		return diag.Errorf("error reading identity provider: identity provider with %q=%q was not found", paramDisplayName, displayName)
	}
	if matchCount > 1 {
		return diag.Errorf("error reading identity provider: there are multiple identity providers with %q=%q", paramDisplayName, displayName)
	}

	if _, err := setIdentityProviderAttributes(d, matchedIdentityProvider); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

func identityProviderDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, identityProviderId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading identity provider %q=%q", paramId, identityProviderId), map[string]interface{}{identityProviderLoggingKey: identityProviderId})

	c := meta.(*Client)
	identityProvider, resp, err := executeIdentityProviderRead(c.identityProviderV2ApiContext(ctx), c, identityProviderId)
	if err != nil {
		return diag.Errorf("error reading identity provider %q: %s", identityProviderId, createDescriptiveError(err, resp))
	}
	identityProviderJson, err := json.Marshal(identityProvider)
	if err != nil {
		return diag.Errorf("error reading identity provider %q: error marshaling %#v to json: %s", identityProviderId, identityProvider, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched identity provider %q: %s", identityProviderId, identityProviderJson), map[string]interface{}{identityProviderLoggingKey: identityProviderId})

	if _, err := setIdentityProviderAttributes(d, identityProvider); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

// loadIdentityProviders paginates through every page of the List endpoint and returns all
// identity providers. Used by the provider's bulk state-import flow (importers.go).
func loadIdentityProviders(ctx context.Context, c *Client) ([]identityproviderv2.IamV2IdentityProvider, error) {
	identityProviders := make([]identityproviderv2.IamV2IdentityProvider, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListIdentityProviders(ctx, c, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading identity providers: %s", createDescriptiveError(err, resp))
		}
		identityProviders = append(identityProviders, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading identity providers: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return identityProviders, nil
}

func executeListIdentityProviders(ctx context.Context, c *Client, pageToken string) (identityproviderv2.IamV2IdentityProviderList, *http.Response, error) {
	if pageToken != "" {
		return c.identityProviderV2Client.IdentityProvidersIamV2Api.ListIamV2IdentityProviders(c.identityProviderV2ApiContext(ctx)).PageSize(listIdentityProvidersPageSize).PageToken(pageToken).Execute()
	} else {
		return c.identityProviderV2Client.IdentityProvidersIamV2Api.ListIamV2IdentityProviders(c.identityProviderV2ApiContext(ctx)).PageSize(listIdentityProvidersPageSize).Execute()
	}
}
