// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/walkerus/go-wiremock"
)

const (
	notificationTypeDataSourceScenarioName = "confluent_notifications_notification_type Data Source Lifecycle"
	notificationTypeId                     = "dlz-f3a90de"
)

func TestAccDataSourceNotificationsNotificationType(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	readNotificationTypeResponse, _ := ioutil.ReadFile("../testdata/notifications_notification_type/read_created_notification_type.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/notification-types/%s", notificationTypeId))).
		InScenario(notificationTypeDataSourceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillReturn(
			string(readNotificationTypeResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))
	displayName := "Cluster Shrink"
	category := "BILLING_LICENSING"
	description := "Cluster shrink operation is completed"
	subscriptionPriority := "REQUIRED"
	isIncludedInPlan := ""
	severity := "INFO"
	notificationTypeDataSourceLabel := "test_notification_type_data_source_label"
	fullNotificationTypeDataSourceLabel := fmt.Sprintf("data.confluent_notifications_notification_type.%s", notificationTypeDataSourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckDataSourceNotificationsNotificationTypeConfig(mockServerUrl, notificationTypeDataSourceLabel),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "id", notificationTypeId),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "category", category),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "description", description),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "subscription_priority", subscriptionPriority),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "is_included_in_plan", isIncludedInPlan),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "severity", severity),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "kind", "NotificationType"),
					resource.TestCheckResourceAttr(fullNotificationTypeDataSourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/notification-type=nt-12345"),
				),
			},
		},
	})
}

func testAccCheckDataSourceNotificationsNotificationTypeConfig(mockServerUrl, notificationTypeDataSourceLabel string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	data "confluent_notifications_notification_type" "%s" {
		id = %q
	}
	`, mockServerUrl, notificationTypeDataSourceLabel, notificationTypeId)
}
