// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.20.2; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	networkingv1 "github.com/confluentinc/ccloud-sdk-go-v2/networking/v1"
)

func privateLinkAccessDataSource() *schema.Resource {
	return &schema.Resource{
		ReadContext: privateLinkAccessDataSourceRead,
		Schema: map[string]*schema.Schema{
			paramId: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The ID of the private link access.",
			},
			paramEnvironment: environmentDataSourceSchema(),
			paramDisplayName: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ExactlyOneOf: []string{paramId, paramDisplayName},
				Description:  "The name of the PrivateLink access",
			},
			paramNetwork: {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						paramId: {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
				Description: "The network to which this belongs.",
			},
			paramAws:   awsPrivateLinkAccessDataSourceSchema(),
			paramAzure: azurePrivateLinkAccessDataSourceSchema(),
			paramGcp:   gcpPrivateLinkAccessDataSourceSchema(),
		},
	}
}

func awsPrivateLinkAccessDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAccount: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The AWS account ID for the account containing the VPCs you want to connect from using AWS PrivateLink. You can find your AWS account ID [here](https://console.aws.amazon.com/billing/home?#/account) under **My Account** in your AWS Management Console. Must be a **12 character string**.",
				},
			},
		},
		Computed: true,
	}
}

func azurePrivateLinkAccessDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramSubscription: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The Azure subscription ID for the account containing the VNets you want to connect from using Azure Private Link. You can find your Azure subscription ID in the subscription section of your [Microsoft Azure Portal](https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade). Must be a valid **32 character UUID string**.",
				},
			},
		},
		Computed: true,
	}
}

func gcpPrivateLinkAccessDataSourceSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramProject: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The GCP project ID for the account containing the VPCs that you want to connect from using Private Service Connect. You can find your Google Cloud Project ID under **Project ID** section of your [Google Cloud Console dashboard](https://console.cloud.google.com/home/dashboard).",
				},
			},
		},
		Computed: true,
	}
}

func privateLinkAccessDataSourceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	privateLinkAccessId := d.Get(paramId).(string)
	displayName := d.Get(paramDisplayName).(string)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if environmentId == "" {
		return diag.Errorf("error reading private link access: environment Id is missing")
	}

	if privateLinkAccessId != "" {
		return privateLinkAccessDataSourceReadUsingId(ctx, d, meta, environmentId, privateLinkAccessId)
	} else if displayName != "" {
		return privateLinkAccessDataSourceReadUsingDisplayName(ctx, d, meta, environmentId, displayName)
	}
	return diag.Errorf("error reading private link access: exactly one of %q or %q must be specified but they're both empty", paramId, paramDisplayName)
}

func privateLinkAccessDataSourceReadUsingDisplayName(ctx context.Context, d *schema.ResourceData, meta interface{}, environmentId string, displayName string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading private link access %q=%q", paramDisplayName, displayName))

	c := meta.(*Client)
	privateLinkAccesses, err := loadPrivateLinkAccesses(ctx, c, environmentId)
	if err != nil {
		return diag.Errorf("error reading private link access %q: %s", displayName, createDescriptiveError(err))
	}
	if hasMultiplePrivateLinkAccessesWithDisplayName(privateLinkAccesses, displayName) {
		return diag.Errorf("error reading private link access: there are multiple private link accesss with %q=%q", paramDisplayName, displayName)
	}
	for _, privateLinkAccess := range privateLinkAccesses {
		spec := privateLinkAccess.GetSpec()
		if spec.GetDisplayName() == displayName {
			if _, err := setPrivateLinkAccessAttributes(d, privateLinkAccess); err != nil {
				return diag.FromErr(createDescriptiveError(err))
			}
			return nil
		}
	}

	return diag.Errorf("error reading private link access: private link access with %q=%q was not found", paramDisplayName, displayName)
}

func hasMultiplePrivateLinkAccessesWithDisplayName(privateLinkAccesses []networkingv1.NetworkingV1PrivateLinkAccess, displayName string) bool {
	count := 0
	for _, privateLinkAccess := range privateLinkAccesses {
		spec := privateLinkAccess.GetSpec()
		if spec.GetDisplayName() == displayName {
			count += 1
		}
	}
	return count > 1
}

func privateLinkAccessDataSourceReadUsingId(ctx context.Context, d *schema.ResourceData, meta interface{}, environmentId string, privateLinkAccessId string) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading private link access %q=%q", paramId, privateLinkAccessId), map[string]interface{}{privateLinkAccessLoggingKey: privateLinkAccessId})

	c := meta.(*Client)
	privateLinkAccess, resp, err := executePrivateLinkAccessRead(c.networkingV1ApiContext(ctx), c, environmentId, privateLinkAccessId)
	if err != nil {
		return diag.Errorf("error reading private link access %q: %s", privateLinkAccessId, createDescriptiveError(err, resp))
	}
	privateLinkAccessJson, err := json.Marshal(privateLinkAccess)
	if err != nil {
		return diag.Errorf("error reading private link access %q: error marshaling %#v to json: %s", privateLinkAccessId, privateLinkAccess, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched private link access %q: %s", privateLinkAccessId, privateLinkAccessJson), map[string]interface{}{privateLinkAccessLoggingKey: privateLinkAccessId})

	if _, err := setPrivateLinkAccessAttributes(d, privateLinkAccess); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}
	return nil
}

// loadPrivateLinkAccesses paginates through every page of the List endpoint and returns all
// private link accesss.
//
// Emitted because terraform.emit_list_all_helper is set, which happens for either of two
// reasons: a caller outside this file needs it (importers.go is the usual one), or a
// display_name lookup has to scan client-side, because the SDK's List request either has no
// DisplayName(...) filter method or could not be checked for one (no --sdk-path given).
// Which reason applies is not derivable here, so grep for callers before removing it.
func loadPrivateLinkAccesses(ctx context.Context, c *Client, environmentId string) ([]networkingv1.NetworkingV1PrivateLinkAccess, error) {
	privateLinkAccesses := make([]networkingv1.NetworkingV1PrivateLinkAccess, 0)

	allAreCollected := false
	pageToken := ""
	for !allAreCollected {
		pageList, resp, err := executeListPrivateLinkAccesses(ctx, c, environmentId, pageToken)
		if err != nil {
			return nil, fmt.Errorf("error reading private link accesss: %s", createDescriptiveError(err, resp))
		}
		privateLinkAccesses = append(privateLinkAccesses, pageList.GetData()...)

		// nextPageUrlStringNullable is nil for the last page
		nextPageUrlStringNullable := pageList.GetMetadata().Next

		if nextPageUrlStringNullable.IsSet() {
			nextPageUrlString := *nextPageUrlStringNullable.Get()
			if nextPageUrlString == "" {
				allAreCollected = true
			} else {
				pageToken, err = extractPageToken(nextPageUrlString)
				if err != nil {
					return nil, fmt.Errorf("error reading private link accesss: %s", createDescriptiveError(err, resp))
				}
			}
		} else {
			allAreCollected = true
		}
	}
	return privateLinkAccesses, nil
}

func executeListPrivateLinkAccesses(ctx context.Context, c *Client, environmentId string, pageToken string) (networkingv1.NetworkingV1PrivateLinkAccessList, *http.Response, error) {
	if pageToken != "" {
		return c.networkingV1Client.PrivateLinkAccessesNetworkingV1Api.ListNetworkingV1PrivateLinkAccesses(c.networkingV1ApiContext(ctx)).Environment(environmentId).PageSize(listPrivateLinkAccessesPageSize).PageToken(pageToken).Execute()
	} else {
		return c.networkingV1Client.PrivateLinkAccessesNetworkingV1Api.ListNetworkingV1PrivateLinkAccesses(c.networkingV1ApiContext(ctx)).Environment(environmentId).PageSize(listPrivateLinkAccessesPageSize).Execute()
	}
}
