//go:build live_test && (all || core)

// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"fmt"
	"math/rand"
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
)

// resolveResourceSubscriptionEndpoint returns the Confluent Cloud API endpoint.
// Priority: CONFLUENT_CLOUD_ENDPOINT (full URL override) > TF_ACC_ENV (shorthand) > prod default.
//
//	TF_ACC_ENV=devel  → https://api.devel.cpdev.cloud
//	TF_ACC_ENV=stag   → https://api.stag.cpdev.cloud
//	(empty or "prod")    → https://api.confluent.cloud
func resolveResourceSubscriptionEndpoint() string {
	if ep := os.Getenv("CONFLUENT_CLOUD_ENDPOINT"); ep != "" {
		return ep
	}
	switch os.Getenv("TF_ACC_ENV") {
	case "devel":
		return "https://api.devel.cpdev.cloud"
	case "stag":
		return "https://api.stag.cpdev.cloud"
	default:
		return "https://api.confluent.cloud"
	}
}

func TestAccResourceSubscriptionLive(t *testing.T) {
	// Enable parallel execution for I/O bound operations
	t.Parallel()

	// Skip this test unless explicitly enabled
	if os.Getenv("TF_ACC_PROD") == "" {
		t.Skip("Skipping live test. Set TF_ACC_PROD=1 to run this test.")
	}

	// Read credentials and configuration from environment variables (populated by Vault)
	apiKey := os.Getenv("CONFLUENT_CLOUD_API_KEY")
	apiSecret := os.Getenv("CONFLUENT_CLOUD_API_SECRET")
	endpoint := resolveResourceSubscriptionEndpoint()

	// Validate required environment variables are present
	if apiKey == "" || apiSecret == "" {
		t.Fatal("CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET must be set for live tests")
	}

	// Generate unique names for test resources to avoid conflicts
	randomSuffix := rand.Intn(100000)
	resourceSubscriptionResourceLabel := fmt.Sprintf("test_live_resource_subscription_%d", randomSuffix)
	resourceValue := fmt.Sprintf("tf_live_resource_subscription_%d", randomSuffix)
	resourceType := "CONNECTOR"
	notificationType := os.Getenv("CONFLUENT_CLOUD_NOTIFICATION_TYPE_ID")
	if notificationType == "" {
		t.Fatal("CONFLUENT_CLOUD_NOTIFICATION_TYPE_ID must be set for live tests")
	}

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckResourceSubscriptionLiveDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckResourceSubscriptionLiveConfig(endpoint, resourceSubscriptionResourceLabel, resourceValue, resourceType, notificationType, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckResourceSubscriptionLiveExists(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource", resourceValue),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource_type", resourceType),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "notification_type.0.id", notificationType),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.#", "1"),
					resource.TestCheckTypeSetElemAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.*", ""),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "id"),
				),
			},
			{
				ResourceName:      fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccResourceSubscriptionUpdateLive(t *testing.T) {
	// Enable parallel execution for I/O bound operations
	t.Parallel()

	// Skip this test unless explicitly enabled
	if os.Getenv("TF_ACC_PROD") == "" {
		t.Skip("Skipping live test. Set TF_ACC_PROD=1 to run this test.")
	}

	// Read credentials and configuration from environment variables (populated by Vault)
	apiKey := os.Getenv("CONFLUENT_CLOUD_API_KEY")
	apiSecret := os.Getenv("CONFLUENT_CLOUD_API_SECRET")
	endpoint := resolveResourceSubscriptionEndpoint()

	// Validate required environment variables are present
	if apiKey == "" || apiSecret == "" {
		t.Fatal("CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET must be set for live tests")
	}

	// Generate unique names for test resources to avoid conflicts
	randomSuffix := rand.Intn(100000)
	resourceSubscriptionResourceLabel := fmt.Sprintf("test_live_resource_subscription_update_%d", randomSuffix)
	resourceValue := fmt.Sprintf("tf_live_resource_subscription_%d", randomSuffix)
	resourceType := "CONNECTOR"
	notificationType := os.Getenv("CONFLUENT_CLOUD_NOTIFICATION_TYPE_ID")
	resourceValueUpdated := fmt.Sprintf("tf_live_resource_subscription_update_%d", randomSuffix)
	resourceTypeUpdated := resourceType
	if notificationType == "" {
		t.Fatal("CONFLUENT_CLOUD_NOTIFICATION_TYPE_ID must be set for live tests")
	}

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckResourceSubscriptionLiveDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckResourceSubscriptionLiveConfig(endpoint, resourceSubscriptionResourceLabel, resourceValue, resourceType, notificationType, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckResourceSubscriptionLiveExists(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource", resourceValue),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource_type", resourceType),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "notification_type.0.id", notificationType),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.#", "1"),
					resource.TestCheckTypeSetElemAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.*", ""),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "id"),
				),
			},
			{
				Config: testAccCheckResourceSubscriptionUpdateLiveConfig(endpoint, resourceSubscriptionResourceLabel, resourceValueUpdated, resourceTypeUpdated, notificationType, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckResourceSubscriptionLiveExists(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource", resourceValueUpdated),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource_type", resourceTypeUpdated),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "notification_type.0.id", notificationType),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.#", "1"),
					resource.TestCheckTypeSetElemAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.*", ""),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "id"),
				),
			},
		},
	})
}

func TestAccResourceSubscriptionMinimalLive(t *testing.T) {
	// Enable parallel execution for I/O bound operations
	t.Parallel()

	// Skip this test unless explicitly enabled
	if os.Getenv("TF_ACC_PROD") == "" {
		t.Skip("Skipping live test. Set TF_ACC_PROD=1 to run this test.")
	}

	// Read credentials and configuration from environment variables (populated by Vault)
	apiKey := os.Getenv("CONFLUENT_CLOUD_API_KEY")
	apiSecret := os.Getenv("CONFLUENT_CLOUD_API_SECRET")
	endpoint := resolveResourceSubscriptionEndpoint()

	// Validate required environment variables are present
	if apiKey == "" || apiSecret == "" {
		t.Fatal("CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET must be set for live tests")
	}

	// Generate unique names for test resources to avoid conflicts
	randomSuffix := rand.Intn(100000)
	resourceSubscriptionResourceLabel := fmt.Sprintf("test_live_resource_subscription_minimal_%d", randomSuffix)
	resourceValue := fmt.Sprintf("tf_live_resource_subscription_%d", randomSuffix)
	resourceType := "CONNECTOR"
	notificationType := os.Getenv("CONFLUENT_CLOUD_NOTIFICATION_TYPE_ID")
	if notificationType == "" {
		t.Fatal("CONFLUENT_CLOUD_NOTIFICATION_TYPE_ID must be set for live tests")
	}

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckResourceSubscriptionLiveDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckResourceSubscriptionMinimalLiveConfig(endpoint, resourceSubscriptionResourceLabel, resourceValue, resourceType, notificationType, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckResourceSubscriptionLiveExists(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource", resourceValue),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "resource_type", resourceType),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "notification_type.0.id", notificationType),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.#", "1"),
					resource.TestCheckTypeSetElemAttr(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "integrations.*", ""),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel), "id"),
				),
			},
		},
	})
}

func testAccCheckResourceSubscriptionLiveConfig(endpoint, resourceSubscriptionResourceLabel string, resourceValue string, resourceType string, notificationType string, apiKey, apiSecret string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint         = "%s"
		cloud_api_key    = "%s"
		cloud_api_secret = "%s"
	}

	resource "confluent_notifications_resource_subscription" "%s" {
		resource = %q
		resource_type = %q
		notification_type {
			id = %q
		}
		integrations = [""]
	}
	`, endpoint, apiKey, apiSecret, resourceSubscriptionResourceLabel, resourceValue, resourceType, notificationType)
}

func testAccCheckResourceSubscriptionMinimalLiveConfig(endpoint, resourceSubscriptionResourceLabel string, resourceValue string, resourceType string, notificationType string, apiKey, apiSecret string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint         = "%s"
		cloud_api_key    = "%s"
		cloud_api_secret = "%s"
	}

	resource "confluent_notifications_resource_subscription" "%s" {
		resource = %q
		resource_type = %q
		notification_type {
			id = %q
		}
		integrations = [""]
	}
	`, endpoint, apiKey, apiSecret, resourceSubscriptionResourceLabel, resourceValue, resourceType, notificationType)
}

func testAccCheckResourceSubscriptionUpdateLiveConfig(endpoint, resourceSubscriptionResourceLabel string, resourceValue string, resourceType string, notificationType string, apiKey, apiSecret string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint         = "%s"
		cloud_api_key    = "%s"
		cloud_api_secret = "%s"
	}

	resource "confluent_notifications_resource_subscription" "%s" {
		resource = %q
		resource_type = %q
		notification_type {
			id = %q
		}
		integrations = [""]
	}
	`, endpoint, apiKey, apiSecret, resourceSubscriptionResourceLabel, resourceValue, resourceType, notificationType)
}

func testAccCheckResourceSubscriptionLiveExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}

		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is not set")
		}

		return nil
	}
}

func testAccCheckResourceSubscriptionLiveDestroy(s *terraform.State) error {
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "confluent_notifications_resource_subscription" {
			continue
		}

		// In live tests, we can't easily check if the resource is actually destroyed
		// without making API calls, so we just verify the resource is removed from state
		if rs.Primary.ID != "" {
			// This is normal - the resource should have an ID but be removed from the live environment
			// The actual cleanup happens through the API calls during destroy
		}
	}
	return nil
}
