// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.20.2; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	networkingv1 "github.com/confluentinc/ccloud-sdk-go-v2/networking/v1"
)

// Variant kind constants
const (
	kindAwsPrivateLinkAccess           = "AwsPrivateLinkAccess"
	kindAzurePrivateLinkAccess         = "AzurePrivateLinkAccess"
	kindGcpPrivateServiceConnectAccess = "GcpPrivateServiceConnectAccess"
)

// acceptedPrivateLinkAccessCloudVariants defines the list of valid cloud block types
var acceptedPrivateLinkAccessCloudVariants = []string{paramAws, paramAzure, paramGcp}

func privateLinkAccessResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: privateLinkAccessCreate,
		ReadContext:   privateLinkAccessRead,
		UpdateContext: privateLinkAccessUpdate,
		DeleteContext: privateLinkAccessDelete,
		Importer: &schema.ResourceImporter{
			StateContext: privateLinkAccessImport,
		},
		Schema: map[string]*schema.Schema{
			paramDisplayName: {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The name of the PrivateLink access",
			},
			paramEnvironment: environmentSchema(),
			paramNetwork:     requiredNetworkSchema(),
			paramAws:         awsPrivateLinkAccessSchema(),
			paramAzure:       azurePrivateLinkAccessSchema(),
			paramGcp:         gcpPrivateLinkAccessSchema(),
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(networkingAPICreateTimeout),
			Delete: schema.DefaultTimeout(networkingAPIDeleteTimeout),
		},
	}
}

func awsPrivateLinkAccessSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAccount: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringMatch(regexp.MustCompile("^\\d{12}$"), "value must match pattern ^\\d{12}$"),
					Description:  "The AWS account ID for the account containing the VPCs you want to connect from using AWS PrivateLink. You can find your AWS account ID [here](https://console.aws.amazon.com/billing/home?#/account) under **My Account** in your AWS Management Console. Must be a **12 character string**.",
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPrivateLinkAccessCloudVariants,
	}
}

func azurePrivateLinkAccessSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramSubscription: {
					Type:        schema.TypeString,
					Required:    true,
					ForceNew:    true,
					Description: "The Azure subscription ID for the account containing the VNets you want to connect from using Azure Private Link. You can find your Azure subscription ID in the subscription section of your [Microsoft Azure Portal](https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade). Must be a valid **32 character UUID string**.",
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPrivateLinkAccessCloudVariants,
	}
}

func gcpPrivateLinkAccessSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramProject: {
					Type:        schema.TypeString,
					Required:    true,
					ForceNew:    true,
					Description: "The GCP project ID for the account containing the VPCs that you want to connect from using Private Service Connect. You can find your Google Cloud Project ID under **Project ID** section of your [Google Cloud Console dashboard](https://console.cloud.google.com/home/dashboard).",
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPrivateLinkAccessCloudVariants,
	}
}

func privateLinkAccessCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	spec := networkingv1.NewNetworkingV1PrivateLinkAccessSpec()

	// Set regular attributes
	environmentRef := networkingv1.NewObjectReferenceWithDefaults()
	environmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	spec.SetEnvironment(*environmentRef)
	networkRef := networkingv1.NewObjectReferenceWithDefaults()
	networkRef.SetId(extractStringValueFromBlock(d, paramNetwork, paramId))
	spec.SetNetwork(*networkRef)
	if _, ok := d.GetOk(paramDisplayName); ok {
		spec.SetDisplayName(d.Get(paramDisplayName).(string))
	}
	// Detect which cloud variant is specified
	_, isAwsPrivateLinkAccess := d.GetOk(paramAws)
	_, isAzurePrivateLinkAccess := d.GetOk(paramAzure)
	_, isGcpPrivateServiceConnectAccess := d.GetOk(paramGcp)

	var cloudIdentifier string

	switch {
	case isAwsPrivateLinkAccess:
		account := extractStringValueFromBlock(d, paramAws, paramAccount)
		cloudIdentifier = account
		cloudOneOf := networkingv1.NetworkingV1AwsPrivateLinkAccessAsNetworkingV1PrivateLinkAccessSpecCloudOneOf(networkingv1.NewNetworkingV1AwsPrivateLinkAccess(kindAwsPrivateLinkAccess, account))
		spec.SetCloud(cloudOneOf)
	case isAzurePrivateLinkAccess:
		subscription := extractStringValueFromBlock(d, paramAzure, paramSubscription)
		cloudIdentifier = subscription
		cloudOneOf := networkingv1.NetworkingV1AzurePrivateLinkAccessAsNetworkingV1PrivateLinkAccessSpecCloudOneOf(networkingv1.NewNetworkingV1AzurePrivateLinkAccess(kindAzurePrivateLinkAccess, subscription))
		spec.SetCloud(cloudOneOf)
	case isGcpPrivateServiceConnectAccess:
		project := extractStringValueFromBlock(d, paramGcp, paramProject)
		cloudIdentifier = project
		cloudOneOf := networkingv1.NetworkingV1GcpPrivateServiceConnectAccessAsNetworkingV1PrivateLinkAccessSpecCloudOneOf(networkingv1.NewNetworkingV1GcpPrivateServiceConnectAccess(kindGcpPrivateServiceConnectAccess, project))
		spec.SetCloud(cloudOneOf)
	default:
		return diag.Errorf("error creating private link access: expected one of %s, %s, %s params", paramAws, paramAzure, paramGcp)
	}

	createPrivateLinkAccessRequest := &networkingv1.NetworkingV1PrivateLinkAccess{Spec: spec}

	createPrivateLinkAccessRequestJson, err := json.Marshal(createPrivateLinkAccessRequest)
	if err != nil {
		return diag.Errorf("error creating private link access: error marshaling %#v to json: %s", createPrivateLinkAccessRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new private link access: %s", createPrivateLinkAccessRequestJson))

	createdPrivateLinkAccess, resp, err := executePrivateLinkAccessCreate(ctx, c, *createPrivateLinkAccessRequest)
	if err != nil {
		return diag.Errorf("error creating private link access %q: %s", cloudIdentifier, createDescriptiveError(err, resp))
	}
	d.SetId(createdPrivateLinkAccess.GetId())

	// Wait for async provisioning to complete
	createEnvironmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if err := waitForPrivateLinkAccessToProvision(c.networkingV1ApiContext(ctx), c, createEnvironmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for private link access %q to provision: %s", d.Id(), createDescriptiveError(err))
	}

	createdPrivateLinkAccessJson, err := json.Marshal(createdPrivateLinkAccess)
	if err != nil {
		return diag.Errorf("error creating private link access %q: error marshaling %#v to json: %s", d.Id(), createdPrivateLinkAccess, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating private link access %q: %s", d.Id(), createdPrivateLinkAccessJson), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	return privateLinkAccessRead(ctx, d, meta)
}

func privateLinkAccessRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading private link access %q", d.Id()), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})
	if _, err := readPrivateLinkAccessAndSetAttributes(ctx, d, meta); err != nil {
		return diag.FromErr(fmt.Errorf("error reading private link access %q: %s", d.Id(), createDescriptiveError(err)))
	}
	return nil
}

func privateLinkAccessUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName) {
		return diag.Errorf("error updating private link access %q: only %q can be updated", d.Id(), paramDisplayName)
	}

	updatePrivateLinkAccessRequest := networkingv1.NewNetworkingV1PrivateLinkAccessUpdate()
	specUpdate := networkingv1.NewNetworkingV1PrivateLinkAccessSpecUpdate()
	if d.HasChange(paramDisplayName) {
		specUpdate.SetDisplayName(d.Get(paramDisplayName).(string))
	}

	// Environment is required in the update request body for resource identification
	updateEnvironmentRef := networkingv1.NewObjectReferenceWithDefaults()
	updateEnvironmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	specUpdate.SetEnvironment(*updateEnvironmentRef)

	updatePrivateLinkAccessRequest.SetSpec(*specUpdate)

	updatePrivateLinkAccessRequestJson, err := json.Marshal(updatePrivateLinkAccessRequest)
	if err != nil {
		return diag.Errorf("error updating private link access %q: error marshaling %#v to json: %s", d.Id(), updatePrivateLinkAccessRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating private link access %q: %s", d.Id(), updatePrivateLinkAccessRequestJson), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedPrivateLinkAccess, resp, err := c.networkingV1Client.PrivateLinkAccessesNetworkingV1Api.UpdateNetworkingV1PrivateLinkAccess(c.networkingV1ApiContext(ctx), d.Id()).NetworkingV1PrivateLinkAccessUpdate(*updatePrivateLinkAccessRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating private link access %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedPrivateLinkAccessJson, err := json.Marshal(updatedPrivateLinkAccess)
	if err != nil {
		return diag.Errorf("error updating private link access %q: error marshaling %#v to json: %s", d.Id(), updatedPrivateLinkAccess, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating private link access %q: %s", d.Id(), updatedPrivateLinkAccessJson), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	return privateLinkAccessRead(ctx, d, meta)
}

func privateLinkAccessDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting private link access %q", d.Id()), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	req := c.networkingV1Client.PrivateLinkAccessesNetworkingV1Api.DeleteNetworkingV1PrivateLinkAccess(c.networkingV1ApiContext(ctx), d.Id()).Environment(environmentId)
	resp, err := req.Execute()
	if err != nil {
		return diag.Errorf("error deleting private link access %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	// Wait for async deletion to complete
	if err := waitForPrivateLinkAccessToBeDeleted(c.networkingV1ApiContext(ctx), c, environmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for private link access %q to be deleted: %s", d.Id(), createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting private link access %q", d.Id()), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	return nil
}

func executePrivateLinkAccessCreate(ctx context.Context, c *Client, privateLinkAccess networkingv1.NetworkingV1PrivateLinkAccess) (networkingv1.NetworkingV1PrivateLinkAccess, *http.Response, error) {
	req := c.networkingV1Client.PrivateLinkAccessesNetworkingV1Api.CreateNetworkingV1PrivateLinkAccess(c.networkingV1ApiContext(ctx)).NetworkingV1PrivateLinkAccess(privateLinkAccess)
	return req.Execute()
}
func executePrivateLinkAccessRead(ctx context.Context, c *Client, environmentId string, id string) (networkingv1.NetworkingV1PrivateLinkAccess, *http.Response, error) {
	req := c.networkingV1Client.PrivateLinkAccessesNetworkingV1Api.GetNetworkingV1PrivateLinkAccess(c.networkingV1ApiContext(ctx), id).Environment(environmentId)
	return req.Execute()
}

func readPrivateLinkAccessAndSetAttributes(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	privateLinkAccess, resp, err := executePrivateLinkAccessRead(ctx, c, environmentId, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading private link access %q: %s", d.Id(), readErr), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing private link access %q in TF state because private link access could not be found on the server", d.Id()), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})
			d.SetId("")
			return nil, nil
		}
		return nil, fmt.Errorf("error reading private link access %q: %s", d.Id(), readErr)
	}

	privateLinkAccessJson, err := json.Marshal(privateLinkAccess)
	if err != nil {
		return nil, fmt.Errorf("error reading private link access %q: error marshaling %#v to json: %s", privateLinkAccess.GetId(), privateLinkAccess, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched private link access %q: %s", d.Id(), privateLinkAccessJson), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	if _, err := setPrivateLinkAccessAttributes(d, privateLinkAccess); err != nil {
		// No resp: a d.Set failure is not an API error, and resp.Body is already consumed.
		return nil, fmt.Errorf("error setting private link access attributes %q: %s", d.Id(), createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished reading private link access %q", d.Id()), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	return []*schema.ResourceData{d}, nil
}

func setPrivateLinkAccessAttributes(d *schema.ResourceData, privateLinkAccess networkingv1.NetworkingV1PrivateLinkAccess) (*schema.ResourceData, error) {
	spec := privateLinkAccess.GetSpec()
	if err := d.Set(paramDisplayName, spec.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	environmentRef := spec.GetEnvironment()
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	networkRef := spec.GetNetwork()
	if err := d.Set(paramNetwork, []interface{}{map[string]interface{}{
		paramId: networkRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	oneOfCloud := spec.GetCloud()

	switch {
	case oneOfCloud.NetworkingV1AwsPrivateLinkAccess != nil:
		if err := d.Set(paramAws, []interface{}{map[string]interface{}{
			paramAccount: oneOfCloud.NetworkingV1AwsPrivateLinkAccess.GetAccount(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1AzurePrivateLinkAccess != nil:
		if err := d.Set(paramAzure, []interface{}{map[string]interface{}{
			paramSubscription: oneOfCloud.NetworkingV1AzurePrivateLinkAccess.GetSubscription(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1GcpPrivateServiceConnectAccess != nil:
		if err := d.Set(paramGcp, []interface{}{map[string]interface{}{
			paramProject: oneOfCloud.NetworkingV1GcpPrivateServiceConnectAccess.GetProject(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	}

	d.SetId(privateLinkAccess.GetId())
	return d, nil
}

func privateLinkAccessImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing private link access %q", d.Id()), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})

	envIDAndResourceId := d.Id()
	parts := strings.Split(envIDAndResourceId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing private link access: invalid format: expected '<environment ID>/<private link access ID>'")
	}
	environmentId := parts[0]
	resourceId := parts[1]
	d.SetId(resourceId)
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if _, err := readPrivateLinkAccessAndSetAttributes(ctx, d, meta); err != nil {
		return nil, fmt.Errorf("error importing private link access %q: %s", d.Id(), err)
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished importing private link access %q", d.Id()), map[string]interface{}{privateLinkAccessLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
