// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.17.1; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	iamv2 "github.com/confluentinc/ccloud-sdk-go-v2/iam/v2"
)

func invitationResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: invitationCreate,
		ReadContext:   invitationRead,
		UpdateContext: invitationUpdate,
		DeleteContext: invitationDelete,
		Importer: &schema.ResourceImporter{
			StateContext: invitationImport,
		},
		Schema: map[string]*schema.Schema{
			paramEmail: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The user/invitee's email address",
			},
			paramAuthType: {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The user/invitee's authentication type. Note that only the [OrganizationAdmin role](https://docs.confluent.io/cloud/current/access-management/access-control/cloud-rbac.html#organizationadmin) can invite AUTH_TYPE_LOCAL users to SSO organizations. The user's auth_type is set as AUTH_TYPE_SSO by default if the organization has SSO enabled. Otherwise, the user's auth_type is AUTH_TYPE_LOCAL by default.",
			},
			paramStatus: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The status of invitations",
			},
			paramAcceptedAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The timestamp that the invitation was accepted",
			},
			paramExpiresAt: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The timestamp that the invitation will expire",
			},
			paramUser:    userSchema(),
			paramCreator: creatorSchema(),
			paramAllowDeletion: {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  false,
			},
		},
	}
}

func invitationCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	createInvitationIdentifier := d.Get(paramEmail).(string)
	createInvitationRequest := iamv2.NewIamV2Invitation()

	// Set required attributes
	createInvitationRequest.SetEmail(d.Get(paramEmail).(string))

	// Set optional attributes
	if _, ok := d.GetOk(paramAuthType); ok {
		createInvitationRequest.SetAuthType(d.Get(paramAuthType).(string))
	}

	// Logging
	createInvitationRequestJson, err := json.Marshal(createInvitationRequest)
	if err != nil {
		return diag.Errorf("error creating invitation: error marshaling %#v to json: %s", createInvitationRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new invitation: %s", createInvitationRequestJson))

	// Make API call
	createdInvitation, resp, err := executeInvitationCreate(c.iamV2ApiContext(ctx), c, createInvitationRequest)
	if err != nil {
		return diag.Errorf("error creating invitation %q: %s", createInvitationIdentifier, createDescriptiveError(err, resp))
	}

	d.SetId(createdInvitation.GetId())

	// Logging
	createdInvitationJson, err := json.Marshal(createdInvitation)
	if err != nil {
		return diag.Errorf("error creating invitation %q: error marshaling %#v to json: %s", d.Id(), createdInvitation, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating invitation %q: %s", d.Id(), createdInvitationJson), map[string]interface{}{invitationLoggingKey: d.Id()})

	return invitationRead(ctx, d, meta)
}

func executeInvitationCreate(ctx context.Context, c *Client, invitation *iamv2.IamV2Invitation) (iamv2.IamV2Invitation, *http.Response, error) {
	req := c.iamV2Client.InvitationsIamV2Api.CreateIamV2Invitation(c.iamV2ApiContext(ctx)).IamV2Invitation(*invitation)
	return req.Execute()
}

func invitationRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading invitation %q", d.Id()), map[string]interface{}{invitationLoggingKey: d.Id()})

	c := meta.(*Client)
	invitation, resp, err := executeInvitationRead(c.iamV2ApiContext(ctx), c, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading invitation %q: %s", d.Id(), readErr), map[string]interface{}{invitationLoggingKey: d.Id()})

		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing invitation %q in TF state because invitation could not be found on the server", d.Id()), map[string]interface{}{invitationLoggingKey: d.Id()})
			d.SetId("")
			return nil
		}

		return diag.FromErr(readErr)
	}

	invitationJson, err := json.Marshal(invitation)
	if err != nil {
		return diag.Errorf("error reading invitation %q: error marshaling %#v to json: %s", d.Id(), invitation, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched invitation %q: %s", d.Id(), invitationJson), map[string]interface{}{invitationLoggingKey: d.Id()})

	if _, err := setInvitationAttributes(d, invitation); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	// Explicitly set paramAllowDeletion to the default value if unset.
	// Default is only applied during diff computation (plan time), not during an
	// arbitrary Read — including the post-import Read — so without this, importing
	// can leave this Optional+Default field genuinely unset rather than defaulted,
	// which shows up as a spurious diff on the next plan. Every hand-written
	// Optional+Default flag in the provider guards itself the same way —
	// resource_api_key.go / resource_tag_binding.go, and resource_schema.go /
	// resource_schema_registry_kek.go / resource_schema_registry_dek.go /
	// resource_subject_mode.go / resource_schema_registry_cluster_mode.go — each
	// carrying the identical "Must be unset when importing" doc note. Scoped to
	// this resource-only Read function (not the shared setInvitationAttributes)
	// because the data source reuses that setter too, and its schema has no
	// paramAllowDeletion key at all — calling d.Set on a key absent from the
	// current ResourceData's schema fails with "Invalid address to set", not a no-op.
	if _, ok := d.GetOk(paramAllowDeletion); !ok {
		if err := d.Set(paramAllowDeletion, d.Get(paramAllowDeletion)); err != nil {
			return diag.FromErr(createDescriptiveError(err))
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished reading invitation %q", d.Id()), map[string]interface{}{invitationLoggingKey: d.Id()})

	return nil
}

func executeInvitationRead(ctx context.Context, c *Client, invitationId string) (iamv2.IamV2Invitation, *http.Response, error) {
	req := c.iamV2Client.InvitationsIamV2Api.GetIamV2Invitation(c.iamV2ApiContext(ctx), invitationId)
	return req.Execute()
}

func setInvitationAttributes(d *schema.ResourceData, invitation iamv2.IamV2Invitation) (*schema.ResourceData, error) {
	if err := d.Set(paramEmail, invitation.GetEmail()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramAuthType, invitation.GetAuthType()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramStatus, invitation.GetStatus()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramAcceptedAt, invitation.GetAcceptedAt().String()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramExpiresAt, invitation.GetExpiresAt().String()); err != nil {
		return nil, createDescriptiveError(err)
	}
	userRef := invitation.GetUser()
	if err := d.Set(paramUser, []interface{}{map[string]interface{}{
		paramId: userRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	creatorRef := invitation.GetCreator()
	if err := d.Set(paramCreator, []interface{}{map[string]interface{}{
		paramId: creatorRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(invitation.GetId())
	return d, nil
}

func invitationUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	// No real update operation exists for this resource — every other attribute is
	// ForceNew. This Update function exists solely because allow_deletion
	// (a Terraform-only flag with no SDK field) is Optional and non-ForceNew, and the
	// Terraform SDK's InternalValidate requires an Update function for any such attribute.
	if d.HasChangesExcept(paramAllowDeletion) {
		return diag.Errorf("error updating invitation %q: only %q can be updated", d.Id(), paramAllowDeletion)
	}
	return invitationRead(ctx, d, meta)
}

func invitationDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting invitation %q", d.Id()), map[string]interface{}{invitationLoggingKey: d.Id()})

	// The API refuses to delete in this state, so a destroy would fail forever and leave the
	// user unable to get rid of the resource. paramAllowDeletion lets them drop it from
	// Terraform state instead. Deliberately opt-in: silently forgetting a resource the API
	// still holds is the wrong default.
	if d.Get(paramAllowDeletion).(bool) && d.Get(paramStatus).(string) == statusAccepted {
		tflog.Debug(ctx, fmt.Sprintf("Removing invitation %q from Terraform state without deleting it: %q is true and %q is %q", d.Id(), paramAllowDeletion, paramStatus, statusAccepted), map[string]interface{}{invitationLoggingKey: d.Id()})
		return nil
	}

	c := meta.(*Client)
	req := c.iamV2Client.InvitationsIamV2Api.DeleteIamV2Invitation(c.iamV2ApiContext(ctx), d.Id())
	resp, err := req.Execute()

	if err != nil {
		return diag.Errorf("error deleting invitation %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting invitation %q", d.Id()), map[string]interface{}{invitationLoggingKey: d.Id()})

	return nil
}

func invitationImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing invitation %q", d.Id()), map[string]interface{}{invitationLoggingKey: d.Id()})

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if diagnostics := invitationRead(ctx, d, meta); len(diagnostics) > 0 {
		return nil, fmt.Errorf("error importing invitation %q: %s", d.Id(), diagnostics[0].Summary)
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished importing invitation %q", d.Id()), map[string]interface{}{invitationLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
func userSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The unique identifier for the user.",
				},
			},
		},
		Computed:    true,
		Description: "The user/invitee",
	}
}
func creatorSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramId: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "The unique identifier for the creator.",
				},
			},
		},
		Computed:    true,
		Description: "The invitation creator",
	}
}
