// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	configurationcontrolv1 "github.com/confluentinc/ccloud-sdk-go-v2/configurationcontrol/v1"
)

const clientRequestPolicyLoggingKey = "client_request_policy_id"

func clientRequestPolicyResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: clientRequestPolicyCreate,
		ReadContext:   clientRequestPolicyRead,
		UpdateContext: clientRequestPolicyUpdate,
		DeleteContext: clientRequestPolicyDelete,
		Importer: &schema.ResourceImporter{
			StateContext: clientRequestPolicyImport,
		},
		Schema: map[string]*schema.Schema{
			paramName: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Client-supplied stable identifier for the policy. Used as the URL identifier and must be unique within the caller's organization. Immutable.",
			},
			paramPolicyType: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The policy type that supplies the variable bindings, allowed scope kinds, and allowed enforcement actions for this policy (e.g. `VersionPolicy`). The set of available types is registered by Confluent.",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The Confluent Resource Name (CRN) of the bound resource the policy applies to.",
			},
			paramMode: {
				Type:         schema.TypeString,
				Optional:     true,
				Default:      "DRAFT",
				ValidateFunc: validation.StringInSlice([]string{"DRAFT", "AUDIT", "ACTIVE"}, false),
				Description:  "Lifecycle position of the policy. `DRAFT` — stored, never evaluated. `AUDIT` — evaluated and surfaced (logs/metrics); not enforced. `ACTIVE` — evaluated and enforced according to `action`.",
			},
			paramAction: {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringInSlice([]string{"DENY", "OVERRIDE"}, false),
				Description:  "Action taken when any of the policy's rules return false on an `ACTIVE` policy. `DENY` — reject the operation. `OVERRIDE` — apply the failing rule's mutation to the resource.",
			},
			paramRules: {
				Type:        schema.TypeList,
				Required:    true,
				MinItems:    1,
				Description: "The list of CEL rules evaluated for the policy. All rules must evaluate true for the policy to pass; the platform AND-joins them at compile time.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						paramName: {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Human-readable label for the rule. Surfaced in errors, audit logs, and metrics so operators can identify which rule fired.",
						},
						paramMatch: {
							Type:        schema.TypeString,
							Required:    true,
							Description: "CEL expression returning a boolean that describes the required configuration. The rule passes when `match` returns true.",
						},
						paramMutate: {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "CEL expression returning the mutation payload to apply when `match` returns false under an `OVERRIDE` policy. Required on `OVERRIDE` policies; must be omitted on `DENY` policies.",
						},
					},
				},
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "APIVersion defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramUid: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "System-generated unique identifier for this policy.",
			},
			paramResourceVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Opaque value identifying the current version of the policy.",
			},
			paramPhase: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The lifecycle phase of the policy as reported by the server.",
			},
			paramErrorMessage: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "A human-readable message describing why the policy is in an errored state, if any.",
			},
		},
	}
}

func clientRequestPolicyCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	createClientRequestPolicyIdentifier := d.Get(paramName).(string)

	createClientRequestPolicyRequest := configurationcontrolv1.ConfigurationcontrolV1Policy{
		Metadata: &configurationcontrolv1.ObjectMeta{
			Name: createClientRequestPolicyIdentifier,
		},
		Spec: &configurationcontrolv1.ConfigurationcontrolV1PolicySpec{
			Type: d.Get(paramPolicyType).(string),
			Scope: configurationcontrolv1.ConfigurationcontrolV1PolicyScope{
				ResourceName: d.Get(paramResourceName).(string),
			},
			Mode:   configurationcontrolv1.PtrString(d.Get(paramMode).(string)),
			Action: d.Get(paramAction).(string),
			Rules:  buildClientRequestPolicyRules(d.Get(paramRules).([]interface{})),
		},
	}

	createClientRequestPolicyRequestJson, err := json.Marshal(createClientRequestPolicyRequest)
	if err != nil {
		return diag.Errorf("error creating client request policy: error marshaling %#v to json: %s", createClientRequestPolicyRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new client request policy: %s", createClientRequestPolicyRequestJson))

	createdClientRequestPolicy, resp, err := executeClientRequestPolicyCreate(c.configurationControlV1ApiContext(ctx), c, createClientRequestPolicyRequest)
	if err != nil {
		return diag.Errorf("error creating client request policy %q: %s", createClientRequestPolicyIdentifier, createDescriptiveError(err, resp))
	}

	d.SetId(createdClientRequestPolicy.Metadata.GetName())

	createdClientRequestPolicyJson, err := json.Marshal(createdClientRequestPolicy)
	if err != nil {
		return diag.Errorf("error creating client request policy %q: error marshaling %#v to json: %s", d.Id(), createdClientRequestPolicy, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating client request policy %q: %s", d.Id(), createdClientRequestPolicyJson), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	return clientRequestPolicyRead(ctx, d, meta)
}

func executeClientRequestPolicyCreate(ctx context.Context, c *Client, policy configurationcontrolv1.ConfigurationcontrolV1Policy) (configurationcontrolv1.ConfigurationcontrolV1Policy, *http.Response, error) {
	req := c.configurationControlV1Client.PoliciesConfigurationcontrolV1Api.CreateConfigurationcontrolV1Policy(c.configurationControlV1ApiContext(ctx)).ConfigurationcontrolV1Policy(policy)
	return req.Execute()
}

func clientRequestPolicyRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading client request policy %q", d.Id()), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	c := meta.(*Client)
	clientRequestPolicy, resp, err := executeClientRequestPolicyRead(c.configurationControlV1ApiContext(ctx), c, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading client request policy %q: %s", d.Id(), readErr), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing client request policy %q in TF state because client request policy could not be found on the server", d.Id()), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})
			d.SetId("")
			return nil
		}

		return diag.FromErr(readErr)
	}

	clientRequestPolicyJson, err := json.Marshal(clientRequestPolicy)
	if err != nil {
		return diag.Errorf("error reading client request policy %q: error marshaling %#v to json: %s", d.Id(), clientRequestPolicy, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched client request policy %q: %s", d.Id(), clientRequestPolicyJson), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	if _, err := setClientRequestPolicyAttributes(d, clientRequestPolicy); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished reading client request policy %q", d.Id()), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	return nil
}

func executeClientRequestPolicyRead(ctx context.Context, c *Client, policyName string) (configurationcontrolv1.ConfigurationcontrolV1Policy, *http.Response, error) {
	req := c.configurationControlV1Client.PoliciesConfigurationcontrolV1Api.GetConfigurationcontrolV1Policy(c.configurationControlV1ApiContext(ctx), policyName)
	return req.Execute()
}

func setClientRequestPolicyAttributes(d *schema.ResourceData, policy configurationcontrolv1.ConfigurationcontrolV1Policy) (*schema.ResourceData, error) {
	metadata := policy.GetMetadata()
	spec := policy.GetSpec()
	scope := spec.GetScope()
	status := policy.GetStatus()

	if err := d.Set(paramName, metadata.GetName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramPolicyType, spec.GetType()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceName, scope.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramMode, spec.GetMode()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramAction, spec.GetAction()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramRules, flattenClientRequestPolicyRules(spec.GetRules())); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramApiVersion, policy.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, policy.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramUid, metadata.GetUid()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceVersion, metadata.GetResourceVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramPhase, status.GetPhase()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramErrorMessage, status.GetErrorMessage()); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(metadata.GetName())
	return d, nil
}

func clientRequestPolicyUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramMode, paramAction, paramRules) {
		return diag.Errorf("error updating client request policy %q: only %q, %q, %q can be updated", d.Id(), paramMode, paramAction, paramRules)
	}

	updateClientRequestPolicyRequest := configurationcontrolv1.ConfigurationcontrolV1PolicyUpdate{
		Spec: &configurationcontrolv1.ConfigurationcontrolV1PolicySpecUpdate{
			Mode:   configurationcontrolv1.PtrString(d.Get(paramMode).(string)),
			Action: d.Get(paramAction).(string),
			Rules:  buildClientRequestPolicyRules(d.Get(paramRules).([]interface{})),
		},
	}

	updateClientRequestPolicyRequestJson, err := json.Marshal(updateClientRequestPolicyRequest)
	if err != nil {
		return diag.Errorf("error updating client request policy %q: error marshaling %#v to json: %s", d.Id(), updateClientRequestPolicyRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating client request policy %q: %s", d.Id(), updateClientRequestPolicyRequestJson), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedClientRequestPolicy, resp, err := c.configurationControlV1Client.PoliciesConfigurationcontrolV1Api.UpdateConfigurationcontrolV1Policy(c.configurationControlV1ApiContext(ctx), d.Id()).ConfigurationcontrolV1PolicyUpdate(updateClientRequestPolicyRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating client request policy %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedClientRequestPolicyJson, err := json.Marshal(updatedClientRequestPolicy)
	if err != nil {
		return diag.Errorf("error updating client request policy %q: error marshaling %#v to json: %s", d.Id(), updatedClientRequestPolicy, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating client request policy %q: %s", d.Id(), updatedClientRequestPolicyJson), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	return clientRequestPolicyRead(ctx, d, meta)
}

func clientRequestPolicyDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting client request policy %q", d.Id()), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})
	c := meta.(*Client)
	req := c.configurationControlV1Client.PoliciesConfigurationcontrolV1Api.DeleteConfigurationcontrolV1Policy(c.configurationControlV1ApiContext(ctx), d.Id())
	resp, err := req.Execute()

	if err != nil {
		return diag.Errorf("error deleting client request policy %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting client request policy %q", d.Id()), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	return nil
}

func clientRequestPolicyImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing client request policy %q", d.Id()), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if diagnostics := clientRequestPolicyRead(ctx, d, meta); len(diagnostics) > 0 {
		return nil, fmt.Errorf("error importing client request policy %q: %s", d.Id(), diagnostics[0].Summary)
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished importing client request policy %q", d.Id()), map[string]interface{}{clientRequestPolicyLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}

func buildClientRequestPolicyRules(rawRules []interface{}) []configurationcontrolv1.ConfigurationcontrolV1PolicyRule {
	rules := make([]configurationcontrolv1.ConfigurationcontrolV1PolicyRule, len(rawRules))
	for i, rawRule := range rawRules {
		block := rawRule.(map[string]interface{})
		rule := configurationcontrolv1.ConfigurationcontrolV1PolicyRule{
			Name:  block[paramName].(string),
			Match: block[paramMatch].(string),
		}
		if mutate, ok := block[paramMutate].(string); ok && mutate != "" {
			rule.Mutate = configurationcontrolv1.PtrString(mutate)
		}
		rules[i] = rule
	}
	return rules
}

func flattenClientRequestPolicyRules(rules []configurationcontrolv1.ConfigurationcontrolV1PolicyRule) []interface{} {
	flattened := make([]interface{}, len(rules))
	for i, rule := range rules {
		flattened[i] = map[string]interface{}{
			paramName:   rule.GetName(),
			paramMatch:  rule.GetMatch(),
			paramMutate: rule.GetMutate(),
		}
	}
	return flattened
}
