// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	networkingdnsforwarderv1 "github.com/confluentinc/ccloud-sdk-go-v2/networking-dnsforwarder/v1"
)

// Variant kind constants
const (
	kindForwardViaIp          = "ForwardViaIp"
	kindForwardViaGcpDnsZones = "ForwardViaGcpDnsZones"
)

// acceptedDnsForwarderConfigVariants defines the list of valid config block types
var acceptedDnsForwarderConfigVariants = []string{paramForwardViaIp, paramForwardViaGcpDnsZones}

// Timeout constants for async operations
const (
	networkingDnsforwarderV1DnsForwarderAPICreateTimeout = 1 * time.Hour
)

const dnsForwarderLoggingKey = "dns_forwarder_id"

func dnsForwarderResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: dnsForwarderCreate,
		ReadContext:   dnsForwarderRead,
		UpdateContext: dnsForwarderUpdate,
		DeleteContext: dnsForwarderDelete,
		Importer: &schema.ResourceImporter{
			StateContext: dnsForwarderImport,
		},
		Schema: map[string]*schema.Schema{
			paramDisplayName: {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The name of the DNS forwarder",
			},
			paramDomains: {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Required:    true,
				Description: "List of domains for the DNS forwarder to use",
			},
			paramEnvironment:           environmentSchema(),
			paramGateway:               requiredGateway(),
			paramForwardViaIp:          forwardViaIpDnsForwarderSchema(),
			paramForwardViaGcpDnsZones: forwardViaGcpDnsZonesDnsForwarderSchema(),
		},
	}
}

func forwardViaIpDnsForwarderSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramForwardViaIpDnsServerIps: {
					Type:     schema.TypeSet,
					Elem:     &schema.Schema{Type: schema.TypeString},
					Optional: true,
					Computed: true,
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedDnsForwarderConfigVariants,
	}
}

func forwardViaGcpDnsZonesDnsForwarderSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramForwardViaGcpDnsZonesDomainMappings: {
					Type: schema.TypeMap,
					Elem: &schema.Schema{
						Type:         schema.TypeString,
						ValidateFunc: validation.StringMatch(regexp.MustCompile("^[^,]+,[^,]+$"), "Exactly 2 strings separated by a comma"),
					},
					Optional: true,
					Computed: true,
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedDnsForwarderConfigVariants,
	}
}

func dnsForwarderCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	spec := networkingdnsforwarderv1.NewNetworkingV1DnsForwarderSpec()

	// Set regular attributes
	spec.SetDomains(convertToStringSlice(d.Get(paramDomains).(*schema.Set).List()))
	environmentRef := networkingdnsforwarderv1.NewObjectReferenceWithDefaults()
	environmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	spec.SetEnvironment(*environmentRef)
	gatewayRef := networkingdnsforwarderv1.NewObjectReferenceWithDefaults()
	gatewayRef.SetId(extractStringValueFromBlock(d, paramGateway, paramId))
	spec.SetGateway(*gatewayRef)
	if _, ok := d.GetOk(paramDisplayName); ok {
		spec.SetDisplayName(d.Get(paramDisplayName).(string))
	}
	// Detect which config variant is specified
	_, isForwardViaIp := d.GetOk(paramForwardViaIp)
	_, isForwardViaGcpDnsZones := d.GetOk(paramForwardViaGcpDnsZones)

	var configIdentifier string

	switch {
	case isForwardViaIp:
		dnsServerIps := convertToStringSlice(d.Get(fmt.Sprintf("%s.0.%s", paramForwardViaIp, paramForwardViaIpDnsServerIps)).(*schema.Set).List())
		configOneOf := networkingdnsforwarderv1.NetworkingV1ForwardViaIpAsNetworkingV1DnsForwarderSpecConfigOneOf(networkingdnsforwarderv1.NewNetworkingV1ForwardViaIp(kindForwardViaIp, dnsServerIps))
		spec.SetConfig(configOneOf)
	case isForwardViaGcpDnsZones:
		domainMappings := buildDomainMappings(d, paramForwardViaGcpDnsZones, paramForwardViaGcpDnsZonesDomainMappings)
		configOneOf := networkingdnsforwarderv1.NetworkingV1ForwardViaGcpDnsZonesAsNetworkingV1DnsForwarderSpecConfigOneOf(networkingdnsforwarderv1.NewNetworkingV1ForwardViaGcpDnsZones(kindForwardViaGcpDnsZones, domainMappings))
		spec.SetConfig(configOneOf)
	default:
		return diag.Errorf("error creating DNS forwarder: expected one of %s, %s params", paramForwardViaIp, paramForwardViaGcpDnsZones)
	}

	createDnsForwarderRequest := &networkingdnsforwarderv1.NetworkingV1DnsForwarder{Spec: spec}

	createDnsForwarderRequestJson, err := json.Marshal(createDnsForwarderRequest)
	if err != nil {
		return diag.Errorf("error creating DNS forwarder: error marshaling %#v to json: %s", createDnsForwarderRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new DNS forwarder: %s", createDnsForwarderRequestJson))

	createdDnsForwarder, resp, err := executeDnsForwarderCreate(ctx, c, *createDnsForwarderRequest)
	if err != nil {
		return diag.Errorf("error creating DNS forwarder %q: %s", configIdentifier, createDescriptiveError(err, resp))
	}
	d.SetId(createdDnsForwarder.GetId())

	// Wait for async provisioning to complete
	createEnvironmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if err := waitForDnsForwarderToProvision(c.networkingDnsforwarderV1ApiContext(ctx), c, createEnvironmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for DNS forwarder %q to provision: %s", d.Id(), createDescriptiveError(err))
	}

	createdDnsForwarderJson, err := json.Marshal(createdDnsForwarder)
	if err != nil {
		return diag.Errorf("error creating DNS forwarder %q: error marshaling %#v to json: %s", d.Id(), createdDnsForwarder, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating DNS forwarder %q: %s", d.Id(), createdDnsForwarderJson), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	return dnsForwarderRead(ctx, d, meta)
}

func dnsForwarderRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading DNS forwarder %q", d.Id()), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})
	if _, err := readDnsForwarderAndSetAttributes(ctx, d, meta); err != nil {
		return diag.FromErr(fmt.Errorf("error reading DNS forwarder %q: %s", d.Id(), createDescriptiveError(err)))
	}
	return nil
}

func dnsForwarderUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName, paramDomains) {
		return diag.Errorf("error updating DNS forwarder %q: only %q, %q can be updated", d.Id(), paramDisplayName, paramDomains)
	}

	updateDnsForwarderRequest := networkingdnsforwarderv1.NewNetworkingV1DnsForwarderUpdate()
	specUpdate := networkingdnsforwarderv1.NewNetworkingV1DnsForwarderSpecUpdate()
	if d.HasChange(paramDisplayName) {
		specUpdate.SetDisplayName(d.Get(paramDisplayName).(string))
	}
	if d.HasChange(paramDomains) {
		specUpdate.SetDomains(convertToStringSlice(d.Get(paramDomains).(*schema.Set).List()))
	}

	// Environment is required in the update request body for resource identification
	updateEnvironmentRef := networkingdnsforwarderv1.NewObjectReferenceWithDefaults()
	updateEnvironmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	specUpdate.SetEnvironment(*updateEnvironmentRef)

	updateDnsForwarderRequest.SetSpec(*specUpdate)

	updateDnsForwarderRequestJson, err := json.Marshal(updateDnsForwarderRequest)
	if err != nil {
		return diag.Errorf("error updating DNS forwarder %q: error marshaling %#v to json: %s", d.Id(), updateDnsForwarderRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating DNS forwarder %q: %s", d.Id(), updateDnsForwarderRequestJson), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedDnsForwarder, resp, err := c.networkingDnsforwarderV1Client.DNSForwardersNetworkingV1Api.UpdateNetworkingV1DnsForwarder(c.networkingDnsforwarderV1ApiContext(ctx), d.Id()).NetworkingV1DnsForwarderUpdate(*updateDnsForwarderRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating DNS forwarder %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedDnsForwarderJson, err := json.Marshal(updatedDnsForwarder)
	if err != nil {
		return diag.Errorf("error updating DNS forwarder %q: error marshaling %#v to json: %s", d.Id(), updatedDnsForwarder, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating DNS forwarder %q: %s", d.Id(), updatedDnsForwarderJson), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	return dnsForwarderRead(ctx, d, meta)
}

func dnsForwarderDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting DNS forwarder %q", d.Id()), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	req := c.networkingDnsforwarderV1Client.DNSForwardersNetworkingV1Api.DeleteNetworkingV1DnsForwarder(c.networkingDnsforwarderV1ApiContext(ctx), d.Id()).Environment(environmentId)
	resp, err := req.Execute()
	if err != nil {
		return diag.Errorf("error deleting DNS forwarder %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting DNS forwarder %q", d.Id()), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	return nil
}

func executeDnsForwarderCreate(ctx context.Context, c *Client, dnsForwarder networkingdnsforwarderv1.NetworkingV1DnsForwarder) (networkingdnsforwarderv1.NetworkingV1DnsForwarder, *http.Response, error) {
	req := c.networkingDnsforwarderV1Client.DNSForwardersNetworkingV1Api.CreateNetworkingV1DnsForwarder(c.networkingDnsforwarderV1ApiContext(ctx)).NetworkingV1DnsForwarder(dnsForwarder)
	return req.Execute()
}
func executeDnsForwarderRead(ctx context.Context, c *Client, environmentId string, id string) (networkingdnsforwarderv1.NetworkingV1DnsForwarder, *http.Response, error) {
	req := c.networkingDnsforwarderV1Client.DNSForwardersNetworkingV1Api.GetNetworkingV1DnsForwarder(c.networkingDnsforwarderV1ApiContext(ctx), id).Environment(environmentId)
	return req.Execute()
}

func readDnsForwarderAndSetAttributes(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	dnsForwarder, resp, err := executeDnsForwarderRead(ctx, c, environmentId, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading DNS forwarder %q: %s", d.Id(), readErr), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing DNS forwarder %q in TF state because DNS forwarder could not be found on the server", d.Id()), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})
			d.SetId("")
			return nil, nil
		}
		return nil, fmt.Errorf("error reading DNS forwarder %q: %s", d.Id(), readErr)
	}

	dnsForwarderJson, err := json.Marshal(dnsForwarder)
	if err != nil {
		return nil, fmt.Errorf("error reading DNS forwarder %q: error marshaling %#v to json: %s", dnsForwarder.GetId(), dnsForwarder, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched DNS forwarder %q: %s", d.Id(), dnsForwarderJson), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	if _, err := setDnsForwarderAttributes(d, dnsForwarder); err != nil {
		// No resp: a d.Set failure is not an API error, and resp.Body is already consumed.
		return nil, fmt.Errorf("error setting DNS forwarder attributes %q: %s", d.Id(), createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished reading DNS forwarder %q", d.Id()), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	return []*schema.ResourceData{d}, nil
}

func setDnsForwarderAttributes(d *schema.ResourceData, dnsForwarder networkingdnsforwarderv1.NetworkingV1DnsForwarder) (*schema.ResourceData, error) {
	spec := dnsForwarder.GetSpec()
	if err := d.Set(paramDisplayName, spec.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramDomains, spec.GetDomains()); err != nil {
		return nil, createDescriptiveError(err)
	}
	environmentRef := spec.GetEnvironment()
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	gatewayRef := spec.GetGateway()
	if err := d.Set(paramGateway, []interface{}{map[string]interface{}{
		paramId: gatewayRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	oneOfConfig := spec.GetConfig()

	switch {
	case oneOfConfig.NetworkingV1ForwardViaIp != nil:
		if err := d.Set(paramForwardViaIp, []interface{}{map[string]interface{}{
			paramForwardViaIpDnsServerIps: oneOfConfig.NetworkingV1ForwardViaIp.GetDnsServerIps(),
		}}); err != nil {
			return nil, err
		}
	case oneOfConfig.NetworkingV1ForwardViaGcpDnsZones != nil:
		if err := d.Set(paramForwardViaGcpDnsZones, []interface{}{map[string]interface{}{
			paramForwardViaGcpDnsZonesDomainMappings: flattenDomainMappings(oneOfConfig.NetworkingV1ForwardViaGcpDnsZones.GetDomainMappings()),
		}}); err != nil {
			return nil, err
		}
	}

	d.SetId(dnsForwarder.GetId())
	return d, nil
}

func dnsForwarderImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing DNS forwarder %q", d.Id()), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})

	envIDAndResourceId := d.Id()
	parts := strings.Split(envIDAndResourceId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing DNS forwarder: invalid format: expected '<environment ID>/<DNS forwarder ID>'")
	}
	environmentId := parts[0]
	resourceId := parts[1]
	d.SetId(resourceId)
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if _, err := readDnsForwarderAndSetAttributes(ctx, d, meta); err != nil {
		return nil, fmt.Errorf("error importing DNS forwarder %q: %s", d.Id(), err)
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished importing DNS forwarder %q", d.Id()), map[string]interface{}{dnsForwarderLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
