// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	certificateauthorityv2 "github.com/confluentinc/ccloud-sdk-go-v2/certificate-authority/v2"
)

func certificatePoolResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: certificatePoolCreate,
		ReadContext:   certificatePoolRead,
		UpdateContext: certificatePoolUpdate,
		DeleteContext: certificatePoolDelete,
		Importer: &schema.ResourceImporter{
			StateContext: certificatePoolImport,
		},
		Schema: map[string]*schema.Schema{
			paramCertificateAuthority: certificateAuthoritySchema(),
			paramDisplayName: {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringIsNotEmpty,
				Description:  "The name of the certificate identity pool.",
			},
			paramDescription: {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringIsNotEmpty,
				Description:  "A description of how this certificate identity pool is used.",
			},
			paramExternalIdentifier: {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringIsNotEmpty,
				Description:  "The certificate field that will be used to represent the pool's external identifier for audit logging.",
			},
			paramFilter: {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringLenBetween(0, 300),
				Description:  "A filter expression in [Supported Common Expression Language (CEL)](https://docs.confluent.io/cloud/current/access-management/authenticate/mtls/cel-filters.html) that specifies which identities can authenticate using your certificate identity pool (see [CEL filter for mTLS](https://docs.confluent.io/cloud/current/access-management/authenticate/mtls/cel-filters.html) for more details).",
			},
			paramPrincipal: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Represents the federated identity associated with this pool.",
			},
			paramState: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The current state of the certificate identity pool.",
			},
		},
	}
}

func certificatePoolCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	createCertificatePoolIdentifier := d.Get(paramDisplayName).(string)
	createCertificatePoolRequest := certificateauthorityv2.NewIamV2CertificateIdentityPool()

	// Set required attributes
	createCertificatePoolRequest.SetDisplayName(d.Get(paramDisplayName).(string))
	createCertificatePoolRequest.SetDescription(d.Get(paramDescription).(string))
	createCertificatePoolRequest.SetExternalIdentifier(d.Get(paramExternalIdentifier).(string))
	createCertificatePoolRequest.SetFilter(d.Get(paramFilter).(string))

	// Set optional attributes

	// Logging
	createCertificatePoolRequestJson, err := json.Marshal(createCertificatePoolRequest)
	if err != nil {
		return diag.Errorf("error creating certificate pool: error marshaling %#v to json: %s", createCertificatePoolRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new certificate pool: %s", createCertificatePoolRequestJson))

	// Make API call
	certificateAuthorityId := extractStringValueFromBlock(d, paramCertificateAuthority, paramId)
	createdCertificatePool, resp, err := executeCertificatePoolCreate(c.certificateAuthorityV2ApiContext(ctx), c, createCertificatePoolRequest, certificateAuthorityId)
	if err != nil {
		return diag.Errorf("error creating certificate pool %q: %s", createCertificatePoolIdentifier, createDescriptiveError(err, resp))
	}

	d.SetId(createdCertificatePool.GetId())

	// Logging
	createdCertificatePoolJson, err := json.Marshal(createdCertificatePool)
	if err != nil {
		return diag.Errorf("error creating certificate pool %q: error marshaling %#v to json: %s", d.Id(), createdCertificatePool, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating certificate pool %q: %s", d.Id(), createdCertificatePoolJson), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	return certificatePoolRead(ctx, d, meta)
}

func executeCertificatePoolCreate(ctx context.Context, c *Client, certificatePool *certificateauthorityv2.IamV2CertificateIdentityPool, certificateAuthorityId string) (certificateauthorityv2.IamV2CertificateIdentityPool, *http.Response, error) {
	req := c.certificateAuthorityV2Client.CertificateIdentityPoolsIamV2Api.CreateIamV2CertificateIdentityPool(c.certificateAuthorityV2ApiContext(ctx), certificateAuthorityId).IamV2CertificateIdentityPool(*certificatePool)
	return req.Execute()
}

func certificatePoolRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading certificate pool %q", d.Id()), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	c := meta.(*Client)
	certificateAuthorityId := extractStringValueFromBlock(d, paramCertificateAuthority, paramId)
	certificatePool, resp, err := executeCertificatePoolRead(c.certificateAuthorityV2ApiContext(ctx), c, certificateAuthorityId, d.Id())
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Error reading certificate pool %q: %s", d.Id(), createDescriptiveError(err, resp)), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing certificate pool %q in TF state because certificate pool could not be found on the server", d.Id()), map[string]interface{}{certificatePoolLoggingKey: d.Id()})
			d.SetId("")
			return nil
		}

		return diag.FromErr(createDescriptiveError(err, resp))
	}

	certificatePoolJson, err := json.Marshal(certificatePool)
	if err != nil {
		return diag.Errorf("error reading certificate pool %q: error marshaling %#v to json: %s", d.Id(), certificatePool, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched certificate pool %q: %s", d.Id(), certificatePoolJson), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	if _, err := setCertificatePoolAttributes(d, certificatePool); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished reading certificate pool %q", d.Id()), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	return nil
}

func executeCertificatePoolRead(ctx context.Context, c *Client, certificateAuthorityId string, certificatePoolId string) (certificateauthorityv2.IamV2CertificateIdentityPool, *http.Response, error) {
	req := c.certificateAuthorityV2Client.CertificateIdentityPoolsIamV2Api.GetIamV2CertificateIdentityPool(c.certificateAuthorityV2ApiContext(ctx), certificateAuthorityId, certificatePoolId)
	return req.Execute()
}

func setCertificatePoolAttributes(d *schema.ResourceData, certificatePool certificateauthorityv2.IamV2CertificateIdentityPool) (*schema.ResourceData, error) {
	if err := d.Set(paramDisplayName, certificatePool.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramDescription, certificatePool.GetDescription()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramExternalIdentifier, certificatePool.GetExternalIdentifier()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramFilter, certificatePool.GetFilter()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramPrincipal, certificatePool.GetPrincipal()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramState, certificatePool.GetState()); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(certificatePool.GetId())
	return d, nil
}

func certificatePoolUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName, paramDescription, paramExternalIdentifier, paramFilter) {
		return diag.Errorf("error updating certificate pool %q: only %q, %q, %q, %q can be updated", d.Id(), paramDisplayName, paramDescription, paramExternalIdentifier, paramFilter)
	}

	updateCertificatePoolRequest := certificateauthorityv2.NewIamV2CertificateIdentityPool()
	updateCertificatePoolRequest.SetDisplayName(d.Get(paramDisplayName).(string))
	updateCertificatePoolRequest.SetDescription(d.Get(paramDescription).(string))
	updateCertificatePoolRequest.SetExternalIdentifier(d.Get(paramExternalIdentifier).(string))
	updateCertificatePoolRequest.SetFilter(d.Get(paramFilter).(string))

	updateCertificatePoolRequestJson, err := json.Marshal(updateCertificatePoolRequest)
	if err != nil {
		return diag.Errorf("error updating certificate pool %q: error marshaling %#v to json: %s", d.Id(), updateCertificatePoolRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating certificate pool %q: %s", d.Id(), updateCertificatePoolRequestJson), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	c := meta.(*Client)
	certificateAuthorityId := extractStringValueFromBlock(d, paramCertificateAuthority, paramId)
	updatedCertificatePool, resp, err := c.certificateAuthorityV2Client.CertificateIdentityPoolsIamV2Api.UpdateIamV2CertificateIdentityPool(c.certificateAuthorityV2ApiContext(ctx), certificateAuthorityId, d.Id()).IamV2CertificateIdentityPool(*updateCertificatePoolRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating certificate pool %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedCertificatePoolJson, err := json.Marshal(updatedCertificatePool)
	if err != nil {
		return diag.Errorf("error updating certificate pool %q: error marshaling %#v to json: %s", d.Id(), updatedCertificatePool, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating certificate pool %q: %s", d.Id(), updatedCertificatePoolJson), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	return certificatePoolRead(ctx, d, meta)
}

func certificatePoolDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting certificate pool %q", d.Id()), map[string]interface{}{certificatePoolLoggingKey: d.Id()})
	certificateAuthorityId := extractStringValueFromBlock(d, paramCertificateAuthority, paramId)
	c := meta.(*Client)
	req := c.certificateAuthorityV2Client.CertificateIdentityPoolsIamV2Api.DeleteIamV2CertificateIdentityPool(c.certificateAuthorityV2ApiContext(ctx), certificateAuthorityId, d.Id())
	_, resp, err := req.Execute()

	if err != nil {
		return diag.Errorf("error deleting certificate pool %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting certificate pool %q", d.Id()), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	return nil
}

func certificatePoolImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing certificate pool %q", d.Id()), map[string]interface{}{certificatePoolLoggingKey: d.Id()})

	importId := d.Id()
	parts := strings.Split(importId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing certificate pool: invalid format: expected '<Certificate Authority ID>/<certificate pool ID>'")
	}
	certificateAuthorityId := parts[0]
	resourceId := parts[len(parts)-1]
	d.SetId(resourceId)
	if err := d.Set(paramCertificateAuthority, []interface{}{map[string]interface{}{
		paramId: certificateAuthorityId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if diagnostics := certificatePoolRead(ctx, d, meta); len(diagnostics) > 0 {
		return nil, fmt.Errorf("error importing certificate pool %q: %s", d.Id(), diagnostics[0].Summary)
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished importing certificate pool %q", d.Id()), map[string]interface{}{certificatePoolLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
func certificateAuthoritySchema() *schema.Schema {
	return &schema.Schema{
		Type:     schema.TypeList,
		Required: true,
		MinItems: 1,
		MaxItems: 1,
		ForceNew: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramId: {
					Type:        schema.TypeString,
					Required:    true,
					ForceNew:    true,
					Description: "The unique identifier for the certificate authority.",
				},
			},
		},
		Description: "The certificate authority that the resource belongs to.",
	}
}
