// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2/notifications/v1"
)

// Variant kind constants
const (
	kindSlackTarget     = "SlackTarget"
	kindRoleEmailTarget = "RoleEmailTarget"
	kindUserEmailTarget = "UserEmailTarget"
	kindWebhookTarget   = "WebhookTarget"
	kindMsTeamsTarget   = "MsTeamsTarget"
	kindInAppTarget     = "InAppTarget"
)

// acceptedTargetVariants defines the list of valid, user-settable target
// block types. Variants the API forbids creating/updating/deleting are Computed-only and
// excluded here — see OneOfVariant.ReadOnly.
var acceptedTargetVariants = []string{paramSlackTarget, paramWebhookTarget, paramMsTeamsTarget}

const integrationLoggingKey = "integration_id"

func integrationResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: integrationCreate,
		ReadContext:   integrationRead,
		UpdateContext: integrationUpdate,
		DeleteContext: integrationDelete,
		Importer: &schema.ResourceImporter{
			StateContext: integrationImport,
		},
		Schema: map[string]*schema.Schema{
			paramDisplayName: {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringLenBetween(0, 64),
				Description:  "A human readable name for the particular integration",
			},
			paramDescription: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringLenBetween(0, 128),
				Description:  "A human readable description for the particular integration",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Integration.",
			},
			paramSlackTarget:     slackTargetIntegrationSchema(),
			paramRoleEmailTarget: roleEmailTargetIntegrationSchema(),
			paramUserEmailTarget: userEmailTargetIntegrationSchema(),
			paramWebhookTarget:   webhookTargetIntegrationSchema(),
			paramMsTeamsTarget:   msTeamsTargetIntegrationSchema(),
			paramInAppTarget:     inAppTargetIntegrationSchema(),
		},
	}
}

func slackTargetIntegrationSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramSlackTargetWebhookUrl: {
					Type:         schema.TypeString,
					Required:     true,
					ValidateFunc: validation.IsURLWithHTTPorHTTPS,
				},
			},
		},
		Optional:     true,
		Computed:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedTargetVariants,
	}
}

func roleEmailTargetIntegrationSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramRoleEmailTargetRoleName: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func userEmailTargetIntegrationSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramUserEmailTargetUser: {
					Type: schema.TypeList,
					Elem: &schema.Resource{
						Schema: map[string]*schema.Schema{
							paramId: {
								Type:     schema.TypeString,
								Computed: true,
							},
						},
					},
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func webhookTargetIntegrationSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramWebhookTargetUrl: {
					Type:         schema.TypeString,
					Required:     true,
					ValidateFunc: validation.IsURLWithHTTPorHTTPS,
				},
			},
		},
		Optional:     true,
		Computed:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedTargetVariants,
	}
}

func msTeamsTargetIntegrationSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramMsTeamsTargetWebhookUrl: {
					Type:         schema.TypeString,
					Required:     true,
					ValidateFunc: validation.IsURLWithHTTPorHTTPS,
				},
			},
		},
		Optional:     true,
		Computed:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedTargetVariants,
	}
}

func inAppTargetIntegrationSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramInAppTargetUser: {
					Type: schema.TypeList,
					Elem: &schema.Resource{
						Schema: map[string]*schema.Schema{
							paramId: {
								Type:     schema.TypeString,
								Computed: true,
							},
						},
					},
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func integrationCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	createIntegrationRequest := notificationsv1.NewNotificationsV1Integration()

	// Set regular attributes
	createIntegrationRequest.SetDisplayName(d.Get(paramDisplayName).(string))
	if _, ok := d.GetOk(paramDescription); ok {
		createIntegrationRequest.SetDescription(d.Get(paramDescription).(string))
	}
	// Detect which target variant is specified. Variants the API forbids
	// creating (OneOfVariant.ReadOnly) are Computed-only and never reach here — a user
	// can't set them in HCL, so there's nothing to dispatch on.
	_, isSlackTarget := d.GetOk(paramSlackTarget)
	_, isWebhookTarget := d.GetOk(paramWebhookTarget)
	_, isMsTeamsTarget := d.GetOk(paramMsTeamsTarget)

	var targetIdentifier string

	switch {
	case isSlackTarget:
		webhookUrl := extractStringValueFromBlock(d, paramSlackTarget, paramSlackTargetWebhookUrl)
		targetIdentifier = webhookUrl
		targetOneOf := notificationsv1.NotificationsV1SlackTargetAsNotificationsV1Target(notificationsv1.NewNotificationsV1SlackTarget(kindSlackTarget, webhookUrl))
		createIntegrationRequest.SetTarget(targetOneOf)
	case isWebhookTarget:
		url := extractStringValueFromBlock(d, paramWebhookTarget, paramWebhookTargetUrl)
		targetIdentifier = url
		targetOneOf := notificationsv1.NotificationsV1WebhookTargetAsNotificationsV1Target(notificationsv1.NewNotificationsV1WebhookTarget(kindWebhookTarget, url))
		createIntegrationRequest.SetTarget(targetOneOf)
	case isMsTeamsTarget:
		webhookUrl := extractStringValueFromBlock(d, paramMsTeamsTarget, paramMsTeamsTargetWebhookUrl)
		targetIdentifier = webhookUrl
		targetOneOf := notificationsv1.NotificationsV1MsTeamsTargetAsNotificationsV1Target(notificationsv1.NewNotificationsV1MsTeamsTarget(kindMsTeamsTarget, webhookUrl))
		createIntegrationRequest.SetTarget(targetOneOf)
	default:
		return diag.Errorf("error creating integration: expected one of %s, %s, %s params", paramSlackTarget, paramWebhookTarget, paramMsTeamsTarget)
	}

	createIntegrationRequestJson, err := json.Marshal(createIntegrationRequest)
	if err != nil {
		return diag.Errorf("error creating integration: error marshaling %#v to json: %s", createIntegrationRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new integration: %s", createIntegrationRequestJson))

	createdIntegration, resp, err := executeIntegrationCreate(ctx, c, *createIntegrationRequest)
	if err != nil {
		return diag.Errorf("error creating integration %q: %s", targetIdentifier, createDescriptiveError(err, resp))
	}
	d.SetId(createdIntegration.GetId())

	createdIntegrationJson, err := json.Marshal(createdIntegration)
	if err != nil {
		return diag.Errorf("error creating integration %q: error marshaling %#v to json: %s", d.Id(), createdIntegration, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating integration %q: %s", d.Id(), createdIntegrationJson), map[string]interface{}{integrationLoggingKey: d.Id()})

	return integrationRead(ctx, d, meta)
}

func integrationDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting integration %q", d.Id()), map[string]interface{}{integrationLoggingKey: d.Id()})

	c := meta.(*Client)

	req := c.notificationsV1Client.IntegrationsNotificationsV1Api.DeleteNotificationsV1Integration(c.notificationsV1ApiContext(ctx), d.Id())
	resp, err := req.Execute()
	if err != nil {
		return diag.Errorf("error deleting integration %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting integration %q", d.Id()), map[string]interface{}{integrationLoggingKey: d.Id()})

	return nil
}

func integrationRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading integration %q", d.Id()), map[string]interface{}{integrationLoggingKey: d.Id()})
	if _, err := readIntegrationAndSetAttributes(ctx, d, meta); err != nil {
		return diag.FromErr(fmt.Errorf("error reading integration %q: %s", d.Id(), createDescriptiveError(err)))
	}
	return nil
}

func integrationUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName, paramDescription, paramSlackTarget, paramWebhookTarget, paramMsTeamsTarget) {
		return diag.Errorf("error updating integration %q: only %q, %q, %q, %q, %q can be updated", d.Id(), paramDisplayName, paramDescription, paramSlackTarget, paramWebhookTarget, paramMsTeamsTarget)
	}

	updateIntegrationRequest := notificationsv1.NewNotificationsV1Integration()
	if d.HasChange(paramDisplayName) {
		updateIntegrationRequest.SetDisplayName(d.Get(paramDisplayName).(string))
	}
	if d.HasChange(paramDescription) {
		updateIntegrationRequest.SetDescription(d.Get(paramDescription).(string))
	}

	if d.HasChanges(paramSlackTarget, paramWebhookTarget, paramMsTeamsTarget) {
		_, isSlackTargetUpdate := d.GetOk(paramSlackTarget)
		_, isWebhookTargetUpdate := d.GetOk(paramWebhookTarget)
		_, isMsTeamsTargetUpdate := d.GetOk(paramMsTeamsTarget)

		switch {
		case isSlackTargetUpdate:
			webhookUrl := extractStringValueFromBlock(d, paramSlackTarget, paramSlackTargetWebhookUrl)
			targetOneOfUpdate := notificationsv1.NotificationsV1SlackTargetAsNotificationsV1Target(notificationsv1.NewNotificationsV1SlackTarget(kindSlackTarget, webhookUrl))
			updateIntegrationRequest.SetTarget(targetOneOfUpdate)
		case isWebhookTargetUpdate:
			url := extractStringValueFromBlock(d, paramWebhookTarget, paramWebhookTargetUrl)
			targetOneOfUpdate := notificationsv1.NotificationsV1WebhookTargetAsNotificationsV1Target(notificationsv1.NewNotificationsV1WebhookTarget(kindWebhookTarget, url))
			updateIntegrationRequest.SetTarget(targetOneOfUpdate)
		case isMsTeamsTargetUpdate:
			webhookUrl := extractStringValueFromBlock(d, paramMsTeamsTarget, paramMsTeamsTargetWebhookUrl)
			targetOneOfUpdate := notificationsv1.NotificationsV1MsTeamsTargetAsNotificationsV1Target(notificationsv1.NewNotificationsV1MsTeamsTarget(kindMsTeamsTarget, webhookUrl))
			updateIntegrationRequest.SetTarget(targetOneOfUpdate)
		}
	}

	updateIntegrationRequestJson, err := json.Marshal(updateIntegrationRequest)
	if err != nil {
		return diag.Errorf("error updating integration %q: error marshaling %#v to json: %s", d.Id(), updateIntegrationRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating integration %q: %s", d.Id(), updateIntegrationRequestJson), map[string]interface{}{integrationLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedIntegration, resp, err := c.notificationsV1Client.IntegrationsNotificationsV1Api.UpdateNotificationsV1Integration(c.notificationsV1ApiContext(ctx), d.Id()).NotificationsV1Integration(*updateIntegrationRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating integration %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedIntegrationJson, err := json.Marshal(updatedIntegration)
	if err != nil {
		return diag.Errorf("error updating integration %q: error marshaling %#v to json: %s", d.Id(), updatedIntegration, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating integration %q: %s", d.Id(), updatedIntegrationJson), map[string]interface{}{integrationLoggingKey: d.Id()})

	return integrationRead(ctx, d, meta)
}

func executeIntegrationCreate(ctx context.Context, c *Client, integration notificationsv1.NotificationsV1Integration) (notificationsv1.NotificationsV1Integration, *http.Response, error) {
	req := c.notificationsV1Client.IntegrationsNotificationsV1Api.CreateNotificationsV1Integration(c.notificationsV1ApiContext(ctx)).NotificationsV1Integration(integration)
	return req.Execute()
}
func executeIntegrationRead(ctx context.Context, c *Client, id string) (notificationsv1.NotificationsV1Integration, *http.Response, error) {
	req := c.notificationsV1Client.IntegrationsNotificationsV1Api.GetNotificationsV1Integration(c.notificationsV1ApiContext(ctx), id)
	return req.Execute()
}

func readIntegrationAndSetAttributes(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	c := meta.(*Client)
	integration, resp, err := executeIntegrationRead(ctx, c, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading integration %q: %s", d.Id(), readErr), map[string]interface{}{integrationLoggingKey: d.Id()})
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing integration %q in TF state because integration could not be found on the server", d.Id()), map[string]interface{}{integrationLoggingKey: d.Id()})
			d.SetId("")
			return nil, nil
		}
		return nil, fmt.Errorf("error reading integration %q: %s", d.Id(), readErr)
	}

	integrationJson, err := json.Marshal(integration)
	if err != nil {
		return nil, fmt.Errorf("error reading integration %q: error marshaling %#v to json: %s", integration.GetId(), integration, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched integration %q: %s", d.Id(), integrationJson), map[string]interface{}{integrationLoggingKey: d.Id()})

	if _, err := setIntegrationAttributes(d, integration); err != nil {
		// No resp: a d.Set failure is not an API error, and resp.Body is already consumed.
		return nil, fmt.Errorf("error setting integration attributes %q: %s", d.Id(), createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished reading integration %q", d.Id()), map[string]interface{}{integrationLoggingKey: d.Id()})

	return []*schema.ResourceData{d}, nil
}

func setIntegrationAttributes(d *schema.ResourceData, integration notificationsv1.NotificationsV1Integration) (*schema.ResourceData, error) {
	if err := d.Set(paramDisplayName, integration.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramDescription, integration.GetDescription()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramApiVersion, integration.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, integration.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceName, integration.Metadata.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	oneOfTarget := integration.GetTarget()

	// Read-only variants are Computed-only: clear them so an unmatched one is known, not
	// "known after apply" on every plan. The switch below populates the one that matches.
	if err := d.Set(paramRoleEmailTarget, []interface{}{}); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramUserEmailTarget, []interface{}{}); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramInAppTarget, []interface{}{}); err != nil {
		return nil, createDescriptiveError(err)
	}

	switch {
	case oneOfTarget.NotificationsV1SlackTarget != nil:
		if err := d.Set(paramSlackTarget, []interface{}{map[string]interface{}{
			paramSlackTargetWebhookUrl: oneOfTarget.NotificationsV1SlackTarget.GetWebhookUrl(),
		}}); err != nil {
			return nil, err
		}
	case oneOfTarget.NotificationsV1RoleEmailTarget != nil:
		if err := d.Set(paramRoleEmailTarget, []interface{}{map[string]interface{}{
			paramRoleEmailTargetRoleName: oneOfTarget.NotificationsV1RoleEmailTarget.GetRoleName(),
		}}); err != nil {
			return nil, err
		}
	case oneOfTarget.NotificationsV1UserEmailTarget != nil:
		// Hoist to a local var: GetId() has a pointer receiver, can't chain off a value-returning getter.
		userEmailTargetUserRef := oneOfTarget.NotificationsV1UserEmailTarget.GetUser()
		if err := d.Set(paramUserEmailTarget, []interface{}{map[string]interface{}{
			paramUserEmailTargetUser: []interface{}{map[string]interface{}{
				paramId: userEmailTargetUserRef.GetId(),
			}},
		}}); err != nil {
			return nil, err
		}
	case oneOfTarget.NotificationsV1WebhookTarget != nil:
		if err := d.Set(paramWebhookTarget, []interface{}{map[string]interface{}{
			paramWebhookTargetUrl: oneOfTarget.NotificationsV1WebhookTarget.GetUrl(),
		}}); err != nil {
			return nil, err
		}
	case oneOfTarget.NotificationsV1MsTeamsTarget != nil:
		if err := d.Set(paramMsTeamsTarget, []interface{}{map[string]interface{}{
			paramMsTeamsTargetWebhookUrl: oneOfTarget.NotificationsV1MsTeamsTarget.GetWebhookUrl(),
		}}); err != nil {
			return nil, err
		}
	case oneOfTarget.NotificationsV1InAppTarget != nil:
		// Hoist to a local var: GetId() has a pointer receiver, can't chain off a value-returning getter.
		inAppTargetUserRef := oneOfTarget.NotificationsV1InAppTarget.GetUser()
		if err := d.Set(paramInAppTarget, []interface{}{map[string]interface{}{
			paramInAppTargetUser: []interface{}{map[string]interface{}{
				paramId: inAppTargetUserRef.GetId(),
			}},
		}}); err != nil {
			return nil, err
		}
	}

	d.SetId(integration.GetId())
	return d, nil
}

func integrationImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing integration %q", d.Id()), map[string]interface{}{integrationLoggingKey: d.Id()})

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if _, err := readIntegrationAndSetAttributes(ctx, d, meta); err != nil {
		return nil, fmt.Errorf("error importing integration %q: %s", d.Id(), err)
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished importing integration %q", d.Id()), map[string]interface{}{integrationLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
