// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	switchoverv1 "github.com/confluentinc/ccloud-sdk-go-v2/switchover/v1"
)

// Parameter name constants
const (
	paramActiveMember = "active_member"
	paramMembers      = "members"
)

// Timeout constants for async operations
const (
	switchoverV1APICreateTimeout = 1 * time.Hour
	switchoverV1APIDeleteTimeout = 1 * time.Hour
)

// State constants for async provisioning
const (
	stateSwitching = "SWITCHING"
	stateSwitched  = "SWITCHED"
)

const switchoverPairLoggingKey = "switchover_pair_id"

func switchoverPair() *schema.Resource {
	return &schema.Resource{
		CreateContext: switchoverPairCreate,
		ReadContext:   switchoverPairRead,
		UpdateContext: switchoverPairUpdate,
		DeleteContext: switchoverPairDelete,
		Importer: &schema.ResourceImporter{
			StateContext: switchoverPairImport,
		},
		Schema: map[string]*schema.Schema{
			paramActiveMember: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The name of the member that is currently active. On create, this selects which member starts as active; it must match one of the `members[].name` values. Changing this after creation triggers a declarative failover (the `:failover` operation).",
			},
			paramDisplayName: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "A human-readable name for the switchover pair.",
			},
			paramEnvironment: environmentSchema(),
			paramMembers: {
				Type:        schema.TypeList,
				Required:    true,
				ForceNew:    true,
				Description: "The two clusters participating in this switchover pair. Must contain exactly 2 members.",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the resource.",
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(switchoverV1APICreateTimeout),
			Delete: schema.DefaultTimeout(switchoverV1APIDeleteTimeout),
		},
	}
}

func switchoverPairCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	spec := switchoverv1.NewSwitchoverV1SwitchoverPairSpec()

	// Set required attributes
	spec.SetActiveMember(d.Get(paramActiveMember).(string))
	spec.SetDisplayName(d.Get(paramDisplayName).(string))
	environmentRef := switchoverv1.NewEnvScopedObjectReferenceWithDefaults()
	environmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	spec.SetEnvironment(*environmentRef)
	spec.SetMembers(d.Get(paramMembers).(string))

	// Set optional attributes

	createSwitchoverPairRequest := &switchoverv1.SwitchoverV1SwitchoverPair{Spec: spec}

	// Logging
	createSwitchoverPairRequestJson, err := json.Marshal(createSwitchoverPairRequest)
	if err != nil {
		return diag.Errorf("error creating SwitchoverPair: error marshaling %#v to json: %s", createSwitchoverPairRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new SwitchoverPair: %s", createSwitchoverPairRequestJson))

	// Make API call
	createdSwitchoverPair, resp, err := executeSwitchoverPairCreate(c.switchoverV1ApiContext(ctx), c, createSwitchoverPairRequest)
	if err != nil {
		return diag.Errorf("error creating SwitchoverPair: %s", createDescriptiveError(err, resp))
	}
	d.SetId(createdSwitchoverPair.GetId())
	createEnvironmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	// Wait for async provisioning to complete
	if err := waitForSwitchoverPairToProvision(c.switchoverV1ApiContext(ctx), c, createEnvironmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for SwitchoverPair %q to provision: %s", d.Id(), createDescriptiveError(err))
	}

	// Logging
	createdSwitchoverPairJson, err := json.Marshal(createdSwitchoverPair)
	if err != nil {
		return diag.Errorf("error creating SwitchoverPair %q: error marshaling %#v to json: %s", d.Id(), createdSwitchoverPair, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating SwitchoverPair %q: %s", d.Id(), createdSwitchoverPairJson), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	return switchoverPairRead(ctx, d, meta)
}

func executeSwitchoverPairCreate(ctx context.Context, c *Client, switchoverPair *switchoverv1.SwitchoverV1SwitchoverPair) (switchoverv1.SwitchoverV1SwitchoverPair, *http.Response, error) {
	req := c.switchoverV1Client.SwitchoverPairsSwitchoverV1Api.CreateSwitchoverV1SwitchoverPair(c.switchoverV1ApiContext(ctx)).SwitchoverV1SwitchoverPair(*switchoverPair)
	return req.Execute()
}

func switchoverPairRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading SwitchoverPair %q", d.Id()), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	switchoverPair, resp, err := executeSwitchoverPairRead(c.switchoverV1ApiContext(ctx), c, environmentId, d.Id())
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Error reading SwitchoverPair %q: %s", d.Id(), createDescriptiveError(err, resp)), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing SwitchoverPair %q in TF state because SwitchoverPair could not be found on the server", d.Id()), map[string]interface{}{switchoverPairLoggingKey: d.Id()})
			d.SetId("")
			return nil
		}

		return diag.FromErr(createDescriptiveError(err, resp))
	}

	switchoverPairJson, err := json.Marshal(switchoverPair)
	if err != nil {
		return diag.Errorf("error reading SwitchoverPair %q: error marshaling %#v to json: %s", d.Id(), switchoverPair, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched SwitchoverPair %q: %s", d.Id(), switchoverPairJson), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	if _, err := setSwitchoverPairAttributes(d, switchoverPair); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished reading SwitchoverPair %q", d.Id()), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	return nil
}

func executeSwitchoverPairRead(ctx context.Context, c *Client, environmentId string, switchoverPairId string) (switchoverv1.SwitchoverV1SwitchoverPair, *http.Response, error) {
	req := c.switchoverV1Client.SwitchoverPairsSwitchoverV1Api.GetSwitchoverV1SwitchoverPair(c.switchoverV1ApiContext(ctx), switchoverPairId).Environment(environmentId)
	return req.Execute()
}

func setSwitchoverPairAttributes(d *schema.ResourceData, switchoverPair switchoverv1.SwitchoverV1SwitchoverPair) (*schema.ResourceData, error) {
	spec := switchoverPair.GetSpec()
	if err := d.Set(paramActiveMember, spec.GetActiveMember()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramDisplayName, spec.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	environmentRef := spec.GetEnvironment()
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramMembers, spec.GetMembers()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramApiVersion, switchoverPair.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, switchoverPair.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceName, switchoverPair.Metadata.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(switchoverPair.GetId())
	return d, nil
}

func switchoverPairUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName, paramActiveMember) {
		return diag.Errorf("error updating SwitchoverPair %q: only %q and %q can be updated", d.Id(), paramDisplayName, paramActiveMember)
	}

	c := meta.(*Client)

	// A change to active_member is a declarative failover: promote the new active member via the
	// :failover operation rather than a plain spec update.
	if d.HasChange(paramActiveMember) {
		failoverRequest := switchoverv1.NewSwitchoverV1SwitchoverPairFailoverRequest()
		failoverRequest.SetActiveMember(d.Get(paramActiveMember).(string))
		req := c.switchoverV1Client.SwitchoverPairsSwitchoverV1Api.FailoverSwitchoverV1SwitchoverPair(c.switchoverV1ApiContext(ctx), d.Id()).SwitchoverV1SwitchoverPairFailoverRequest(*failoverRequest)
		if _, resp, err := req.Execute(); err != nil {
			return diag.Errorf("error triggering failover for SwitchoverPair %q: %s", d.Id(), createDescriptiveError(err, resp))
		}
		if !d.HasChange(paramDisplayName) {
			return switchoverPairRead(ctx, d, meta)
		}
	}

	updateSwitchoverPairRequest := switchoverv1.NewSwitchoverV1SwitchoverPair()
	specUpdate := switchoverv1.NewSwitchoverV1SwitchoverPairSpecUpdate()
	if d.HasChange(paramDisplayName) {
		specUpdate.SetDisplayName(d.Get(paramDisplayName).(string))
	}

	// Environment is required in the update request body for resource identification
	updateEnvironmentRef := switchoverv1.NewEnvScopedObjectReferenceWithDefaults()
	updateEnvironmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	specUpdate.SetEnvironment(*updateEnvironmentRef)

	updateSwitchoverPairRequest.SetSpec(*specUpdate)

	updateSwitchoverPairRequestJson, err := json.Marshal(updateSwitchoverPairRequest)
	if err != nil {
		return diag.Errorf("error updating SwitchoverPair %q: error marshaling %#v to json: %s", d.Id(), updateSwitchoverPairRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating SwitchoverPair %q: %s", d.Id(), updateSwitchoverPairRequestJson), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	updatedSwitchoverPair, resp, err := c.switchoverV1Client.SwitchoverPairsSwitchoverV1Api.UpdateSwitchoverV1SwitchoverPair(c.switchoverV1ApiContext(ctx), d.Id()).SwitchoverV1SwitchoverPair(*updateSwitchoverPairRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating SwitchoverPair %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedSwitchoverPairJson, err := json.Marshal(updatedSwitchoverPair)
	if err != nil {
		return diag.Errorf("error updating SwitchoverPair %q: error marshaling %#v to json: %s", d.Id(), updatedSwitchoverPair, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating SwitchoverPair %q: %s", d.Id(), updatedSwitchoverPairJson), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	return switchoverPairRead(ctx, d, meta)
}

func switchoverPairDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting SwitchoverPair %q", d.Id()), map[string]interface{}{switchoverPairLoggingKey: d.Id()})
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	c := meta.(*Client)
	req := c.switchoverV1Client.SwitchoverPairsSwitchoverV1Api.DeleteSwitchoverV1SwitchoverPair(c.switchoverV1ApiContext(ctx), d.Id()).Environment(environmentId)
	resp, err := req.Execute()

	if err != nil {
		return diag.Errorf("error deleting SwitchoverPair %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	// Wait for async deletion to complete
	if err := waitForSwitchoverPairToBeDeleted(c.switchoverV1ApiContext(ctx), c, environmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for SwitchoverPair %q to be deleted: %s", d.Id(), createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting SwitchoverPair %q", d.Id()), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	return nil
}

func switchoverPairImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing SwitchoverPair %q", d.Id()), map[string]interface{}{switchoverPairLoggingKey: d.Id()})

	importId := d.Id()
	parts := strings.Split(importId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing SwitchoverPair: invalid format: expected '<environment ID>/<SwitchoverPair ID>'")
	}
	environmentId := parts[0]
	resourceId := parts[len(parts)-1]
	d.SetId(resourceId)
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if diagnostics := switchoverPairRead(ctx, d, meta); diagnostics != nil {
		return nil, fmt.Errorf("error importing SwitchoverPair %q: %s", d.Id(), diagnostics[0].Summary)
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished importing SwitchoverPair %q", d.Id()), map[string]interface{}{switchoverPairLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}

// switchoverPairProvisionStatus returns a StateRefreshFunc for polling the resource status
func switchoverPairProvisionStatus(ctx context.Context, c *Client, environmentId string, switchoverPairId string) resource.StateRefreshFunc {
	return func() (result interface{}, s string, err error) {
		switchoverPair, resp, err := executeSwitchoverPairRead(c.switchoverV1ApiContext(ctx), c, environmentId, switchoverPairId)
		if err != nil {
			tflog.Warn(ctx, fmt.Sprintf("Error reading SwitchoverPair %q: %s", switchoverPairId, createDescriptiveError(err, resp)), map[string]interface{}{switchoverPairLoggingKey: switchoverPairId})
			return nil, stateUnknown, err
		}

		currentPhase := switchoverPair.Status.GetPhase()
		tflog.Debug(ctx, fmt.Sprintf("Waiting for SwitchoverPair %q provisioning status to become one of %v: current status is %q", switchoverPairId, []string{stateReady, stateSwitching, stateSwitched}, currentPhase), map[string]interface{}{switchoverPairLoggingKey: switchoverPairId})

		// Check for pending states (still provisioning)
		switch currentPhase {
		case stateProvisioning:
			return switchoverPair, currentPhase, nil
		}

		// Check for target states (provisioning complete)
		switch currentPhase {
		case stateReady:
			return switchoverPair, currentPhase, nil
		case stateSwitching:
			return switchoverPair, currentPhase, nil
		case stateSwitched:
			return switchoverPair, currentPhase, nil
		}

		// Check for failed states
		switch currentPhase {
		case stateError:
			return nil, stateError, fmt.Errorf("SwitchoverPair %q provisioning status is %q", switchoverPairId, stateError)
		}

		// Unexpected state
		return nil, stateUnexpected, fmt.Errorf("SwitchoverPair %q is in an unexpected state %q", switchoverPairId, currentPhase)
	}
}

// waitForSwitchoverPairToProvision waits for the resource to reach a ready state
func waitForSwitchoverPairToProvision(ctx context.Context, c *Client, environmentId string, switchoverPairId string) error {
	delay, pollInterval := getDelayAndPollInterval(5*time.Second, 1*time.Minute, c.isAcceptanceTestMode)
	stateConf := &resource.StateChangeConf{
		Pending:      []string{stateProvisioning},
		Target:       []string{stateReady, stateSwitching, stateSwitched},
		Refresh:      switchoverPairProvisionStatus(ctx, c, environmentId, switchoverPairId),
		Timeout:      switchoverV1APICreateTimeout,
		Delay:        delay,
		PollInterval: pollInterval,
	}

	tflog.Debug(ctx, fmt.Sprintf("Waiting for SwitchoverPair %q provisioning status to become one of %v", switchoverPairId, []string{stateReady, stateSwitching, stateSwitched}), map[string]interface{}{switchoverPairLoggingKey: switchoverPairId})
	if _, err := stateConf.WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}

// switchoverPairDeleteStatus returns a StateRefreshFunc for polling the delete status
func switchoverPairDeleteStatus(ctx context.Context, c *Client, environmentId string, switchoverPairId string) resource.StateRefreshFunc {
	return func() (result interface{}, s string, err error) {
		switchoverPair, resp, err := executeSwitchoverPairRead(c.switchoverV1ApiContext(ctx), c, environmentId, switchoverPairId)
		if err != nil {
			if isNonKafkaRestApiResourceNotFound(resp) {
				// Resource is deleted
				return switchoverPair, "DELETED", nil
			}
			tflog.Warn(ctx, fmt.Sprintf("Error reading SwitchoverPair %q: %s", switchoverPairId, createDescriptiveError(err, resp)), map[string]interface{}{switchoverPairLoggingKey: switchoverPairId})
			return nil, stateUnknown, err
		}

		// Resource still exists
		return switchoverPair, "DELETING", nil
	}
}

// waitForSwitchoverPairToBeDeleted waits for the resource to be fully deleted
func waitForSwitchoverPairToBeDeleted(ctx context.Context, c *Client, environmentId string, switchoverPairId string) error {
	delay, pollInterval := getDelayAndPollInterval(5*time.Second, 1*time.Minute, c.isAcceptanceTestMode)
	stateConf := &resource.StateChangeConf{
		Pending:      []string{"DELETING"},
		Target:       []string{"DELETED"},
		Refresh:      switchoverPairDeleteStatus(ctx, c, environmentId, switchoverPairId),
		Timeout:      switchoverV1APIDeleteTimeout,
		Delay:        delay,
		PollInterval: pollInterval,
	}

	tflog.Debug(ctx, fmt.Sprintf("Waiting for SwitchoverPair %q to be deleted", switchoverPairId), map[string]interface{}{switchoverPairLoggingKey: switchoverPairId})
	if _, err := stateConf.WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}
