//go:build live_test && (all || core)

// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"fmt"
	"math/rand"
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
)

// resolveGroupMappingEndpoint returns the Confluent Cloud API endpoint.
// Priority: CONFLUENT_CLOUD_ENDPOINT (full URL override) > TF_ACC_ENV (shorthand) > prod default.
//
//	TF_ACC_ENV=devel  → https://api.devel.cpdev.cloud
//	TF_ACC_ENV=stag   → https://api.stag.cpdev.cloud
//	(empty or "prod")    → https://api.confluent.cloud
func resolveGroupMappingEndpoint() string {
	if ep := os.Getenv("CONFLUENT_CLOUD_ENDPOINT"); ep != "" {
		return ep
	}
	switch os.Getenv("TF_ACC_ENV") {
	case "devel":
		return "https://api.devel.cpdev.cloud"
	case "stag":
		return "https://api.stag.cpdev.cloud"
	default:
		return "https://api.confluent.cloud"
	}
}

func TestAccGroupMappingLive(t *testing.T) {
	// Enable parallel execution for I/O bound operations
	t.Parallel()

	// Skip this test unless explicitly enabled
	if os.Getenv("TF_ACC_PROD") == "" {
		t.Skip("Skipping live test. Set TF_ACC_PROD=1 to run this test.")
	}

	// Read credentials and configuration from environment variables (populated by Vault)
	apiKey := os.Getenv("CONFLUENT_CLOUD_API_KEY")
	apiSecret := os.Getenv("CONFLUENT_CLOUD_API_SECRET")
	endpoint := resolveGroupMappingEndpoint()

	// Validate required environment variables are present
	if apiKey == "" || apiSecret == "" {
		t.Fatal("CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET must be set for live tests")
	}

	// Generate unique names for test resources to avoid conflicts
	randomSuffix := rand.Intn(100000)
	groupMappingResourceLabel := fmt.Sprintf("test_live_group_mapping_%d", randomSuffix)
	displayName := fmt.Sprintf("tf_live_group_mapping_%d", randomSuffix)
	filter := fmt.Sprintf("tf_live_group_mapping_%d", randomSuffix)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckGroupMappingLiveDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckGroupMappingLiveConfig(endpoint, groupMappingResourceLabel, displayName, filter, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckGroupMappingLiveExists(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "display_name", displayName),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "filter", filter),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "id"),
				),
			},
			{
				ResourceName:      fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccGroupMappingUpdateLive(t *testing.T) {
	// Enable parallel execution for I/O bound operations
	t.Parallel()

	// Skip this test unless explicitly enabled
	if os.Getenv("TF_ACC_PROD") == "" {
		t.Skip("Skipping live test. Set TF_ACC_PROD=1 to run this test.")
	}

	// Read credentials and configuration from environment variables (populated by Vault)
	apiKey := os.Getenv("CONFLUENT_CLOUD_API_KEY")
	apiSecret := os.Getenv("CONFLUENT_CLOUD_API_SECRET")
	endpoint := resolveGroupMappingEndpoint()

	// Validate required environment variables are present
	if apiKey == "" || apiSecret == "" {
		t.Fatal("CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET must be set for live tests")
	}

	// Generate unique names for test resources to avoid conflicts
	randomSuffix := rand.Intn(100000)
	groupMappingResourceLabel := fmt.Sprintf("test_live_group_mapping_update_%d", randomSuffix)
	displayName := fmt.Sprintf("tf_live_group_mapping_%d", randomSuffix)
	filter := fmt.Sprintf("tf_live_group_mapping_%d", randomSuffix)
	displayNameUpdated := fmt.Sprintf("tf_live_group_mapping_update_%d", randomSuffix)
	filterUpdated := fmt.Sprintf("tf_live_group_mapping_update_%d", randomSuffix)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckGroupMappingLiveDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckGroupMappingLiveConfig(endpoint, groupMappingResourceLabel, displayName, filter, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckGroupMappingLiveExists(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "display_name", displayName),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "filter", filter),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "id"),
				),
			},
			{
				Config: testAccCheckGroupMappingUpdateLiveConfig(endpoint, groupMappingResourceLabel, displayNameUpdated, filterUpdated, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckGroupMappingLiveExists(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "display_name", displayNameUpdated),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "filter", filterUpdated),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "id"),
				),
			},
		},
	})
}

func TestAccGroupMappingMinimalLive(t *testing.T) {
	// Enable parallel execution for I/O bound operations
	t.Parallel()

	// Skip this test unless explicitly enabled
	if os.Getenv("TF_ACC_PROD") == "" {
		t.Skip("Skipping live test. Set TF_ACC_PROD=1 to run this test.")
	}

	// Read credentials and configuration from environment variables (populated by Vault)
	apiKey := os.Getenv("CONFLUENT_CLOUD_API_KEY")
	apiSecret := os.Getenv("CONFLUENT_CLOUD_API_SECRET")
	endpoint := resolveGroupMappingEndpoint()

	// Validate required environment variables are present
	if apiKey == "" || apiSecret == "" {
		t.Fatal("CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET must be set for live tests")
	}

	// Generate unique names for test resources to avoid conflicts
	randomSuffix := rand.Intn(100000)
	groupMappingResourceLabel := fmt.Sprintf("test_live_group_mapping_minimal_%d", randomSuffix)
	displayName := fmt.Sprintf("tf_live_group_mapping_%d", randomSuffix)
	filter := fmt.Sprintf("tf_live_group_mapping_%d", randomSuffix)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckGroupMappingLiveDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckGroupMappingMinimalLiveConfig(endpoint, groupMappingResourceLabel, displayName, filter, apiKey, apiSecret),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckGroupMappingLiveExists(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel)),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "display_name", displayName),
					resource.TestCheckResourceAttr(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "filter", filter),
					resource.TestCheckResourceAttrSet(fmt.Sprintf("confluent_group_mapping.%s", groupMappingResourceLabel), "id"),
				),
			},
		},
	})
}

func testAccCheckGroupMappingLiveConfig(endpoint, groupMappingResourceLabel string, displayName string, filter string, apiKey, apiSecret string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint         = "%s"
		cloud_api_key    = "%s"
		cloud_api_secret = "%s"
	}

	resource "confluent_group_mapping" "%s" {
		display_name = %q
		filter = %q
	}
	`, endpoint, apiKey, apiSecret, groupMappingResourceLabel, displayName, filter)
}

func testAccCheckGroupMappingMinimalLiveConfig(endpoint, groupMappingResourceLabel string, displayName string, filter string, apiKey, apiSecret string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint         = "%s"
		cloud_api_key    = "%s"
		cloud_api_secret = "%s"
	}

	resource "confluent_group_mapping" "%s" {
		display_name = %q
		filter = %q
	}
	`, endpoint, apiKey, apiSecret, groupMappingResourceLabel, displayName, filter)
}

func testAccCheckGroupMappingUpdateLiveConfig(endpoint, groupMappingResourceLabel string, displayName string, filter string, apiKey, apiSecret string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint         = "%s"
		cloud_api_key    = "%s"
		cloud_api_secret = "%s"
	}

	resource "confluent_group_mapping" "%s" {
		display_name = %q
		filter = %q
	}
	`, endpoint, apiKey, apiSecret, groupMappingResourceLabel, displayName, filter)
}

func testAccCheckGroupMappingLiveExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}

		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is not set")
		}

		return nil
	}
}

func testAccCheckGroupMappingLiveDestroy(s *terraform.State) error {
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "confluent_group_mapping" {
			continue
		}

		// In live tests, we can't easily check if the resource is actually destroyed
		// without making API calls, so we just verify the resource is removed from state
		if rs.Primary.ID != "" {
			// This is normal - the resource should have an ID but be removed from the live environment
			// The actual cleanup happens through the API calls during destroy
		}
	}
	return nil
}
