// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.12.3; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	networkingprivatelinkv1 "github.com/confluentinc/ccloud-sdk-go-v2/networking-privatelink/v1"
)

// Variant kind constants
const (
	kindAwsPrivateLinkAttachmentConnection   = "AwsPrivateLinkAttachmentConnection"
	kindAzurePrivateLinkAttachmentConnection = "AzurePrivateLinkAttachmentConnection"
	kindGcpPrivateLinkAttachmentConnection   = "GcpPrivateLinkAttachmentConnection"
)

// acceptedPrivateLinkAttachmentConnectionCloudVariants defines the list of valid cloud block types
var acceptedPrivateLinkAttachmentConnectionCloudVariants = []string{paramAws, paramAzure, paramGcp}

// State constants for async provisioning
const (
	statePrivateLinkAttachmentConnectionProvisioning = "PROVISIONING"
	statePrivateLinkAttachmentConnectionReady        = "READY"
	statePrivateLinkAttachmentConnectionFailed       = "FAILED"
	statePrivateLinkAttachmentConnectionDisconnected = "DISCONNECTED"
	statePrivateLinkAttachmentConnectionUnknown      = "UNKNOWN"
	statePrivateLinkAttachmentConnectionUnexpected   = "UNEXPECTED"
)

func privateLinkAttachmentConnectionResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: privateLinkAttachmentConnectionCreate,
		ReadContext:   privateLinkAttachmentConnectionRead,
		UpdateContext: privateLinkAttachmentConnectionUpdate,
		DeleteContext: privateLinkAttachmentConnectionDelete,
		Importer: &schema.ResourceImporter{
			StateContext: privateLinkAttachmentConnectionImport,
		},
		Schema: map[string]*schema.Schema{
			paramDisplayName: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The name of the PrivateLink attachment connection.",
			},
			paramEnvironment:           environmentSchema(),
			paramPrivateLinkAttachment: privateLinkAttachmentSchema(),
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Private Link Attachment Connection.",
			},
			paramAws:   awsPrivateLinkAttachmentConnectionSchema(),
			paramAzure: azurePrivateLinkAttachmentConnectionSchema(),
			paramGcp:   gcpPrivateLinkAttachmentConnectionSchema(),
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(networkingAPICreateTimeout),
			Delete: schema.DefaultTimeout(networkingAPIDeleteTimeout),
		},
	}
}

func awsPrivateLinkAttachmentConnectionSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAwsVpcEndpointId: {
					Type:         schema.TypeString,
					Required:     true,
					ValidateFunc: validation.StringIsNotEmpty,
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPrivateLinkAttachmentConnectionCloudVariants,
	}
}

func azurePrivateLinkAttachmentConnectionSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAzurePrivateEndpointResourceId: {
					Type:         schema.TypeString,
					Required:     true,
					ValidateFunc: validation.StringIsNotEmpty,
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPrivateLinkAttachmentConnectionCloudVariants,
	}
}

func gcpPrivateLinkAttachmentConnectionSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramGcpPrivateServiceConnectConnectionId: {
					Type:         schema.TypeString,
					Required:     true,
					ValidateFunc: validation.StringIsNotEmpty,
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPrivateLinkAttachmentConnectionCloudVariants,
	}
}

func privateLinkAttachmentConnectionCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	spec := networkingprivatelinkv1.NewNetworkingV1PrivateLinkAttachmentConnectionSpec()

	// Set regular attributes
	spec.SetDisplayName(d.Get(paramDisplayName).(string))
	environmentRef := networkingprivatelinkv1.NewObjectReferenceWithDefaults()
	environmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	spec.SetEnvironment(*environmentRef)
	privateLinkAttachmentRef := networkingprivatelinkv1.NewObjectReferenceWithDefaults()
	privateLinkAttachmentRef.SetId(extractStringValueFromBlock(d, paramPrivateLinkAttachment, paramId))
	spec.SetPrivateLinkAttachment(*privateLinkAttachmentRef)
	// Detect which cloud variant is specified
	_, isAwsPrivateLinkAttachmentConnection := d.GetOk(paramAws)
	_, isAzurePrivateLinkAttachmentConnection := d.GetOk(paramAzure)
	_, isGcpPrivateLinkAttachmentConnection := d.GetOk(paramGcp)

	var cloudIdentifier string

	switch {
	case isAwsPrivateLinkAttachmentConnection:
		vpcEndpointId := extractStringValueFromBlock(d, paramAws, paramAwsVpcEndpointId)
		cloudIdentifier = vpcEndpointId
		cloudOneOf := networkingprivatelinkv1.NetworkingV1AwsPrivateLinkAttachmentConnectionAsNetworkingV1PrivateLinkAttachmentConnectionSpecCloudOneOf(networkingprivatelinkv1.NewNetworkingV1AwsPrivateLinkAttachmentConnection(kindAwsPrivateLinkAttachmentConnection, vpcEndpointId))
		spec.SetCloud(cloudOneOf)
	case isAzurePrivateLinkAttachmentConnection:
		privateEndpointResourceId := extractStringValueFromBlock(d, paramAzure, paramAzurePrivateEndpointResourceId)
		cloudIdentifier = privateEndpointResourceId
		cloudOneOf := networkingprivatelinkv1.NetworkingV1AzurePrivateLinkAttachmentConnectionAsNetworkingV1PrivateLinkAttachmentConnectionSpecCloudOneOf(networkingprivatelinkv1.NewNetworkingV1AzurePrivateLinkAttachmentConnection(kindAzurePrivateLinkAttachmentConnection, privateEndpointResourceId))
		spec.SetCloud(cloudOneOf)
	case isGcpPrivateLinkAttachmentConnection:
		privateServiceConnectConnectionId := extractStringValueFromBlock(d, paramGcp, paramGcpPrivateServiceConnectConnectionId)
		cloudIdentifier = privateServiceConnectConnectionId
		cloudOneOf := networkingprivatelinkv1.NetworkingV1GcpPrivateLinkAttachmentConnectionAsNetworkingV1PrivateLinkAttachmentConnectionSpecCloudOneOf(networkingprivatelinkv1.NewNetworkingV1GcpPrivateLinkAttachmentConnection(kindGcpPrivateLinkAttachmentConnection, privateServiceConnectConnectionId))
		spec.SetCloud(cloudOneOf)
	default:
		return diag.Errorf("error creating private link attachment connection: expected one of %s, %s, %s params", paramAws, paramAzure, paramGcp)
	}

	createPrivateLinkAttachmentConnectionRequest := &networkingprivatelinkv1.NetworkingV1PrivateLinkAttachmentConnection{Spec: spec}

	createPrivateLinkAttachmentConnectionRequestJson, err := json.Marshal(createPrivateLinkAttachmentConnectionRequest)
	if err != nil {
		return diag.Errorf("error creating private link attachment connection: error marshaling %#v to json: %s", createPrivateLinkAttachmentConnectionRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new private link attachment connection: %s", createPrivateLinkAttachmentConnectionRequestJson))

	createdPrivateLinkAttachmentConnection, resp, err := executePrivateLinkAttachmentConnectionCreate(ctx, c, *createPrivateLinkAttachmentConnectionRequest)
	if err != nil {
		return diag.Errorf("error creating private link attachment connection %q: %s", cloudIdentifier, createDescriptiveError(err, resp))
	}
	d.SetId(createdPrivateLinkAttachmentConnection.GetId())

	// Wait for async provisioning to complete
	createEnvironmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if err := waitForPrivateLinkAttachmentConnectionToProvision(c.networkingPrivatelinkV1ApiContext(ctx), c, createEnvironmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for private link attachment connection %q to provision: %s", d.Id(), createDescriptiveError(err))
	}

	createdPrivateLinkAttachmentConnectionJson, err := json.Marshal(createdPrivateLinkAttachmentConnection)
	if err != nil {
		return diag.Errorf("error creating private link attachment connection %q: error marshaling %#v to json: %s", d.Id(), createdPrivateLinkAttachmentConnection, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating private link attachment connection %q: %s", d.Id(), createdPrivateLinkAttachmentConnectionJson), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	return privateLinkAttachmentConnectionRead(ctx, d, meta)
}

func privateLinkAttachmentConnectionRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading private link attachment connection %q", d.Id()), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})
	if _, err := readPrivateLinkAttachmentConnectionAndSetAttributes(ctx, d, meta); err != nil {
		return diag.FromErr(fmt.Errorf("error reading private link attachment connection %q: %s", d.Id(), createDescriptiveError(err)))
	}
	return nil
}

func privateLinkAttachmentConnectionUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName) {
		return diag.Errorf("error updating private link attachment connection %q: only %q can be updated", d.Id(), paramDisplayName)
	}

	updatePrivateLinkAttachmentConnectionRequest := networkingprivatelinkv1.NewNetworkingV1PrivateLinkAttachmentConnectionUpdate()
	specUpdate := networkingprivatelinkv1.NewNetworkingV1PrivateLinkAttachmentConnectionSpecUpdate()
	if d.HasChange(paramDisplayName) {
		specUpdate.SetDisplayName(d.Get(paramDisplayName).(string))
	}

	// Environment is required in the update request body for resource identification
	updateEnvironmentRef := networkingprivatelinkv1.NewObjectReferenceWithDefaults()
	updateEnvironmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	specUpdate.SetEnvironment(*updateEnvironmentRef)

	updatePrivateLinkAttachmentConnectionRequest.SetSpec(*specUpdate)

	updatePrivateLinkAttachmentConnectionRequestJson, err := json.Marshal(updatePrivateLinkAttachmentConnectionRequest)
	if err != nil {
		return diag.Errorf("error updating private link attachment connection %q: error marshaling %#v to json: %s", d.Id(), updatePrivateLinkAttachmentConnectionRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating private link attachment connection %q: %s", d.Id(), updatePrivateLinkAttachmentConnectionRequestJson), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedPrivateLinkAttachmentConnection, resp, err := c.networkingPrivatelinkV1Client.PrivateLinkAttachmentConnectionsNetworkingV1Api.UpdateNetworkingV1PrivateLinkAttachmentConnection(c.networkingPrivatelinkV1ApiContext(ctx), d.Id()).NetworkingV1PrivateLinkAttachmentConnectionUpdate(*updatePrivateLinkAttachmentConnectionRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating private link attachment connection %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedPrivateLinkAttachmentConnectionJson, err := json.Marshal(updatedPrivateLinkAttachmentConnection)
	if err != nil {
		return diag.Errorf("error updating private link attachment connection %q: error marshaling %#v to json: %s", d.Id(), updatedPrivateLinkAttachmentConnection, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating private link attachment connection %q: %s", d.Id(), updatedPrivateLinkAttachmentConnectionJson), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	return privateLinkAttachmentConnectionRead(ctx, d, meta)
}

func privateLinkAttachmentConnectionDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting private link attachment connection %q", d.Id()), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	req := c.networkingPrivatelinkV1Client.PrivateLinkAttachmentConnectionsNetworkingV1Api.DeleteNetworkingV1PrivateLinkAttachmentConnection(c.networkingPrivatelinkV1ApiContext(ctx), d.Id()).Environment(environmentId)
	resp, err := req.Execute()
	if err != nil {
		return diag.Errorf("error deleting private link attachment connection %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	// Wait for async deletion to complete
	if err := waitForPrivateLinkAttachmentConnectionToBeDeleted(c.networkingPrivatelinkV1ApiContext(ctx), c, environmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for private link attachment connection %q to be deleted: %s", d.Id(), createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting private link attachment connection %q", d.Id()), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	return nil
}

func executePrivateLinkAttachmentConnectionCreate(ctx context.Context, c *Client, privateLinkAttachmentConnection networkingprivatelinkv1.NetworkingV1PrivateLinkAttachmentConnection) (networkingprivatelinkv1.NetworkingV1PrivateLinkAttachmentConnection, *http.Response, error) {
	req := c.networkingPrivatelinkV1Client.PrivateLinkAttachmentConnectionsNetworkingV1Api.CreateNetworkingV1PrivateLinkAttachmentConnection(c.networkingPrivatelinkV1ApiContext(ctx)).NetworkingV1PrivateLinkAttachmentConnection(privateLinkAttachmentConnection)
	return req.Execute()
}
func executePrivateLinkAttachmentConnectionRead(ctx context.Context, c *Client, environmentId string, id string) (networkingprivatelinkv1.NetworkingV1PrivateLinkAttachmentConnection, *http.Response, error) {
	req := c.networkingPrivatelinkV1Client.PrivateLinkAttachmentConnectionsNetworkingV1Api.GetNetworkingV1PrivateLinkAttachmentConnection(c.networkingPrivatelinkV1ApiContext(ctx), id).Environment(environmentId)
	return req.Execute()
}

func readPrivateLinkAttachmentConnectionAndSetAttributes(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	privateLinkAttachmentConnection, resp, err := executePrivateLinkAttachmentConnectionRead(ctx, c, environmentId, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading private link attachment connection %q: %s", d.Id(), readErr), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing private link attachment connection %q in TF state because private link attachment connection could not be found on the server", d.Id()), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})
			d.SetId("")
			return nil, nil
		}
		return nil, fmt.Errorf("error reading private link attachment connection %q: %s", d.Id(), readErr)
	}

	privateLinkAttachmentConnectionJson, err := json.Marshal(privateLinkAttachmentConnection)
	if err != nil {
		return nil, fmt.Errorf("error reading private link attachment connection %q: error marshaling %#v to json: %s", privateLinkAttachmentConnection.GetId(), privateLinkAttachmentConnection, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched private link attachment connection %q: %s", d.Id(), privateLinkAttachmentConnectionJson), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	if _, err := setPrivateLinkAttachmentConnectionAttributes(d, privateLinkAttachmentConnection); err != nil {
		// No resp: a d.Set failure is not an API error, and resp.Body is already consumed.
		return nil, fmt.Errorf("error setting private link attachment connection attributes %q: %s", d.Id(), createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished reading private link attachment connection %q", d.Id()), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	return []*schema.ResourceData{d}, nil
}

func setPrivateLinkAttachmentConnectionAttributes(d *schema.ResourceData, privateLinkAttachmentConnection networkingprivatelinkv1.NetworkingV1PrivateLinkAttachmentConnection) (*schema.ResourceData, error) {
	spec := privateLinkAttachmentConnection.GetSpec()
	if err := d.Set(paramDisplayName, spec.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	environmentRef := spec.GetEnvironment()
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	privateLinkAttachmentRef := spec.GetPrivateLinkAttachment()
	if err := d.Set(paramPrivateLinkAttachment, []interface{}{map[string]interface{}{
		paramId: privateLinkAttachmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceName, privateLinkAttachmentConnection.Metadata.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	oneOfCloud := spec.GetCloud()
	status := privateLinkAttachmentConnection.GetStatus()
	statusOneOfCloud := status.GetCloud()

	switch {
	case oneOfCloud.NetworkingV1AwsPrivateLinkAttachmentConnection != nil && statusOneOfCloud.NetworkingV1AwsPrivateLinkAttachmentConnectionStatus != nil:
		if err := d.Set(paramAws, []interface{}{map[string]interface{}{
			paramAwsVpcEndpointId: oneOfCloud.NetworkingV1AwsPrivateLinkAttachmentConnection.GetVpcEndpointId(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1AzurePrivateLinkAttachmentConnection != nil && statusOneOfCloud.NetworkingV1AzurePrivateLinkAttachmentConnectionStatus != nil:
		if err := d.Set(paramAzure, []interface{}{map[string]interface{}{
			paramAzurePrivateEndpointResourceId: oneOfCloud.NetworkingV1AzurePrivateLinkAttachmentConnection.GetPrivateEndpointResourceId(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1GcpPrivateLinkAttachmentConnection != nil && statusOneOfCloud.NetworkingV1GcpPrivateLinkAttachmentConnectionStatus != nil:
		if err := d.Set(paramGcp, []interface{}{map[string]interface{}{
			paramGcpPrivateServiceConnectConnectionId: oneOfCloud.NetworkingV1GcpPrivateLinkAttachmentConnection.GetPrivateServiceConnectConnectionId(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	}

	d.SetId(privateLinkAttachmentConnection.GetId())
	return d, nil
}

func privateLinkAttachmentConnectionImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing private link attachment connection %q", d.Id()), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})

	envIDAndResourceId := d.Id()
	parts := strings.Split(envIDAndResourceId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing private link attachment connection: invalid format: expected '<environment ID>/<private link attachment connection ID>'")
	}
	environmentId := parts[0]
	resourceId := parts[1]
	d.SetId(resourceId)
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if _, err := readPrivateLinkAttachmentConnectionAndSetAttributes(ctx, d, meta); err != nil {
		return nil, fmt.Errorf("error importing private link attachment connection %q: %s", d.Id(), err)
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished importing private link attachment connection %q", d.Id()), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}

// privateLinkAttachmentConnectionProvisionStatus returns a StateRefreshFunc for polling the resource status
func privateLinkAttachmentConnectionProvisionStatus(ctx context.Context, c *Client, environmentId string, privateLinkAttachmentConnectionId string) resource.StateRefreshFunc {
	return func() (result interface{}, s string, err error) {
		privateLinkAttachmentConnection, resp, err := executePrivateLinkAttachmentConnectionRead(ctx, c, environmentId, privateLinkAttachmentConnectionId)
		if err != nil {
			tflog.Warn(ctx, fmt.Sprintf("Error reading private link attachment connection %q: %s", privateLinkAttachmentConnectionId, createDescriptiveError(err, resp)), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: privateLinkAttachmentConnectionId})
			return nil, statePrivateLinkAttachmentConnectionUnknown, err
		}

		currentPhase := privateLinkAttachmentConnection.Status.GetPhase()
		tflog.Debug(ctx, fmt.Sprintf("Waiting for private link attachment connection %q provisioning status to become one of %v: current status is %q", privateLinkAttachmentConnectionId, []string{statePrivateLinkAttachmentConnectionReady}, currentPhase), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: privateLinkAttachmentConnectionId})

		// Check for pending states (still provisioning)
		switch currentPhase {
		case statePrivateLinkAttachmentConnectionProvisioning:
			return privateLinkAttachmentConnection, currentPhase, nil
		}

		// Check for target states (provisioning complete)
		switch currentPhase {
		case statePrivateLinkAttachmentConnectionReady:
			return privateLinkAttachmentConnection, currentPhase, nil
		}

		// Check for failed states
		switch currentPhase {
		case statePrivateLinkAttachmentConnectionFailed:
			errorMsg := privateLinkAttachmentConnection.Status.GetErrorMessage()
			if errorMsg == "" {
				statusBytes, marshalErr := json.Marshal(privateLinkAttachmentConnection.Status)
				if marshalErr == nil && len(statusBytes) > 0 {
					errorMsg = fmt.Sprintf("no error_message provided by the API; status: %s", statusBytes)
				} else {
					errorMsg = "no error_message provided by the API"
				}
			}
			return nil, statePrivateLinkAttachmentConnectionFailed, fmt.Errorf("private link attachment connection %q provisioning status is %q: %s", privateLinkAttachmentConnectionId, statePrivateLinkAttachmentConnectionFailed, errorMsg)
		case statePrivateLinkAttachmentConnectionDisconnected:
			errorMsg := privateLinkAttachmentConnection.Status.GetErrorMessage()
			if errorMsg == "" {
				statusBytes, marshalErr := json.Marshal(privateLinkAttachmentConnection.Status)
				if marshalErr == nil && len(statusBytes) > 0 {
					errorMsg = fmt.Sprintf("no error_message provided by the API; status: %s", statusBytes)
				} else {
					errorMsg = "no error_message provided by the API"
				}
			}
			return nil, statePrivateLinkAttachmentConnectionDisconnected, fmt.Errorf("private link attachment connection %q provisioning status is %q: %s", privateLinkAttachmentConnectionId, statePrivateLinkAttachmentConnectionDisconnected, errorMsg)
		}

		// Unexpected state
		return nil, statePrivateLinkAttachmentConnectionUnexpected, fmt.Errorf("private link attachment connection %q is in an unexpected state %q", privateLinkAttachmentConnectionId, currentPhase)
	}
}

// waitForPrivateLinkAttachmentConnectionToProvision waits for the resource to reach a ready state
func waitForPrivateLinkAttachmentConnectionToProvision(ctx context.Context, c *Client, environmentId string, privateLinkAttachmentConnectionId string) error {
	delay, pollInterval := getDelayAndPollInterval(5*time.Second, 1*time.Minute, c.isAcceptanceTestMode)
	stateConf := &resource.StateChangeConf{
		Pending:      []string{statePrivateLinkAttachmentConnectionProvisioning},
		Target:       []string{statePrivateLinkAttachmentConnectionReady},
		Refresh:      privateLinkAttachmentConnectionProvisionStatus(ctx, c, environmentId, privateLinkAttachmentConnectionId),
		Timeout:      networkingAPICreateTimeout,
		Delay:        delay,
		PollInterval: pollInterval,
	}

	tflog.Debug(ctx, fmt.Sprintf("Waiting for private link attachment connection %q provisioning status to become one of %v", privateLinkAttachmentConnectionId, []string{statePrivateLinkAttachmentConnectionReady}), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: privateLinkAttachmentConnectionId})
	if _, err := stateConf.WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}

// privateLinkAttachmentConnectionDeleteStatus returns a StateRefreshFunc for polling the delete status
func privateLinkAttachmentConnectionDeleteStatus(ctx context.Context, c *Client, environmentId string, privateLinkAttachmentConnectionId string) resource.StateRefreshFunc {
	return func() (result interface{}, s string, err error) {
		privateLinkAttachmentConnection, resp, err := executePrivateLinkAttachmentConnectionRead(ctx, c, environmentId, privateLinkAttachmentConnectionId)
		if err != nil {
			if isNonKafkaRestApiResourceNotFound(resp) {
				// Resource is deleted
				return privateLinkAttachmentConnection, "DELETED", nil
			}
			tflog.Warn(ctx, fmt.Sprintf("Error reading private link attachment connection %q: %s", privateLinkAttachmentConnectionId, createDescriptiveError(err, resp)), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: privateLinkAttachmentConnectionId})
			return nil, statePrivateLinkAttachmentConnectionUnknown, err
		}

		// Resource still exists
		return privateLinkAttachmentConnection, "DELETING", nil
	}
}

// waitForPrivateLinkAttachmentConnectionToBeDeleted waits for the resource to be fully deleted
func waitForPrivateLinkAttachmentConnectionToBeDeleted(ctx context.Context, c *Client, environmentId string, privateLinkAttachmentConnectionId string) error {
	delay, pollInterval := getDelayAndPollInterval(5*time.Second, 1*time.Minute, c.isAcceptanceTestMode)
	stateConf := &resource.StateChangeConf{
		Pending:      []string{"DELETING"},
		Target:       []string{"DELETED"},
		Refresh:      privateLinkAttachmentConnectionDeleteStatus(ctx, c, environmentId, privateLinkAttachmentConnectionId),
		Timeout:      networkingAPIDeleteTimeout,
		Delay:        delay,
		PollInterval: pollInterval,
	}

	tflog.Debug(ctx, fmt.Sprintf("Waiting for private link attachment connection %q to be deleted", privateLinkAttachmentConnectionId), map[string]interface{}{privateLinkAttachmentConnectionLoggingKey: privateLinkAttachmentConnectionId})
	if _, err := stateConf.WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}
func privateLinkAttachmentSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramId: {
					Type:        schema.TypeString,
					Required:    true,
					ForceNew:    true,
					Description: "The unique identifier for the private link attachment.",
				},
			},
		},
		Required:    true,
		MinItems:    1,
		MaxItems:    1,
		ForceNew:    true,
		Description: "The private_link_attachment to which this belongs.",
	}
}
