// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2/notifications/v1"
)

const subscriptionLoggingKey = "subscription_id"

func subscriptionResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: subscriptionCreate,
		ReadContext:   subscriptionRead,
		UpdateContext: subscriptionUpdate,
		DeleteContext: subscriptionDelete,
		Importer: &schema.ResourceImporter{
			StateContext: subscriptionImport,
		},
		Schema: map[string]*schema.Schema{
			paramCurrentState: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"ENABLED", "DISABLED"}, false),
				Description:  "Denotes the state of the subscription. When the subscription is ENABLED, the user will receive notification on the configured integrations. If the subscription is DISABLED, the user will not receive any notification for the configured notification type. Note that, you cannot disable a subscription for `REQUIRED` notification type.",
			},
			paramNotificationType: notificationTypeSchema(),
			paramIntegrations: {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				MinItems:    1,
				Required:    true,
				Description: "Integrations to which notifications are to be sent.",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Subscription.",
			},
		},
	}
}

func subscriptionCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	createSubscriptionRequest := notificationsv1.NewNotificationsV1Subscription()

	// Set required attributes
	notificationTypeRef := notificationsv1.NewGlobalObjectReferenceWithDefaults()
	notificationTypeRef.SetId(extractStringValueFromBlock(d, paramNotificationType, paramId))
	createSubscriptionRequest.SetNotificationType(*notificationTypeRef)
	integrationsIds := convertToStringSlice(d.Get(paramIntegrations).(*schema.Set).List())
	integrationsRefs := make([]notificationsv1.GlobalObjectReference, len(integrationsIds))
	for i, id := range integrationsIds {
		integrationsRefs[i] = notificationsv1.GlobalObjectReference{Id: id}
	}
	createSubscriptionRequest.SetIntegrations(integrationsRefs)

	// Set optional attributes
	if _, ok := d.GetOk(paramCurrentState); ok {
		createSubscriptionRequest.SetCurrentState(d.Get(paramCurrentState).(string))
	}

	// Logging
	createSubscriptionRequestJson, err := json.Marshal(createSubscriptionRequest)
	if err != nil {
		return diag.Errorf("error creating subscription: error marshaling %#v to json: %s", createSubscriptionRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new subscription: %s", createSubscriptionRequestJson))

	// Make API call
	createdSubscription, resp, err := executeSubscriptionCreate(c.notificationsV1ApiContext(ctx), c, createSubscriptionRequest)
	if err != nil {
		return diag.Errorf("error creating subscription: %s", createDescriptiveError(err, resp))
	}

	d.SetId(createdSubscription.GetId())

	// Logging
	createdSubscriptionJson, err := json.Marshal(createdSubscription)
	if err != nil {
		return diag.Errorf("error creating subscription %q: error marshaling %#v to json: %s", d.Id(), createdSubscription, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating subscription %q: %s", d.Id(), createdSubscriptionJson), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	return subscriptionRead(ctx, d, meta)
}

func executeSubscriptionCreate(ctx context.Context, c *Client, subscription *notificationsv1.NotificationsV1Subscription) (notificationsv1.NotificationsV1Subscription, *http.Response, error) {
	req := c.notificationsV1Client.SubscriptionsNotificationsV1Api.CreateNotificationsV1Subscription(c.notificationsV1ApiContext(ctx)).NotificationsV1Subscription(*subscription)
	return req.Execute()
}

func subscriptionRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading subscription %q", d.Id()), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	c := meta.(*Client)
	subscription, resp, err := executeSubscriptionRead(c.notificationsV1ApiContext(ctx), c, d.Id())
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Error reading subscription %q: %s", d.Id(), createDescriptiveError(err, resp)), map[string]interface{}{subscriptionLoggingKey: d.Id()})

		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing subscription %q in TF state because subscription could not be found on the server", d.Id()), map[string]interface{}{subscriptionLoggingKey: d.Id()})
			d.SetId("")
			return nil
		}

		return diag.FromErr(createDescriptiveError(err, resp))
	}

	subscriptionJson, err := json.Marshal(subscription)
	if err != nil {
		return diag.Errorf("error reading subscription %q: error marshaling %#v to json: %s", d.Id(), subscription, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched subscription %q: %s", d.Id(), subscriptionJson), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	if _, err := setSubscriptionAttributes(d, subscription); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished reading subscription %q", d.Id()), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	return nil
}

func executeSubscriptionRead(ctx context.Context, c *Client, subscriptionId string) (notificationsv1.NotificationsV1Subscription, *http.Response, error) {
	req := c.notificationsV1Client.SubscriptionsNotificationsV1Api.GetNotificationsV1Subscription(c.notificationsV1ApiContext(ctx), subscriptionId)
	return req.Execute()
}

func setSubscriptionAttributes(d *schema.ResourceData, subscription notificationsv1.NotificationsV1Subscription) (*schema.ResourceData, error) {
	if err := d.Set(paramCurrentState, subscription.GetCurrentState()); err != nil {
		return nil, createDescriptiveError(err)
	}
	notificationTypeRef := subscription.GetNotificationType()
	if err := d.Set(paramNotificationType, []interface{}{map[string]interface{}{
		paramId: notificationTypeRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	integrationsRefs := subscription.GetIntegrations()
	integrationsIds := make([]string, len(integrationsRefs))
	for i, ref := range integrationsRefs {
		integrationsIds[i] = ref.GetId()
	}
	if err := d.Set(paramIntegrations, integrationsIds); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramApiVersion, subscription.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, subscription.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceName, subscription.Metadata.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(subscription.GetId())
	return d, nil
}

func subscriptionUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramCurrentState, paramIntegrations) {
		return diag.Errorf("error updating subscription %q: only %q, %q can be updated", d.Id(), paramCurrentState, paramIntegrations)
	}

	updateSubscriptionRequest := notificationsv1.NewNotificationsV1SubscriptionUpdate()
	if d.HasChange(paramCurrentState) {
		updateSubscriptionRequest.SetCurrentState(d.Get(paramCurrentState).(string))
	}
	if d.HasChange(paramIntegrations) {
		integrationsIds := convertToStringSlice(d.Get(paramIntegrations).(*schema.Set).List())
		integrationsRefs := make([]notificationsv1.GlobalObjectReference, len(integrationsIds))
		for i, id := range integrationsIds {
			integrationsRefs[i] = notificationsv1.GlobalObjectReference{Id: id}
		}
		updateSubscriptionRequest.SetIntegrations(integrationsRefs)
	}

	updateSubscriptionRequestJson, err := json.Marshal(updateSubscriptionRequest)
	if err != nil {
		return diag.Errorf("error updating subscription %q: error marshaling %#v to json: %s", d.Id(), updateSubscriptionRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating subscription %q: %s", d.Id(), updateSubscriptionRequestJson), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedSubscription, resp, err := c.notificationsV1Client.SubscriptionsNotificationsV1Api.UpdateNotificationsV1Subscription(c.notificationsV1ApiContext(ctx), d.Id()).NotificationsV1SubscriptionUpdate(*updateSubscriptionRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating subscription %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedSubscriptionJson, err := json.Marshal(updatedSubscription)
	if err != nil {
		return diag.Errorf("error updating subscription %q: error marshaling %#v to json: %s", d.Id(), updatedSubscription, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating subscription %q: %s", d.Id(), updatedSubscriptionJson), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	return subscriptionRead(ctx, d, meta)
}

func subscriptionDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting subscription %q", d.Id()), map[string]interface{}{subscriptionLoggingKey: d.Id()})
	c := meta.(*Client)
	req := c.notificationsV1Client.SubscriptionsNotificationsV1Api.DeleteNotificationsV1Subscription(c.notificationsV1ApiContext(ctx), d.Id())
	resp, err := req.Execute()

	if err != nil {
		return diag.Errorf("error deleting subscription %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting subscription %q", d.Id()), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	return nil
}

func subscriptionImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing subscription %q", d.Id()), map[string]interface{}{subscriptionLoggingKey: d.Id()})

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if diagnostics := subscriptionRead(ctx, d, meta); len(diagnostics) > 0 {
		return nil, fmt.Errorf("error importing subscription %q: %s", d.Id(), diagnostics[0].Summary)
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished importing subscription %q", d.Id()), map[string]interface{}{subscriptionLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
