// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/walkerus/go-wiremock"
)

const (
	scenarioStateSwitchoverPairHasBeenCreated = "The new switchover_pair has been just created"
	scenarioStateSwitchoverPairHasBeenUpdated = "The switchover_pair has been just updated"
	scenarioStateSwitchoverPairHasBeenDeleted = "The switchover_pair has been deleted"
	switchover_pairScenarioName               = "confluent_switchover_pair Resource Lifecycle"
	switchover_pairId                         = "switchover_pair-abc123"
)

func TestAccSwitchoverSwitchoverPair(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	createSwitchoverPairResponse, _ := ioutil.ReadFile("../testdata/switchover_pair/create_switchover_pair.json")
	createSwitchoverPairStub := wiremock.Post(wiremock.URLPathEqualTo("/switchover/v1/switchover-pairs")).
		InScenario(switchover_pairScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillSetStateTo(scenarioStateSwitchoverPairHasBeenCreated).
		WillReturn(
			string(createSwitchoverPairResponse),
			contentTypeJSONHeader,
			http.StatusAccepted,
		)
	_ = wiremockClient.StubFor(createSwitchoverPairStub)

	readCreatedSwitchoverPairResponse, _ := ioutil.ReadFile("../testdata/switchover_pair/read_created_switchover_pair.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/switchover/v1/switchover-pairs/%s", switchover_pairId))).
		InScenario(switchover_pairScenarioName).
		WhenScenarioStateIs(scenarioStateSwitchoverPairHasBeenCreated).
		WillReturn(
			string(readCreatedSwitchoverPairResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))

	readUpdatedSwitchoverPairResponse, _ := ioutil.ReadFile("../testdata/switchover_pair/read_updated_switchover_pair.json")
	patchSwitchoverPairStub := wiremock.Patch(wiremock.URLPathEqualTo(fmt.Sprintf("/switchover/v1/switchover-pairs/%s", switchover_pairId))).
		InScenario(switchover_pairScenarioName).
		WhenScenarioStateIs(scenarioStateSwitchoverPairHasBeenCreated).
		WillSetStateTo(scenarioStateSwitchoverPairHasBeenUpdated).
		WillReturn(
			string(readUpdatedSwitchoverPairResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		)
	_ = wiremockClient.StubFor(patchSwitchoverPairStub)

	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/switchover/v1/switchover-pairs/%s", switchover_pairId))).
		InScenario(switchover_pairScenarioName).
		WhenScenarioStateIs(scenarioStateSwitchoverPairHasBeenUpdated).
		WillReturn(
			string(readUpdatedSwitchoverPairResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))

	readDeletedSwitchoverPairResponse, _ := ioutil.ReadFile("../testdata/switchover_pair/read_deleted_switchover_pair.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/switchover/v1/switchover-pairs/%s", switchover_pairId))).
		InScenario(switchover_pairScenarioName).
		WhenScenarioStateIs(scenarioStateSwitchoverPairHasBeenDeleted).
		WillReturn(
			string(readDeletedSwitchoverPairResponse),
			contentTypeJSONHeader,
			http.StatusForbidden,
		))

	deleteSwitchoverPairStub := wiremock.Delete(wiremock.URLPathEqualTo(fmt.Sprintf("/switchover/v1/switchover-pairs/%s", switchover_pairId))).
		InScenario(switchover_pairScenarioName).
		WhenScenarioStateIs(scenarioStateSwitchoverPairHasBeenUpdated).
		WillSetStateTo(scenarioStateSwitchoverPairHasBeenDeleted).
		WillReturn(
			"",
			contentTypeJSONHeader,
			http.StatusNoContent,
		)
	_ = wiremockClient.StubFor(deleteSwitchoverPairStub)
	activeMember := "west"
	displayName := "prod-kafka-dr"
	environment := "env-00000"
	members := ""
	// in order to test tf update (step #3)
	displayNameUpdated := "prod-kafka-dr_updated"
	switchover_pairResourceLabel := "test_switchover_pair_resource_label"
	fullSwitchoverPairResourceLabel := fmt.Sprintf("confluent_switchover_pair.%s", switchover_pairResourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckSwitchoverSwitchoverPairDestroy,
		// https://www.terraform.io/docs/extend/testing/acceptance-tests/teststep.html
		// https://www.terraform.io/docs/extend/best-practices/testing.html#built-in-patterns
		Steps: []resource.TestStep{
			{
				Config: testAccCheckSwitchoverSwitchoverPairConfig(mockServerUrl, switchover_pairResourceLabel, activeMember, displayName, environment, members),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckSwitchoverSwitchoverPairExists(fullSwitchoverPairResourceLabel),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "id", switchover_pairId),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "active_member", activeMember),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "display_name", displayName),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "environment.0.id", environment),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "members", members),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "api_version", "switchover/v1"),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "kind", "SwitchoverPair"),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/switchover-pair=sw-12345"),
				),
			},
			{
				// https://www.terraform.io/docs/extend/resources/import.html
				ResourceName:      fullSwitchoverPairResourceLabel,
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccCheckSwitchoverSwitchoverPairConfig(mockServerUrl, switchover_pairResourceLabel, activeMember, displayNameUpdated, environment, members),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckSwitchoverSwitchoverPairExists(fullSwitchoverPairResourceLabel),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "id", switchover_pairId),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "active_member", activeMember),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "display_name", displayNameUpdated),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "environment.0.id", environment),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "members", members),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "api_version", "switchover/v1"),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "kind", "SwitchoverPair"),
					resource.TestCheckResourceAttr(fullSwitchoverPairResourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/switchover-pair=sw-12345"),
				),
			},
			{
				ResourceName:      fullSwitchoverPairResourceLabel,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})

	checkStubCount(t, wiremockClient, createSwitchoverPairStub, "POST /switchover/v1/switchover-pairs", expectedCountOne)
	checkStubCount(t, wiremockClient, patchSwitchoverPairStub, fmt.Sprintf("PATCH /switchover/v1/switchover-pairs/%s", switchover_pairId), expectedCountOne)
	checkStubCount(t, wiremockClient, deleteSwitchoverPairStub, fmt.Sprintf("DELETE /switchover/v1/switchover-pairs/%s", switchover_pairId), expectedCountOne)
}

func testAccCheckSwitchoverSwitchoverPairDestroy(s *terraform.State) error {
	c := testAccProvider.Meta().(*Client)
	// Loop through the resources in state, verifying each switchover_pair is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "confluent_switchover_pair" {
			continue
		}
		deletedSwitchoverPairId := rs.Primary.ID
		req := c.switchoverV1Client.SwitchoverPairsSwitchoverV1Api.GetSwitchoverV1SwitchoverPair(c.switchoverV1ApiContext(context.Background()), deletedSwitchoverPairId).Environment(rs.Primary.Attributes[paramEnvironment+".0.id"])
		deletedSwitchoverPair, response, err := req.Execute()
		if response != nil && (response.StatusCode == http.StatusForbidden || response.StatusCode == http.StatusNotFound) {
			// If the error is equivalent to http.StatusNotFound, the switchover_pair is destroyed.
			return nil
		} else if err == nil && deletedSwitchoverPair.Id != nil {
			// Otherwise return the error
			if *deletedSwitchoverPair.Id == rs.Primary.ID {
				return fmt.Errorf("switchover_pair (%q) still exists", rs.Primary.ID)
			}
		}
		return err
	}
	return nil
}

func testAccCheckSwitchoverSwitchoverPairConfig(mockServerUrl, switchover_pairResourceLabel string, activeMember string, displayName string, environment string, members string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	resource "confluent_switchover_pair" "%s" {
		active_member = "%s"
		display_name = "%s"
		environment {
			id = "%s"
		}
		members = "%s"
	}
	`, mockServerUrl, switchover_pairResourceLabel, activeMember, displayName, environment, members)
}

func testAccCheckSwitchoverSwitchoverPairExists(n string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[n]

		if !ok {
			return fmt.Errorf("%s switchover_pair has not been found", n)
		}

		if rs.Primary.ID == "" {
			return fmt.Errorf("ID has not been set for %s switchover_pair", n)
		}

		return nil
	}
}
