// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.19.3; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	networkingv1 "github.com/confluentinc/ccloud-sdk-go-v2/networking/v1"
)

// State constants for async provisioning
const (
	stateNetworkProvisioning = "PROVISIONING"
	stateNetworkReady        = "READY"
	stateNetworkFailed       = "FAILED"
	stateNetworkUnknown      = "UNKNOWN"
	stateNetworkUnexpected   = "UNEXPECTED"
)

func networkResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: networkCreate,
		ReadContext:   networkRead,
		UpdateContext: networkUpdate,
		DeleteContext: networkDelete,
		Importer: &schema.ResourceImporter{
			StateContext: networkImport,
		},
		CustomizeDiff: networkResourceCustomizeDiff,
		Schema: map[string]*schema.Schema{
			paramCidr: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringMatch(regexp.MustCompile(`^\d+\.\d+\.\d+\.\d+/16$`), "The IPv4 CIDR block must be /16."),
				Description:  "The IPv4 [CIDR block](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) to used for this network. Must be `/16`. Required for VPC peering and AWS TransitGateway.",
			},
			paramCloud: {
				Type:         schema.TypeString,
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringInSlice([]string{"AWS", "GCP", "AZURE"}, false),
				Description:  "The cloud service provider in which the network exists.",
			},
			paramConnectionTypes: {
				Type:        schema.TypeList,
				Elem:        &schema.Schema{Type: schema.TypeString},
				MinItems:    1,
				Required:    true,
				ForceNew:    true,
				Description: "The connection types requested for use with the network.",
			},
			paramDisplayName: {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The name of the network",
			},
			paramDnsConfig:   dnsConfigSchema(),
			paramEnvironment: environmentSchema(),
			paramGateway:     computedGatewaySchema(),
			paramRegion: {
				Type:         schema.TypeString,
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringIsNotEmpty,
				Description:  "The cloud service provider region in which the network exists.",
			},
			paramReservedCidr: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringMatch(regexp.MustCompile(`^\d+\.\d+\.\d+\.\d+/24$`), "The IPv4 CIDR block must be /24."),
				Description:  "The reserved CIDR config is used only by AWS networks with connection_types = Vpc_Peering or Transit_Gateway An IPv4 [CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) reserved for Confluent Cloud Network. Must be \\24. If not specified, Confluent Cloud Network uses 172.20.255.0/24 Note - The attribute is in a [Limited Availability lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)",
			},
			paramZones: {
				Type:        schema.TypeList,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Description: "The 3 availability zones for this network. They can optionally be specified for AWS networks used with PrivateLink, for GCP networks used with Private Service Connect, and for AWS and GCP networks used with Peering. Otherwise, they are automatically chosen by Confluent Cloud. On AWS, zones are AWS [AZ IDs](https://docs.aws.amazon.com/ram/latest/userguide/working-with-az-ids.html) (e.g. use1-az3) On GCP, zones are GCP [zones](https://cloud.google.com/compute/docs/regions-zones) (e.g. us-central1-c). On Azure, zones are Confluent-chosen names (e.g. 1, 2, 3) since Azure does not have universal zone identifiers.",
			},
			paramZoneInfo: zonesInfoSchema(),
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Network.",
			},
			paramDnsDomain: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The root DNS domain for the network if applicable. Present on networks that support PrivateLink.",
			},
			paramEndpointSuffix: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The endpoint suffix for the network, if applicable. Full service endpoints can be constructed by appending the service identifier to the beginning of the endpoint suffix. For example, the Flink REST endpoint can be constructed by adding \"flink\" - 'https://flink' + 'endpoint_suffix'.",
			},
			paramZonalSubdomains: {
				Type:        schema.TypeMap,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Computed:    true,
				Description: "The DNS subdomain for each zone. Present on networks that support PrivateLink. Keys are zones and values are DNS domains.",
			},
			paramAws:   awsNetworkSchema(),
			paramGcp:   gcpNetworkSchema(),
			paramAzure: azureNetworkSchema(),
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(networkingAPICreateTimeout),
			Delete: schema.DefaultTimeout(networkingAPIDeleteTimeout),
		},
	}
}

func awsNetworkSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAccount: {
					Type:     schema.TypeString,
					Computed: true,
				},
				paramPrivateLinkEndpointService: {
					Type:     schema.TypeString,
					Computed: true,
				},
				paramVpc: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func gcpNetworkSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramPrivateServiceConnectServiceAttachments: {
					Type: schema.TypeMap,
					Elem: &schema.Schema{
						Type: schema.TypeString,
					},
					Computed: true,
				},
				paramProject: {
					Type:     schema.TypeString,
					Computed: true,
				},
				paramVpcNetwork: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func azureNetworkSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramPrivateLinkServiceAliases: {
					Type: schema.TypeMap,
					Elem: &schema.Schema{
						Type: schema.TypeString,
					},
					Computed: true,
				},
				paramAzurePrivateLinkServiceResourceIds: {
					Type: schema.TypeMap,
					Elem: &schema.Schema{
						Type: schema.TypeString,
					},
					Computed: true,
				},
				paramSubscription: {
					Type:     schema.TypeString,
					Computed: true,
				},
				paramVnet: {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
		Computed: true,
	}
}

func networkCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	spec := networkingv1.NewNetworkingV1NetworkSpec()

	// Set regular attributes
	spec.SetCloud(d.Get(paramCloud).(string))
	spec.SetConnectionTypes(convertToStringSlice(d.Get(paramConnectionTypes).([]interface{})))
	environmentRef := networkingv1.NewObjectReferenceWithDefaults()
	environmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	spec.SetEnvironment(*environmentRef)
	spec.SetRegion(d.Get(paramRegion).(string))
	if _, ok := d.GetOk(paramCidr); ok {
		spec.SetCidr(d.Get(paramCidr).(string))
	}
	if _, ok := d.GetOk(paramDisplayName); ok {
		spec.SetDisplayName(d.Get(paramDisplayName).(string))
	}
	if _, ok := d.GetOk(paramDnsConfig); ok {
		dnsConfigBlock := d.Get(paramDnsConfig).([]interface{})[0].(map[string]interface{})
		dnsConfigObj := networkingv1.NewNetworkingV1DnsConfigWithDefaults()
		dnsConfigObj.SetResolution(dnsConfigBlock[paramResolution].(string))
		spec.SetDnsConfig(*dnsConfigObj)
	}
	if _, ok := d.GetOk(paramReservedCidr); ok {
		spec.SetReservedCidr(d.Get(paramReservedCidr).(string))
	}
	if _, ok := d.GetOk(paramZones); ok {
		spec.SetZones(convertToStringSlice(d.Get(paramZones).([]interface{})))
	}
	if _, ok := d.GetOk(paramZoneInfo); ok {
		zonesInfoList := d.Get(paramZoneInfo).([]interface{})
		zonesInfoObjs := make([]networkingv1.NetworkingV1ZoneInfo, 0, len(zonesInfoList))
		for _, zonesInfoItem := range zonesInfoList {
			zonesInfoBlock := zonesInfoItem.(map[string]interface{})
			zonesInfoObj := networkingv1.NewNetworkingV1ZoneInfoWithDefaults()
			zonesInfoObj.SetZoneId(zonesInfoBlock[paramZoneId].(string))
			zonesInfoObj.SetCidr(zonesInfoBlock[paramCidr].(string))
			zonesInfoObjs = append(zonesInfoObjs, *zonesInfoObj)
		}
		spec.SetZonesInfo(zonesInfoObjs)
	}

	createNetworkRequest := &networkingv1.NetworkingV1Network{Spec: spec}

	createNetworkRequestJson, err := json.Marshal(createNetworkRequest)
	if err != nil {
		return diag.Errorf("error creating network: error marshaling %#v to json: %s", createNetworkRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new network: %s", createNetworkRequestJson))

	createdNetwork, resp, err := executeNetworkCreate(ctx, c, *createNetworkRequest)
	if err != nil {
		return diag.Errorf("error creating network: %s", createDescriptiveError(err, resp))
	}
	d.SetId(createdNetwork.GetId())

	// Wait for async provisioning to complete
	createEnvironmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if err := waitForNetworkToProvision(c.networkingV1ApiContext(ctx), c, createEnvironmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for network %q to provision: %s", d.Id(), createDescriptiveError(err))
	}

	createdNetworkJson, err := json.Marshal(createdNetwork)
	if err != nil {
		return diag.Errorf("error creating network %q: error marshaling %#v to json: %s", d.Id(), createdNetwork, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating network %q: %s", d.Id(), createdNetworkJson), map[string]interface{}{networkLoggingKey: d.Id()})

	return networkRead(ctx, d, meta)
}

func networkRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading network %q", d.Id()), map[string]interface{}{networkLoggingKey: d.Id()})
	if _, err := readNetworkAndSetAttributes(ctx, d, meta); err != nil {
		return diag.FromErr(fmt.Errorf("error reading network %q: %s", d.Id(), createDescriptiveError(err)))
	}
	return nil
}

func networkUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName) {
		return diag.Errorf("error updating network %q: only %q can be updated", d.Id(), paramDisplayName)
	}

	updateNetworkRequest := networkingv1.NewNetworkingV1NetworkUpdate()
	specUpdate := networkingv1.NewNetworkingV1NetworkSpecUpdate()
	if d.HasChange(paramDisplayName) {
		specUpdate.SetDisplayName(d.Get(paramDisplayName).(string))
	}

	// Environment is required in the update request body for resource identification
	updateEnvironmentRef := networkingv1.NewObjectReferenceWithDefaults()
	updateEnvironmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	specUpdate.SetEnvironment(*updateEnvironmentRef)

	updateNetworkRequest.SetSpec(*specUpdate)

	updateNetworkRequestJson, err := json.Marshal(updateNetworkRequest)
	if err != nil {
		return diag.Errorf("error updating network %q: error marshaling %#v to json: %s", d.Id(), updateNetworkRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating network %q: %s", d.Id(), updateNetworkRequestJson), map[string]interface{}{networkLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedNetwork, resp, err := c.networkingV1Client.NetworksNetworkingV1Api.UpdateNetworkingV1Network(c.networkingV1ApiContext(ctx), d.Id()).NetworkingV1NetworkUpdate(*updateNetworkRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating network %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedNetworkJson, err := json.Marshal(updatedNetwork)
	if err != nil {
		return diag.Errorf("error updating network %q: error marshaling %#v to json: %s", d.Id(), updatedNetwork, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating network %q: %s", d.Id(), updatedNetworkJson), map[string]interface{}{networkLoggingKey: d.Id()})

	return networkRead(ctx, d, meta)
}

func networkDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting network %q", d.Id()), map[string]interface{}{networkLoggingKey: d.Id()})

	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	req := c.networkingV1Client.NetworksNetworkingV1Api.DeleteNetworkingV1Network(c.networkingV1ApiContext(ctx), d.Id()).Environment(environmentId)
	resp, err := req.Execute()
	if err != nil {
		return diag.Errorf("error deleting network %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	// Wait for async deletion to complete
	if err := waitForNetworkToBeDeleted(c.networkingV1ApiContext(ctx), c, environmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for network %q to be deleted: %s", d.Id(), createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting network %q", d.Id()), map[string]interface{}{networkLoggingKey: d.Id()})

	return nil
}

func executeNetworkCreate(ctx context.Context, c *Client, network networkingv1.NetworkingV1Network) (networkingv1.NetworkingV1Network, *http.Response, error) {
	req := c.networkingV1Client.NetworksNetworkingV1Api.CreateNetworkingV1Network(c.networkingV1ApiContext(ctx)).NetworkingV1Network(network)
	return req.Execute()
}
func executeNetworkRead(ctx context.Context, c *Client, environmentId string, id string) (networkingv1.NetworkingV1Network, *http.Response, error) {
	req := c.networkingV1Client.NetworksNetworkingV1Api.GetNetworkingV1Network(c.networkingV1ApiContext(ctx), id).Environment(environmentId)
	return req.Execute()
}

func readNetworkAndSetAttributes(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	network, resp, err := executeNetworkRead(ctx, c, environmentId, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading network %q: %s", d.Id(), readErr), map[string]interface{}{networkLoggingKey: d.Id()})
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing network %q in TF state because network could not be found on the server", d.Id()), map[string]interface{}{networkLoggingKey: d.Id()})
			d.SetId("")
			return nil, nil
		}
		return nil, fmt.Errorf("error reading network %q: %s", d.Id(), readErr)
	}

	networkJson, err := json.Marshal(network)
	if err != nil {
		return nil, fmt.Errorf("error reading network %q: error marshaling %#v to json: %s", network.GetId(), network, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched network %q: %s", d.Id(), networkJson), map[string]interface{}{networkLoggingKey: d.Id()})

	if _, err := setNetworkAttributes(d, network); err != nil {
		// No resp: a d.Set failure is not an API error, and resp.Body is already consumed.
		return nil, fmt.Errorf("error setting network attributes %q: %s", d.Id(), createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished reading network %q", d.Id()), map[string]interface{}{networkLoggingKey: d.Id()})

	return []*schema.ResourceData{d}, nil
}

func setNetworkAttributes(d *schema.ResourceData, network networkingv1.NetworkingV1Network) (*schema.ResourceData, error) {
	spec := network.GetSpec()
	if err := d.Set(paramCidr, spec.GetCidr()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramCloud, spec.GetCloud()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramConnectionTypes, spec.GetConnectionTypes()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramDisplayName, spec.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	dnsConfigObj := spec.GetDnsConfig()
	if err := d.Set(paramDnsConfig, []interface{}{map[string]interface{}{
		paramResolution: dnsConfigObj.GetResolution(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	environmentRef := spec.GetEnvironment()
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	gatewayRef := spec.GetGateway()
	if err := d.Set(paramGateway, []interface{}{map[string]interface{}{
		paramId: gatewayRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramRegion, spec.GetRegion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramReservedCidr, spec.GetReservedCidr()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramZones, spec.GetZones()); err != nil {
		return nil, createDescriptiveError(err)
	}
	zonesInfoObjs := spec.GetZonesInfo()
	zonesInfoList := make([]interface{}, len(zonesInfoObjs))
	for i, zonesInfoObj := range zonesInfoObjs {
		zonesInfoList[i] = map[string]interface{}{
			paramZoneId: zonesInfoObj.GetZoneId(),
			paramCidr:   zonesInfoObj.GetCidr(),
		}
	}
	if err := d.Set(paramZoneInfo, zonesInfoList); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceName, network.Metadata.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramDnsDomain, network.Status.GetDnsDomain()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramEndpointSuffix, network.Status.GetEndpointSuffix()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramZonalSubdomains, network.Status.GetZonalSubdomains()); err != nil {
		return nil, createDescriptiveError(err)
	}
	oneOfCloud := network.Status.GetCloud()

	// Read-only variants are Computed-only: clear them so an unmatched one is known, not
	// "known after apply" on every plan. The switch below populates the one that matches.
	if err := d.Set(paramAws, []interface{}{}); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramGcp, []interface{}{}); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramAzure, []interface{}{}); err != nil {
		return nil, createDescriptiveError(err)
	}

	switch {
	case oneOfCloud.NetworkingV1AwsNetwork != nil:
		if err := d.Set(paramAws, []interface{}{map[string]interface{}{
			paramAccount:                    oneOfCloud.NetworkingV1AwsNetwork.GetAccount(),
			paramPrivateLinkEndpointService: oneOfCloud.NetworkingV1AwsNetwork.GetPrivateLinkEndpointService(),
			paramVpc:                        oneOfCloud.NetworkingV1AwsNetwork.GetVpc(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1GcpNetwork != nil:
		if err := d.Set(paramGcp, []interface{}{map[string]interface{}{
			paramPrivateServiceConnectServiceAttachments: oneOfCloud.NetworkingV1GcpNetwork.GetPrivateServiceConnectServiceAttachments(),
			paramProject:    oneOfCloud.NetworkingV1GcpNetwork.GetProject(),
			paramVpcNetwork: oneOfCloud.NetworkingV1GcpNetwork.GetVpcNetwork(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1AzureNetwork != nil:
		if err := d.Set(paramAzure, []interface{}{map[string]interface{}{
			paramPrivateLinkServiceAliases:          oneOfCloud.NetworkingV1AzureNetwork.GetPrivateLinkServiceAliases(),
			paramAzurePrivateLinkServiceResourceIds: oneOfCloud.NetworkingV1AzureNetwork.GetPrivateLinkServiceResourceIds(),
			paramSubscription:                       oneOfCloud.NetworkingV1AzureNetwork.GetSubscription(),
			paramVnet:                               oneOfCloud.NetworkingV1AzureNetwork.GetVnet(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	}

	d.SetId(network.GetId())
	return d, nil
}

func networkImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing network %q", d.Id()), map[string]interface{}{networkLoggingKey: d.Id()})

	envIDAndResourceId := d.Id()
	parts := strings.Split(envIDAndResourceId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing network: invalid format: expected '<environment ID>/<network ID>'")
	}
	environmentId := parts[0]
	resourceId := parts[1]
	d.SetId(resourceId)
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if _, err := readNetworkAndSetAttributes(ctx, d, meta); err != nil {
		return nil, fmt.Errorf("error importing network %q: %s", d.Id(), err)
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished importing network %q", d.Id()), map[string]interface{}{networkLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}

// networkDeleteStatus returns a StateRefreshFunc for polling the delete status
func networkDeleteStatus(ctx context.Context, c *Client, environmentId string, networkId string) resource.StateRefreshFunc {
	return func() (result interface{}, s string, err error) {
		network, resp, err := executeNetworkRead(ctx, c, environmentId, networkId)
		if err != nil {
			if isNonKafkaRestApiResourceNotFound(resp) {
				// Resource is deleted
				return network, "DELETED", nil
			}
			tflog.Warn(ctx, fmt.Sprintf("Error reading network %q: %s", networkId, createDescriptiveError(err, resp)), map[string]interface{}{networkLoggingKey: networkId})
			return nil, stateNetworkUnknown, err
		}

		// Resource still exists
		return network, "DELETING", nil
	}
}

// waitForNetworkToBeDeleted waits for the resource to be fully deleted
func waitForNetworkToBeDeleted(ctx context.Context, c *Client, environmentId string, networkId string) error {
	delay, pollInterval := getDelayAndPollInterval(5*time.Second, 1*time.Minute, c.isAcceptanceTestMode)
	stateConf := &resource.StateChangeConf{
		Pending:      []string{"DELETING"},
		Target:       []string{"DELETED"},
		Refresh:      networkDeleteStatus(ctx, c, environmentId, networkId),
		Timeout:      networkingAPIDeleteTimeout,
		Delay:        delay,
		PollInterval: pollInterval,
	}

	tflog.Debug(ctx, fmt.Sprintf("Waiting for network %q to be deleted", networkId), map[string]interface{}{networkLoggingKey: networkId})
	if _, err := stateConf.WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}
func dnsConfigSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramResolution: {
					Type:        schema.TypeString,
					Required:    true,
					ForceNew:    true,
					Description: "Network DNS resolution type.",
				},
			},
		},
		Optional:    true,
		Computed:    true,
		MaxItems:    1,
		ForceNew:    true,
		Description: "DNS config only applies to PrivateLink network connection type. When resolution is CHASED_PRIVATE, clusters in this network require both public and private DNS to resolve cluster endpoints. When resolution is PRIVATE, clusters in this network only require private DNS to resolve cluster endpoints.",
	}
}
func zonesInfoSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramZoneId: {
					Type:        schema.TypeString,
					Optional:    true,
					Computed:    true,
					Description: "Cloud provider zone id",
				},
				paramCidr: {
					Type:        schema.TypeString,
					Optional:    true,
					Computed:    true,
					Description: "The IPv4 [CIDR block](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) to used for this network. Must be a `/27`. Required for VPC peering and AWS TransitGateway.",
				},
			},
		},
		Optional:    true,
		Computed:    true,
		ForceNew:    true,
		Description: "Each item represents information related to a single zone. Note - The attribute is in a [Limited Availability lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)",
	}
}
