// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/walkerus/go-wiremock"
)

const (
	scenarioStateResourceSubscriptionHasBeenCreated = "The new resource subscription has been just created"
	scenarioStateResourceSubscriptionHasBeenUpdated = "The resource subscription has been just updated"
	scenarioStateResourceSubscriptionHasBeenDeleted = "The resource subscription has been deleted"
	resourceSubscriptionScenarioName                = "confluent_notifications_resource_subscription Resource Lifecycle"
	resourceSubscriptionId                          = "dlz-f3a90de"
)

func TestAccNotificationsResourceSubscription(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	createResourceSubscriptionResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_subscription/create_resource_subscription.json")
	createResourceSubscriptionStub := wiremock.Post(wiremock.URLPathEqualTo("/notifications/v1/resource-subscriptions")).
		InScenario(resourceSubscriptionScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillSetStateTo(scenarioStateResourceSubscriptionHasBeenCreated).
		WillReturn(
			string(createResourceSubscriptionResponse),
			contentTypeJSONHeader,
			http.StatusCreated,
		)
	_ = wiremockClient.StubFor(createResourceSubscriptionStub)

	readCreatedResourceSubscriptionResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_subscription/read_created_resource_subscription.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-subscriptions/%s", resourceSubscriptionId))).
		InScenario(resourceSubscriptionScenarioName).
		WhenScenarioStateIs(scenarioStateResourceSubscriptionHasBeenCreated).
		WillReturn(
			string(readCreatedResourceSubscriptionResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))

	readUpdatedResourceSubscriptionResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_subscription/read_updated_resource_subscription.json")
	patchResourceSubscriptionStub := wiremock.Patch(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-subscriptions/%s", resourceSubscriptionId))).
		InScenario(resourceSubscriptionScenarioName).
		WhenScenarioStateIs(scenarioStateResourceSubscriptionHasBeenCreated).
		WillSetStateTo(scenarioStateResourceSubscriptionHasBeenUpdated).
		WillReturn(
			string(readUpdatedResourceSubscriptionResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		)
	_ = wiremockClient.StubFor(patchResourceSubscriptionStub)

	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-subscriptions/%s", resourceSubscriptionId))).
		InScenario(resourceSubscriptionScenarioName).
		WhenScenarioStateIs(scenarioStateResourceSubscriptionHasBeenUpdated).
		WillReturn(
			string(readUpdatedResourceSubscriptionResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))

	readDeletedResourceSubscriptionResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_subscription/read_deleted_resource_subscription.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-subscriptions/%s", resourceSubscriptionId))).
		InScenario(resourceSubscriptionScenarioName).
		WhenScenarioStateIs(scenarioStateResourceSubscriptionHasBeenDeleted).
		WillReturn(
			string(readDeletedResourceSubscriptionResponse),
			contentTypeJSONHeader,
			http.StatusForbidden,
		))

	deleteResourceSubscriptionStub := wiremock.Delete(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-subscriptions/%s", resourceSubscriptionId))).
		InScenario(resourceSubscriptionScenarioName).
		WhenScenarioStateIs(scenarioStateResourceSubscriptionHasBeenUpdated).
		WillSetStateTo(scenarioStateResourceSubscriptionHasBeenDeleted).
		WillReturn(
			"",
			contentTypeJSONHeader,
			http.StatusNoContent,
		)
	_ = wiremockClient.StubFor(deleteResourceSubscriptionStub)
	resourceValue := "environment=env-456xy/cloud-cluster=lkc-df123/connector=my_datagen_connector"
	resourceType := "CONNECTOR"
	currentState := "ENABLED"
	notificationType := "not-abc123"
	integrations := "[\"\"]"
	// in order to test tf update (step #3)
	resourceValueUpdated := "environment=env-456xy/cloud-cluster=lkc-df123/connector=my_datagen_connector_updated"
	resourceSubscriptionResourceLabel := "test_resource_subscription_resource_label"
	fullResourceSubscriptionResourceLabel := fmt.Sprintf("confluent_notifications_resource_subscription.%s", resourceSubscriptionResourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckNotificationsResourceSubscriptionDestroy,
		// https://www.terraform.io/docs/extend/testing/acceptance-tests/teststep.html
		// https://www.terraform.io/docs/extend/best-practices/testing.html#built-in-patterns
		Steps: []resource.TestStep{
			{
				Config: testAccCheckNotificationsResourceSubscriptionConfig(mockServerUrl, resourceSubscriptionResourceLabel, resourceValue, resourceType, currentState, notificationType, integrations),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckNotificationsResourceSubscriptionExists(fullResourceSubscriptionResourceLabel),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "id", resourceSubscriptionId),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "resource", resourceValue),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "resource_type", resourceType),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "current_state", currentState),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "notification_type.0.id", notificationType),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "integrations.#", "1"),
					resource.TestCheckTypeSetElemAttr(fullResourceSubscriptionResourceLabel, "integrations.*", ""),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "kind", "ResourceSubscription"),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/resource-subscription=rs-12345"),
				),
			},
			{
				// https://www.terraform.io/docs/extend/resources/import.html
				ResourceName:      fullResourceSubscriptionResourceLabel,
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccCheckNotificationsResourceSubscriptionConfig(mockServerUrl, resourceSubscriptionResourceLabel, resourceValueUpdated, resourceType, currentState, notificationType, integrations),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckNotificationsResourceSubscriptionExists(fullResourceSubscriptionResourceLabel),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "id", resourceSubscriptionId),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "resource", resourceValueUpdated),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "resource_type", resourceType),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "current_state", currentState),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "notification_type.0.id", notificationType),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "integrations.#", "1"),
					resource.TestCheckTypeSetElemAttr(fullResourceSubscriptionResourceLabel, "integrations.*", ""),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "kind", "ResourceSubscription"),
					resource.TestCheckResourceAttr(fullResourceSubscriptionResourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/resource-subscription=rs-12345"),
				),
			},
			{
				ResourceName:      fullResourceSubscriptionResourceLabel,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})

	checkStubCount(t, wiremockClient, createResourceSubscriptionStub, "POST /notifications/v1/resource-subscriptions", expectedCountOne)
	checkStubCount(t, wiremockClient, patchResourceSubscriptionStub, fmt.Sprintf("PATCH /notifications/v1/resource-subscriptions/%s", resourceSubscriptionId), expectedCountOne)
	checkStubCount(t, wiremockClient, deleteResourceSubscriptionStub, fmt.Sprintf("DELETE /notifications/v1/resource-subscriptions/%s", resourceSubscriptionId), expectedCountOne)
}

func testAccCheckNotificationsResourceSubscriptionDestroy(s *terraform.State) error {
	c := testAccProvider.Meta().(*Client)
	// Loop through the resources in state, verifying each resource subscription is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "confluent_notifications_resource_subscription" {
			continue
		}
		deletedResourceSubscriptionId := rs.Primary.ID
		req := c.notificationsV1Client.ResourceSubscriptionsNotificationsV1Api.GetNotificationsV1ResourceSubscription(c.notificationsV1ApiContext(context.Background()), deletedResourceSubscriptionId)
		deletedResourceSubscription, response, err := req.Execute()
		if response != nil && (response.StatusCode == http.StatusForbidden || response.StatusCode == http.StatusNotFound) {
			// If the error is equivalent to http.StatusNotFound, the resource subscription is destroyed.
			return nil
		} else if err == nil && deletedResourceSubscription.Id != nil {
			// Otherwise return the error
			if *deletedResourceSubscription.Id == rs.Primary.ID {
				return fmt.Errorf("resource subscription (%q) still exists", rs.Primary.ID)
			}
		}
		return err
	}
	return nil
}

func testAccCheckNotificationsResourceSubscriptionConfig(mockServerUrl, resourceSubscriptionResourceLabel string, resourceValue string, resourceType string, currentState string, notificationType string, integrations string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	resource "confluent_notifications_resource_subscription" "%s" {
		resource = %q
		resource_type = %q
		current_state = %q
		notification_type {
			id = %q
		}
		integrations = %s
	}
	`, mockServerUrl, resourceSubscriptionResourceLabel, resourceValue, resourceType, currentState, notificationType, integrations)
}

func testAccCheckNotificationsResourceSubscriptionExists(n string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[n]

		if !ok {
			return fmt.Errorf("%s resource subscription has not been found", n)
		}

		if rs.Primary.ID == "" {
			return fmt.Errorf("ID has not been set for %s resource subscription", n)
		}

		return nil
	}
}
