// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.8.0; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	ksqlv2 "github.com/confluentinc/ccloud-sdk-go-v2/ksql/v2"
)

func ksqlClusterResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: ksqlClusterCreate,
		ReadContext:   ksqlClusterRead,
		DeleteContext: ksqlClusterDelete,
		Importer: &schema.ResourceImporter{
			StateContext: ksqlClusterImport,
		},
		Schema: map[string]*schema.Schema{
			paramDisplayName: {
				Type:         schema.TypeString,
				Description:  "The name of the ksqlDB cluster.",
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringIsNotEmpty,
			},
			paramUseDetailedProcessingLog: {
				Type:        schema.TypeBool,
				Description: "This flag controls whether you want to include the row data in the processing log topic. Turn it off if you don't want to emit sensitive information to the processing log",
				Optional:    true,
				Default:     true,
				ForceNew:    true,
			},
			paramCsu: {
				Type:         schema.TypeInt,
				Description:  "The number of CSUs (Confluent Streaming Units) in a ksqlDB cluster.",
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validation.IntAtLeast(1),
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramRestEndpoint: {
				Type:        schema.TypeString,
				Description: "The dataplane endpoint of the ksqlDB cluster.",
				Computed:    true,
			},
			paramStorage: {
				Type:        schema.TypeInt,
				Description: "Amount of storage (in GB) provisioned to this cluster",
				Computed:    true,
			},
			paramTopicPrefix: {
				Type:        schema.TypeString,
				Description: "Topic name prefix used by this ksqlDB cluster. Used to assign ACLs for this ksqlDB cluster to use.",
				Computed:    true,
			},
			paramKafkaCluster:       requiredKafkaClusterBlockSchema(),
			paramCredentialIdentity: credentialIdentityBlockSchema(),
			paramEnvironment:        environmentSchema(),
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Cluster.",
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(ksqlCreateTimeout),
			Delete: schema.DefaultTimeout(ksqlDeleteTimeout),
		},
	}
}

func ksqlClusterCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	createKsqlClusterIdentifier := d.Get(paramDisplayName).(string)
	spec := ksqlv2.NewKsqldbcmV2ClusterSpec()

	// Set required attributes
	credentialIdentityRef := ksqlv2.NewObjectReferenceWithDefaults()
	credentialIdentityRef.SetId(extractStringValueFromBlock(d, paramCredentialIdentity, paramId))
	spec.SetCredentialIdentity(*credentialIdentityRef)
	spec.SetCsu(int32(d.Get(paramCsu).(int)))
	spec.SetDisplayName(d.Get(paramDisplayName).(string))
	environmentRef := ksqlv2.NewObjectReferenceWithDefaults()
	environmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	spec.SetEnvironment(*environmentRef)
	kafkaClusterRef := ksqlv2.NewObjectReferenceWithDefaults()
	kafkaClusterRef.SetId(extractStringValueFromBlock(d, paramKafkaCluster, paramId))
	spec.SetKafkaCluster(*kafkaClusterRef)

	// Set optional attributes
	spec.SetUseDetailedProcessingLog(d.Get(paramUseDetailedProcessingLog).(bool))

	createKsqlClusterRequest := &ksqlv2.KsqldbcmV2Cluster{Spec: spec}

	// Logging
	createKsqlClusterRequestJson, err := json.Marshal(createKsqlClusterRequest)
	if err != nil {
		return diag.Errorf("error creating ksql cluster: error marshaling %#v to json: %s", createKsqlClusterRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new ksql cluster: %s", createKsqlClusterRequestJson))

	// Make API call
	createdKsqlCluster, resp, err := executeKsqlClusterCreate(c.ksqlV2ApiContext(ctx), c, createKsqlClusterRequest)
	if err != nil {
		return diag.Errorf("error creating ksql cluster %q: %s", createKsqlClusterIdentifier, createDescriptiveError(err, resp))
	}
	d.SetId(createdKsqlCluster.GetId())
	createEnvironmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	// Wait for async provisioning to complete
	if err := waitForKsqlClusterToProvision(c.ksqlV2ApiContext(ctx), c, createEnvironmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for ksql cluster %q to provision: %s", d.Id(), createDescriptiveError(err))
	}

	// Logging
	createdKsqlClusterJson, err := json.Marshal(createdKsqlCluster)
	if err != nil {
		return diag.Errorf("error creating ksql cluster %q: error marshaling %#v to json: %s", d.Id(), createdKsqlCluster, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating ksql cluster %q: %s", d.Id(), createdKsqlClusterJson), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})

	return ksqlClusterRead(ctx, d, meta)
}

func ksqlClusterRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading ksql cluster %q", d.Id()), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})

	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	ksqlCluster, resp, err := executeKsqlClusterRead(c.ksqlV2ApiContext(ctx), c, environmentId, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading ksql cluster %q: %s", d.Id(), readErr), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})

		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing ksql cluster %q in TF state because ksql cluster could not be found on the server", d.Id()), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})
			d.SetId("")
			return nil
		}

		return diag.FromErr(readErr)
	}

	ksqlClusterJson, err := json.Marshal(ksqlCluster)
	if err != nil {
		return diag.Errorf("error reading ksql cluster %q: error marshaling %#v to json: %s", d.Id(), ksqlCluster, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched ksql cluster %q: %s", d.Id(), ksqlClusterJson), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})

	if _, err := setKsqlClusterAttributes(d, ksqlCluster); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished reading ksql cluster %q", d.Id()), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})

	return nil
}

func ksqlClusterDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting ksql cluster %q", d.Id()), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	c := meta.(*Client)
	req := c.ksqlV2Client.ClustersKsqldbcmV2Api.DeleteKsqldbcmV2Cluster(c.ksqlV2ApiContext(ctx), d.Id()).Environment(environmentId)
	resp, err := req.Execute()

	if err != nil {
		return diag.Errorf("error deleting ksql cluster %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	// Wait for async deletion to complete
	if err := waitForKsqlClusterToBeDeleted(c.ksqlV2ApiContext(ctx), c, environmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for ksql cluster %q to be deleted: %s", d.Id(), createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting ksql cluster %q", d.Id()), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})

	return nil
}

func ksqlClusterImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing ksql cluster %q", d.Id()), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})

	importId := d.Id()
	parts := strings.Split(importId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing ksql cluster: invalid format: expected '<environment ID>/<ksql cluster ID>'")
	}
	environmentId := parts[0]
	resourceId := parts[len(parts)-1]
	d.SetId(resourceId)
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if diagnostics := ksqlClusterRead(ctx, d, meta); len(diagnostics) > 0 {
		return nil, fmt.Errorf("error importing ksql cluster %q: %s", d.Id(), diagnostics[0].Summary)
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished importing ksql cluster %q", d.Id()), map[string]interface{}{ksqlClusterLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}

func executeKsqlClusterCreate(ctx context.Context, c *Client, ksqlCluster *ksqlv2.KsqldbcmV2Cluster) (ksqlv2.KsqldbcmV2Cluster, *http.Response, error) {
	req := c.ksqlV2Client.ClustersKsqldbcmV2Api.CreateKsqldbcmV2Cluster(c.ksqlV2ApiContext(ctx)).KsqldbcmV2Cluster(*ksqlCluster)
	return req.Execute()
}

func executeKsqlClusterRead(ctx context.Context, c *Client, environmentId string, ksqlClusterId string) (ksqlv2.KsqldbcmV2Cluster, *http.Response, error) {
	req := c.ksqlV2Client.ClustersKsqldbcmV2Api.GetKsqldbcmV2Cluster(c.ksqlV2ApiContext(ctx), ksqlClusterId).Environment(environmentId)
	return req.Execute()
}

func setKsqlClusterAttributes(d *schema.ResourceData, ksqlCluster ksqlv2.KsqldbcmV2Cluster) (*schema.ResourceData, error) {
	spec := ksqlCluster.GetSpec()
	if err := d.Set(paramDisplayName, spec.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramUseDetailedProcessingLog, spec.GetUseDetailedProcessingLog()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramCsu, spec.GetCsu()); err != nil {
		return nil, createDescriptiveError(err)
	}

	if err := d.Set(paramApiVersion, ksqlCluster.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, ksqlCluster.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramRestEndpoint, ksqlCluster.Status.GetHttpEndpoint()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramStorage, ksqlCluster.Status.GetStorage()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramTopicPrefix, ksqlCluster.Status.GetTopicPrefix()); err != nil {
		return nil, createDescriptiveError(err)
	}

	if err := d.Set(paramResourceName, ksqlCluster.Metadata.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}

	kafkaClusterRef := spec.GetKafkaCluster()
	if err := d.Set(paramKafkaCluster, []interface{}{map[string]interface{}{
		paramId: kafkaClusterRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	credentialIdentityRef := spec.GetCredentialIdentity()
	if err := d.Set(paramCredentialIdentity, []interface{}{map[string]interface{}{
		paramId: credentialIdentityRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	environmentRef := spec.GetEnvironment()
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(ksqlCluster.GetId())
	return d, nil
}

// ksqlClusterProvisionStatus returns a StateRefreshFunc for polling the resource status
func ksqlClusterProvisionStatus(ctx context.Context, c *Client, environmentId string, ksqlClusterId string) resource.StateRefreshFunc {
	return func() (result interface{}, s string, err error) {
		ksqlCluster, resp, err := executeKsqlClusterRead(c.ksqlV2ApiContext(ctx), c, environmentId, ksqlClusterId)
		if err != nil {
			tflog.Warn(ctx, fmt.Sprintf("Error reading ksql cluster %q: %s", ksqlClusterId, createDescriptiveError(err, resp)), map[string]interface{}{ksqlClusterLoggingKey: ksqlClusterId})
			return nil, stateUnknown, err
		}

		currentPhase := ksqlCluster.Status.GetPhase()
		tflog.Debug(ctx, fmt.Sprintf("Waiting for ksql cluster %q provisioning status to become one of %v: current status is %q", ksqlClusterId, []string{stateProvisioned}, currentPhase), map[string]interface{}{ksqlClusterLoggingKey: ksqlClusterId})

		// Check for pending states (still provisioning)
		switch currentPhase {
		case stateProvisioning:
			return ksqlCluster, currentPhase, nil
		}

		// Check for target states (provisioning complete)
		switch currentPhase {
		case stateProvisioned:
			return ksqlCluster, currentPhase, nil
		}

		// Check for failed states
		switch currentPhase {
		case stateFailed:
			return nil, stateFailed, fmt.Errorf("ksql cluster %q provisioning status is %q", ksqlClusterId, stateFailed)
		}

		// Unexpected state
		return nil, stateUnexpected, fmt.Errorf("ksql cluster %q is in an unexpected state %q", ksqlClusterId, currentPhase)
	}
}

// waitForKsqlClusterToProvision waits for the resource to reach a ready state
func waitForKsqlClusterToProvision(ctx context.Context, c *Client, environmentId string, ksqlClusterId string) error {
	delay, pollInterval := getDelayAndPollInterval(5*time.Second, 1*time.Minute, c.isAcceptanceTestMode)
	stateConf := &resource.StateChangeConf{
		Pending:      []string{stateProvisioning},
		Target:       []string{stateProvisioned},
		Refresh:      ksqlClusterProvisionStatus(ctx, c, environmentId, ksqlClusterId),
		Timeout:      ksqlCreateTimeout,
		Delay:        delay,
		PollInterval: pollInterval,
	}

	tflog.Debug(ctx, fmt.Sprintf("Waiting for ksql cluster %q provisioning status to become one of %v", ksqlClusterId, []string{stateProvisioned}), map[string]interface{}{ksqlClusterLoggingKey: ksqlClusterId})
	if _, err := stateConf.WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}

// ksqlClusterDeleteStatus returns a StateRefreshFunc for polling the delete status
func ksqlClusterDeleteStatus(ctx context.Context, c *Client, environmentId string, ksqlClusterId string) resource.StateRefreshFunc {
	return func() (result interface{}, s string, err error) {
		ksqlCluster, resp, err := executeKsqlClusterRead(c.ksqlV2ApiContext(ctx), c, environmentId, ksqlClusterId)
		if err != nil {
			if isNonKafkaRestApiResourceNotFound(resp) {
				// Resource is deleted
				return ksqlCluster, "DELETED", nil
			}
			tflog.Warn(ctx, fmt.Sprintf("Error reading ksql cluster %q: %s", ksqlClusterId, createDescriptiveError(err, resp)), map[string]interface{}{ksqlClusterLoggingKey: ksqlClusterId})
			return nil, stateUnknown, err
		}

		// Resource still exists
		return ksqlCluster, "DELETING", nil
	}
}

// waitForKsqlClusterToBeDeleted waits for the resource to be fully deleted
func waitForKsqlClusterToBeDeleted(ctx context.Context, c *Client, environmentId string, ksqlClusterId string) error {
	delay, pollInterval := getDelayAndPollInterval(5*time.Second, 1*time.Minute, c.isAcceptanceTestMode)
	stateConf := &resource.StateChangeConf{
		Pending:      []string{"DELETING"},
		Target:       []string{"DELETED"},
		Refresh:      ksqlClusterDeleteStatus(ctx, c, environmentId, ksqlClusterId),
		Timeout:      ksqlDeleteTimeout,
		Delay:        delay,
		PollInterval: pollInterval,
	}

	tflog.Debug(ctx, fmt.Sprintf("Waiting for ksql cluster %q to be deleted", ksqlClusterId), map[string]interface{}{ksqlClusterLoggingKey: ksqlClusterId})
	if _, err := stateConf.WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}
