// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/walkerus/go-wiremock"
)

const (
	scenarioStateResourcePreferenceHasBeenCreated = "The new resource preference has been just created"
	scenarioStateResourcePreferenceHasBeenUpdated = "The resource preference has been just updated"
	scenarioStateResourcePreferenceHasBeenDeleted = "The resource preference has been deleted"
	resourcePreferenceScenarioName                = "confluent_notifications_resource_preference Resource Lifecycle"
	resourcePreferenceId                          = "dlz-f3a90de"
)

func TestAccNotificationsResourcePreference(t *testing.T) {
	ctx := context.Background()

	wiremockContainer, err := setupWiremock(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer wiremockContainer.Terminate(ctx)

	mockServerUrl := wiremockContainer.URI
	wiremockClient := wiremock.NewClient(mockServerUrl)
	// nolint:errcheck
	defer wiremockClient.Reset()

	// nolint:errcheck
	defer wiremockClient.ResetAllScenarios()

	createResourcePreferenceResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_preference/create_resource_preference.json")
	createResourcePreferenceStub := wiremock.Post(wiremock.URLPathEqualTo("/notifications/v1/resource-preferences")).
		InScenario(resourcePreferenceScenarioName).
		WhenScenarioStateIs(wiremock.ScenarioStateStarted).
		WillSetStateTo(scenarioStateResourcePreferenceHasBeenCreated).
		WillReturn(
			string(createResourcePreferenceResponse),
			contentTypeJSONHeader,
			http.StatusCreated,
		)
	_ = wiremockClient.StubFor(createResourcePreferenceStub)

	readCreatedResourcePreferenceResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_preference/read_created_resource_preference.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-preferences/%s", resourcePreferenceId))).
		InScenario(resourcePreferenceScenarioName).
		WhenScenarioStateIs(scenarioStateResourcePreferenceHasBeenCreated).
		WillReturn(
			string(readCreatedResourcePreferenceResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))

	readUpdatedResourcePreferenceResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_preference/read_updated_resource_preference.json")
	patchResourcePreferenceStub := wiremock.Patch(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-preferences/%s", resourcePreferenceId))).
		InScenario(resourcePreferenceScenarioName).
		WhenScenarioStateIs(scenarioStateResourcePreferenceHasBeenCreated).
		WillSetStateTo(scenarioStateResourcePreferenceHasBeenUpdated).
		WillReturn(
			string(readUpdatedResourcePreferenceResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		)
	_ = wiremockClient.StubFor(patchResourcePreferenceStub)

	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-preferences/%s", resourcePreferenceId))).
		InScenario(resourcePreferenceScenarioName).
		WhenScenarioStateIs(scenarioStateResourcePreferenceHasBeenUpdated).
		WillReturn(
			string(readUpdatedResourcePreferenceResponse),
			contentTypeJSONHeader,
			http.StatusOK,
		))

	readDeletedResourcePreferenceResponse, _ := ioutil.ReadFile("../testdata/notifications_resource_preference/read_deleted_resource_preference.json")
	_ = wiremockClient.StubFor(wiremock.Get(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-preferences/%s", resourcePreferenceId))).
		InScenario(resourcePreferenceScenarioName).
		WhenScenarioStateIs(scenarioStateResourcePreferenceHasBeenDeleted).
		WillReturn(
			string(readDeletedResourcePreferenceResponse),
			contentTypeJSONHeader,
			http.StatusForbidden,
		))

	deleteResourcePreferenceStub := wiremock.Delete(wiremock.URLPathEqualTo(fmt.Sprintf("/notifications/v1/resource-preferences/%s", resourcePreferenceId))).
		InScenario(resourcePreferenceScenarioName).
		WhenScenarioStateIs(scenarioStateResourcePreferenceHasBeenUpdated).
		WillSetStateTo(scenarioStateResourcePreferenceHasBeenDeleted).
		WillReturn(
			"",
			contentTypeJSONHeader,
			http.StatusNoContent,
		)
	_ = wiremockClient.StubFor(deleteResourcePreferenceStub)
	resourceValue := "environment=env-456xy/cloud-cluster=lkc-df123/connector=my_datagen_connector"
	resourceType := "CONNECTOR"
	currentState := "ENABLED"
	// in order to test tf update (step #3)
	resourceValueUpdated := "environment=env-456xy/cloud-cluster=lkc-df123/connector=my_datagen_connector_updated"
	resourceTypeUpdated := "ORGANIZATION"
	currentStateUpdated := "DISABLED"
	resourcePreferenceResourceLabel := "test_resource_preference_resource_label"
	fullResourcePreferenceResourceLabel := fmt.Sprintf("confluent_notifications_resource_preference.%s", resourcePreferenceResourceLabel)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccPreCheck(t) },
		ProviderFactories: testAccProviderFactories,
		CheckDestroy:      testAccCheckNotificationsResourcePreferenceDestroy,
		// https://www.terraform.io/docs/extend/testing/acceptance-tests/teststep.html
		// https://www.terraform.io/docs/extend/best-practices/testing.html#built-in-patterns
		Steps: []resource.TestStep{
			{
				Config: testAccCheckNotificationsResourcePreferenceConfig(mockServerUrl, resourcePreferenceResourceLabel, resourceValue, resourceType, currentState),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckNotificationsResourcePreferenceExists(fullResourcePreferenceResourceLabel),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "id", resourcePreferenceId),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "resource", resourceValue),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "resource_type", resourceType),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "current_state", currentState),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "kind", "ResourcePreference"),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/resource-preference=rp-12345"),
				),
			},
			{
				// https://www.terraform.io/docs/extend/resources/import.html
				ResourceName:      fullResourcePreferenceResourceLabel,
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccCheckNotificationsResourcePreferenceConfig(mockServerUrl, resourcePreferenceResourceLabel, resourceValueUpdated, resourceTypeUpdated, currentStateUpdated),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckNotificationsResourcePreferenceExists(fullResourcePreferenceResourceLabel),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "id", resourcePreferenceId),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "resource", resourceValueUpdated),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "resource_type", resourceTypeUpdated),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "current_state", currentStateUpdated),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "api_version", "notifications/v1"),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "kind", "ResourcePreference"),
					resource.TestCheckResourceAttr(fullResourcePreferenceResourceLabel, "resource_name", "crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/resource-preference=rp-12345"),
				),
			},
			{
				ResourceName:      fullResourcePreferenceResourceLabel,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})

	checkStubCount(t, wiremockClient, createResourcePreferenceStub, "POST /notifications/v1/resource-preferences", expectedCountOne)
	checkStubCount(t, wiremockClient, patchResourcePreferenceStub, fmt.Sprintf("PATCH /notifications/v1/resource-preferences/%s", resourcePreferenceId), expectedCountOne)
	checkStubCount(t, wiremockClient, deleteResourcePreferenceStub, fmt.Sprintf("DELETE /notifications/v1/resource-preferences/%s", resourcePreferenceId), expectedCountOne)
}

func testAccCheckNotificationsResourcePreferenceDestroy(s *terraform.State) error {
	c := testAccProvider.Meta().(*Client)
	// Loop through the resources in state, verifying each resource preference is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "confluent_notifications_resource_preference" {
			continue
		}
		deletedResourcePreferenceId := rs.Primary.ID
		req := c.notificationsV1Client.ResourcePreferencesNotificationsV1Api.GetNotificationsV1ResourcePreference(c.notificationsV1ApiContext(context.Background()), deletedResourcePreferenceId)
		deletedResourcePreference, response, err := req.Execute()
		if response != nil && (response.StatusCode == http.StatusForbidden || response.StatusCode == http.StatusNotFound) {
			// If the error is equivalent to http.StatusNotFound, the resource preference is destroyed.
			return nil
		} else if err == nil && deletedResourcePreference.Id != nil {
			// Otherwise return the error
			if *deletedResourcePreference.Id == rs.Primary.ID {
				return fmt.Errorf("resource preference (%q) still exists", rs.Primary.ID)
			}
		}
		return err
	}
	return nil
}

func testAccCheckNotificationsResourcePreferenceConfig(mockServerUrl, resourcePreferenceResourceLabel string, resourceValue string, resourceType string, currentState string) string {
	return fmt.Sprintf(`
	provider "confluent" {
		endpoint = "%s"
	}
	resource "confluent_notifications_resource_preference" "%s" {
		resource = %q
		resource_type = %q
		current_state = %q
	}
	`, mockServerUrl, resourcePreferenceResourceLabel, resourceValue, resourceType, currentState)
}

func testAccCheckNotificationsResourcePreferenceExists(n string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[n]

		if !ok {
			return fmt.Errorf("%s resource preference has not been found", n)
		}

		if rs.Primary.ID == "" {
			return fmt.Errorf("ID has not been set for %s resource preference", n)
		}

		return nil
	}
}
