// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2/notifications/v1"
)

const resourcePreferenceLoggingKey = "resource_preference_id"

func resourcePreferenceResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourcePreferenceCreate,
		ReadContext:   resourcePreferenceRead,
		UpdateContext: resourcePreferenceUpdate,
		DeleteContext: resourcePreferenceDelete,
		Importer: &schema.ResourceImporter{
			StateContext: resourcePreferenceImport,
		},
		Schema: map[string]*schema.Schema{
			paramEndpointResource: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Denotes the Confluent Cloud resource definition.",
			},
			paramResourceType: {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringInSlice([]string{"ORGANIZATION", "ENVIRONMENT", "CLUSTER", "CONNECTOR", "FLINK_COMPUTE_POOL", "FLINK_STATEMENT"}, false),
				Description:  "Denotes the Confluent Cloud resource type.",
			},
			paramCurrentState: {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"ENABLED", "DISABLED"}, false),
				Description:  "Denotes the state of the resource preference. When the resource preference is ENABLED, the user will receive notifications for the Confluent Cloud resource. If the resource preference is DISABLED, the user will not receive any notification for the resource. Note that, you will still receive notifications for `REQUIRED` notification type even when it is DISABLED.",
			},
			paramApiVersion: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "API Version defines the schema version of this representation of a resource.",
			},
			paramKind: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Kind defines the object this REST resource represents.",
			},
			paramResourceName: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The Confluent Resource Name of the Resource Preference.",
			},
		},
	}
}

func resourcePreferenceCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	createResourcePreferenceIdentifier := d.Get(paramEndpointResource).(string)
	createResourcePreferenceRequest := notificationsv1.NewNotificationsV1ResourcePreference()

	// Set required attributes
	createResourcePreferenceRequest.SetResource(d.Get(paramEndpointResource).(string))
	createResourcePreferenceRequest.SetResourceType(d.Get(paramResourceType).(string))

	// Set optional attributes
	if _, ok := d.GetOk(paramCurrentState); ok {
		createResourcePreferenceRequest.SetCurrentState(d.Get(paramCurrentState).(string))
	}

	// Logging
	createResourcePreferenceRequestJson, err := json.Marshal(createResourcePreferenceRequest)
	if err != nil {
		return diag.Errorf("error creating resource preference: error marshaling %#v to json: %s", createResourcePreferenceRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new resource preference: %s", createResourcePreferenceRequestJson))

	// Make API call
	createdResourcePreference, resp, err := executeResourcePreferenceCreate(c.notificationsV1ApiContext(ctx), c, createResourcePreferenceRequest)
	if err != nil {
		return diag.Errorf("error creating resource preference %q: %s", createResourcePreferenceIdentifier, createDescriptiveError(err, resp))
	}

	d.SetId(createdResourcePreference.GetId())

	// Logging
	createdResourcePreferenceJson, err := json.Marshal(createdResourcePreference)
	if err != nil {
		return diag.Errorf("error creating resource preference %q: error marshaling %#v to json: %s", d.Id(), createdResourcePreference, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating resource preference %q: %s", d.Id(), createdResourcePreferenceJson), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	return resourcePreferenceRead(ctx, d, meta)
}

func executeResourcePreferenceCreate(ctx context.Context, c *Client, resourcePreference *notificationsv1.NotificationsV1ResourcePreference) (notificationsv1.NotificationsV1ResourcePreference, *http.Response, error) {
	req := c.notificationsV1Client.ResourcePreferencesNotificationsV1Api.CreateNotificationsV1ResourcePreference(c.notificationsV1ApiContext(ctx)).NotificationsV1ResourcePreference(*resourcePreference)
	return req.Execute()
}

func resourcePreferenceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading resource preference %q", d.Id()), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	c := meta.(*Client)
	resourcePreference, resp, err := executeResourcePreferenceRead(c.notificationsV1ApiContext(ctx), c, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading resource preference %q: %s", d.Id(), readErr), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing resource preference %q in TF state because resource preference could not be found on the server", d.Id()), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})
			d.SetId("")
			return nil
		}

		return diag.FromErr(readErr)
	}

	resourcePreferenceJson, err := json.Marshal(resourcePreference)
	if err != nil {
		return diag.Errorf("error reading resource preference %q: error marshaling %#v to json: %s", d.Id(), resourcePreference, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched resource preference %q: %s", d.Id(), resourcePreferenceJson), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	if _, err := setResourcePreferenceAttributes(d, resourcePreference); err != nil {
		return diag.FromErr(createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished reading resource preference %q", d.Id()), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	return nil
}

func executeResourcePreferenceRead(ctx context.Context, c *Client, resourcePreferenceId string) (notificationsv1.NotificationsV1ResourcePreference, *http.Response, error) {
	req := c.notificationsV1Client.ResourcePreferencesNotificationsV1Api.GetNotificationsV1ResourcePreference(c.notificationsV1ApiContext(ctx), resourcePreferenceId)
	return req.Execute()
}

func setResourcePreferenceAttributes(d *schema.ResourceData, resourcePreference notificationsv1.NotificationsV1ResourcePreference) (*schema.ResourceData, error) {
	if err := d.Set(paramEndpointResource, resourcePreference.GetResource()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceType, resourcePreference.GetResourceType()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramCurrentState, resourcePreference.GetCurrentState()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramApiVersion, resourcePreference.GetApiVersion()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramKind, resourcePreference.GetKind()); err != nil {
		return nil, createDescriptiveError(err)
	}
	if err := d.Set(paramResourceName, resourcePreference.Metadata.GetResourceName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	d.SetId(resourcePreference.GetId())
	return d, nil
}

func resourcePreferenceUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramEndpointResource, paramResourceType, paramCurrentState) {
		return diag.Errorf("error updating resource preference %q: only %q, %q, %q can be updated", d.Id(), paramEndpointResource, paramResourceType, paramCurrentState)
	}

	updateResourcePreferenceRequest := notificationsv1.NewNotificationsV1ResourcePreference()
	if d.HasChange(paramEndpointResource) {
		updateResourcePreferenceRequest.SetResource(d.Get(paramEndpointResource).(string))
	}
	if d.HasChange(paramResourceType) {
		updateResourcePreferenceRequest.SetResourceType(d.Get(paramResourceType).(string))
	}
	if d.HasChange(paramCurrentState) {
		updateResourcePreferenceRequest.SetCurrentState(d.Get(paramCurrentState).(string))
	}

	updateResourcePreferenceRequestJson, err := json.Marshal(updateResourcePreferenceRequest)
	if err != nil {
		return diag.Errorf("error updating resource preference %q: error marshaling %#v to json: %s", d.Id(), updateResourcePreferenceRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating resource preference %q: %s", d.Id(), updateResourcePreferenceRequestJson), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedResourcePreference, resp, err := c.notificationsV1Client.ResourcePreferencesNotificationsV1Api.UpdateNotificationsV1ResourcePreference(c.notificationsV1ApiContext(ctx), d.Id()).NotificationsV1ResourcePreference(*updateResourcePreferenceRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating resource preference %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedResourcePreferenceJson, err := json.Marshal(updatedResourcePreference)
	if err != nil {
		return diag.Errorf("error updating resource preference %q: error marshaling %#v to json: %s", d.Id(), updatedResourcePreference, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating resource preference %q: %s", d.Id(), updatedResourcePreferenceJson), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	return resourcePreferenceRead(ctx, d, meta)
}

func resourcePreferenceDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting resource preference %q", d.Id()), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})
	c := meta.(*Client)
	req := c.notificationsV1Client.ResourcePreferencesNotificationsV1Api.DeleteNotificationsV1ResourcePreference(c.notificationsV1ApiContext(ctx), d.Id())
	resp, err := req.Execute()

	if err != nil {
		return diag.Errorf("error deleting resource preference %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting resource preference %q", d.Id()), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	return nil
}

func resourcePreferenceImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing resource preference %q", d.Id()), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if diagnostics := resourcePreferenceRead(ctx, d, meta); len(diagnostics) > 0 {
		return nil, fmt.Errorf("error importing resource preference %q: %s", d.Id(), diagnostics[0].Summary)
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished importing resource preference %q", d.Id()), map[string]interface{}{resourcePreferenceLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
