// Copyright 2026 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cli-terraform-generator v0.22.2; DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	networkingv1 "github.com/confluentinc/ccloud-sdk-go-v2/networking/v1"
)

// Variant kind constants
const (
	kindAwsPeering   = "AwsPeering"
	kindGcpPeering   = "GcpPeering"
	kindAzurePeering = "AzurePeering"
)

// acceptedPeeringCloudVariants defines the list of valid cloud block types
var acceptedPeeringCloudVariants = []string{paramAws, paramGcp, paramAzure}

func peeringResource() *schema.Resource {
	return &schema.Resource{
		CreateContext: peeringCreate,
		ReadContext:   peeringRead,
		UpdateContext: peeringUpdate,
		DeleteContext: peeringDelete,
		Importer: &schema.ResourceImporter{
			StateContext: peeringImport,
		},
		Schema: map[string]*schema.Schema{
			paramDisplayName: {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The name of the peering",
			},
			paramEnvironment: environmentSchema(),
			paramNetwork:     requiredNetworkSchema(),
			paramAws:         awsPeeringSchema(),
			paramGcp:         gcpPeeringSchema(),
			paramAzure:       azurePeeringSchema(),
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(networkingAPICreateTimeout),
			Delete: schema.DefaultTimeout(networkingAPIDeleteTimeout),
		},
	}
}

func awsPeeringSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramAccount: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringMatch(regexp.MustCompile("^\\d{12}$"), "value must match pattern ^\\d{12}$"),
					Description:  "The AWS account ID associated with the VPC you are peering with Confluent Cloud network.",
				},
				paramVpc: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringMatch(regexp.MustCompile("^vpc-"), "AWS VPC ID must start with 'vpc-'."),
					Description:  "The VPC ID you are peering with Confluent Cloud network.",
				},
				paramRoutes: {
					Type:        schema.TypeList,
					Elem:        &schema.Schema{Type: schema.TypeString},
					Required:    true,
					ForceNew:    true,
					MinItems:    1,
					Description: "The [CIDR blocks](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) of the VPC you are peering with Confluent Cloud network. This is used by Confluent Cloud network to route traffic back to your network. The CIDR block must be a private range and cannot overlap with the Confluent Cloud CIDR block.",
				},
				paramCustomerRegion: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The region of the VPC you are peering with Confluent Cloud network.",
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPeeringCloudVariants,
	}
}

func gcpPeeringSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramProject: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The Google Cloud project ID associated with the VPC that you are peering with Confluent Cloud network.",
				},
				paramVpcNetwork: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The name of the VPC that you are peering with Confluent Cloud network.",
				},
				paramImportCustomRoutes: {
					Type:        schema.TypeBool,
					Optional:    true,
					ForceNew:    true,
					Default:     false,
					Description: "Enable customer route import. For more information, see [Importing custom routes](https://cloud.google.com/vpc/docs/vpc-peering#importing-exporting-routes).",
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPeeringCloudVariants,
	}
}

func azurePeeringSchema() *schema.Schema {
	return &schema.Schema{
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				paramTenant: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The Azure Tenant ID in which your Azure Subscription exists. Represents an organization in Azure Active Directory. You can find your Azure Tenant ID in the Azure Portal under [Azure Active Directory](https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Overview). Must be a valid **32 character UUID string**.",
				},
				paramVnet: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The resource ID of the VNet that you are peering with Confluent Cloud. You can find the name of your Azure VNet in the [Azure Portal on the Overview tab of your Azure Virtual Network](https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Network%2FvirtualNetworks).",
				},
				paramCustomerRegion: {
					Type:         schema.TypeString,
					Required:     true,
					ForceNew:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The region of the VNet you are peering with Confluent Cloud network.",
				},
			},
		},
		Optional:     true,
		ForceNew:     true,
		MinItems:     1,
		MaxItems:     1,
		ExactlyOneOf: acceptedPeeringCloudVariants,
	}
}

func peeringCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*Client)
	spec := networkingv1.NewNetworkingV1PeeringSpec()

	// Set regular attributes
	environmentRef := networkingv1.NewObjectReferenceWithDefaults()
	environmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	spec.SetEnvironment(*environmentRef)
	networkRef := networkingv1.NewObjectReferenceWithDefaults()
	networkRef.SetId(extractStringValueFromBlock(d, paramNetwork, paramId))
	spec.SetNetwork(*networkRef)
	if _, ok := d.GetOk(paramDisplayName); ok {
		spec.SetDisplayName(d.Get(paramDisplayName).(string))
	}
	// Detect which cloud variant is specified
	_, isAwsPeering := d.GetOk(paramAws)
	_, isGcpPeering := d.GetOk(paramGcp)
	_, isAzurePeering := d.GetOk(paramAzure)

	var cloudIdentifier string

	switch {
	case isAwsPeering:
		account := extractStringValueFromBlock(d, paramAws, paramAccount)
		vpc := extractStringValueFromBlock(d, paramAws, paramVpc)
		routes := convertToStringSlice(d.Get(fmt.Sprintf("%s.0.%s", paramAws, paramRoutes)).([]interface{}))
		customerRegion := extractStringValueFromBlock(d, paramAws, paramCustomerRegion)
		cloudIdentifier = account
		cloudOneOf := networkingv1.NetworkingV1AwsPeeringAsNetworkingV1PeeringSpecCloudOneOf(networkingv1.NewNetworkingV1AwsPeering(kindAwsPeering, account, vpc, routes, customerRegion))
		spec.SetCloud(cloudOneOf)
	case isGcpPeering:
		project := extractStringValueFromBlock(d, paramGcp, paramProject)
		vpcNetwork := extractStringValueFromBlock(d, paramGcp, paramVpcNetwork)
		cloudIdentifier = project
		cloudGcpPeering := networkingv1.NewNetworkingV1GcpPeering(kindGcpPeering, project, vpcNetwork)
		cloudGcpPeering.SetImportCustomRoutes(d.Get(fmt.Sprintf("%s.0.%s", paramGcp, paramImportCustomRoutes)).(bool))
		cloudOneOf := networkingv1.NetworkingV1GcpPeeringAsNetworkingV1PeeringSpecCloudOneOf(cloudGcpPeering)
		spec.SetCloud(cloudOneOf)
	case isAzurePeering:
		tenant := extractStringValueFromBlock(d, paramAzure, paramTenant)
		vnet := extractStringValueFromBlock(d, paramAzure, paramVnet)
		customerRegion := extractStringValueFromBlock(d, paramAzure, paramCustomerRegion)
		cloudIdentifier = tenant
		cloudOneOf := networkingv1.NetworkingV1AzurePeeringAsNetworkingV1PeeringSpecCloudOneOf(networkingv1.NewNetworkingV1AzurePeering(kindAzurePeering, tenant, vnet, customerRegion))
		spec.SetCloud(cloudOneOf)
	default:
		return diag.Errorf("error creating peering: expected one of %s, %s, %s params", paramAws, paramGcp, paramAzure)
	}

	createPeeringRequest := &networkingv1.NetworkingV1Peering{Spec: spec}

	createPeeringRequestJson, err := json.Marshal(createPeeringRequest)
	if err != nil {
		return diag.Errorf("error creating peering: error marshaling %#v to json: %s", createPeeringRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Creating new peering: %s", createPeeringRequestJson))

	createdPeering, resp, err := executePeeringCreate(ctx, c, *createPeeringRequest)
	if err != nil {
		return diag.Errorf("error creating peering %q: %s", cloudIdentifier, createDescriptiveError(err, resp))
	}
	d.SetId(createdPeering.GetId())

	// Wait for async provisioning to complete
	createEnvironmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	if err := waitForPeeringToProvision(c.networkingV1ApiContext(ctx), c, createEnvironmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for peering %q to provision: %s", d.Id(), createDescriptiveError(err))
	}

	createdPeeringJson, err := json.Marshal(createdPeering)
	if err != nil {
		return diag.Errorf("error creating peering %q: error marshaling %#v to json: %s", d.Id(), createdPeering, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished creating peering %q: %s", d.Id(), createdPeeringJson), map[string]interface{}{peeringLoggingKey: d.Id()})

	return peeringRead(ctx, d, meta)
}

func peeringRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Reading peering %q", d.Id()), map[string]interface{}{peeringLoggingKey: d.Id()})
	if _, err := readPeeringAndSetAttributes(ctx, d, meta); err != nil {
		return diag.FromErr(fmt.Errorf("error reading peering %q: %s", d.Id(), createDescriptiveError(err)))
	}
	return nil
}

func peeringUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	if d.HasChangesExcept(paramDisplayName) {
		return diag.Errorf("error updating peering %q: only %q can be updated", d.Id(), paramDisplayName)
	}

	updatePeeringRequest := networkingv1.NewNetworkingV1PeeringUpdate()
	specUpdate := networkingv1.NewNetworkingV1PeeringSpecUpdate()
	if d.HasChange(paramDisplayName) {
		specUpdate.SetDisplayName(d.Get(paramDisplayName).(string))
	}

	// Environment is required in the update request body for resource identification
	updateEnvironmentRef := networkingv1.NewObjectReferenceWithDefaults()
	updateEnvironmentRef.SetId(extractStringValueFromBlock(d, paramEnvironment, paramId))
	specUpdate.SetEnvironment(*updateEnvironmentRef)

	updatePeeringRequest.SetSpec(*specUpdate)

	updatePeeringRequestJson, err := json.Marshal(updatePeeringRequest)
	if err != nil {
		return diag.Errorf("error updating peering %q: error marshaling %#v to json: %s", d.Id(), updatePeeringRequest, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Updating peering %q: %s", d.Id(), updatePeeringRequestJson), map[string]interface{}{peeringLoggingKey: d.Id()})

	c := meta.(*Client)
	updatedPeering, resp, err := c.networkingV1Client.PeeringsNetworkingV1Api.UpdateNetworkingV1Peering(c.networkingV1ApiContext(ctx), d.Id()).NetworkingV1PeeringUpdate(*updatePeeringRequest).Execute()
	if err != nil {
		return diag.Errorf("error updating peering %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	updatedPeeringJson, err := json.Marshal(updatedPeering)
	if err != nil {
		return diag.Errorf("error updating peering %q: error marshaling %#v to json: %s", d.Id(), updatedPeering, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished updating peering %q: %s", d.Id(), updatedPeeringJson), map[string]interface{}{peeringLoggingKey: d.Id()})

	return peeringRead(ctx, d, meta)
}

func peeringDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Deleting peering %q", d.Id()), map[string]interface{}{peeringLoggingKey: d.Id()})

	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)

	req := c.networkingV1Client.PeeringsNetworkingV1Api.DeleteNetworkingV1Peering(c.networkingV1ApiContext(ctx), d.Id()).Environment(environmentId)
	resp, err := req.Execute()
	if err != nil {
		return diag.Errorf("error deleting peering %q: %s", d.Id(), createDescriptiveError(err, resp))
	}

	// Wait for async deletion to complete
	if err := waitForPeeringToBeDeleted(c.networkingV1ApiContext(ctx), c, environmentId, d.Id()); err != nil {
		return diag.Errorf("error waiting for peering %q to be deleted: %s", d.Id(), createDescriptiveError(err))
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished deleting peering %q", d.Id()), map[string]interface{}{peeringLoggingKey: d.Id()})

	return nil
}

func executePeeringCreate(ctx context.Context, c *Client, peering networkingv1.NetworkingV1Peering) (networkingv1.NetworkingV1Peering, *http.Response, error) {
	req := c.networkingV1Client.PeeringsNetworkingV1Api.CreateNetworkingV1Peering(c.networkingV1ApiContext(ctx)).NetworkingV1Peering(peering)
	return req.Execute()
}
func executePeeringRead(ctx context.Context, c *Client, environmentId string, id string) (networkingv1.NetworkingV1Peering, *http.Response, error) {
	req := c.networkingV1Client.PeeringsNetworkingV1Api.GetNetworkingV1Peering(c.networkingV1ApiContext(ctx), id).Environment(environmentId)
	return req.Execute()
}

func readPeeringAndSetAttributes(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	c := meta.(*Client)
	environmentId := extractStringValueFromBlock(d, paramEnvironment, paramId)
	peering, resp, err := executePeeringRead(ctx, c, environmentId, d.Id())
	if err != nil {
		// Classify before describing: on a 403 isNonKafkaRestApiResourceNotFound reads resp.Body to
		// tell an invalid API key from a real not-found, and createDescriptiveError drains it.
		isResourceNotFound := isNonKafkaRestApiResourceNotFound(resp)
		// One call only: createDescriptiveError drains resp.Body, so a second call loses it.
		readErr := createDescriptiveError(err, resp)
		tflog.Warn(ctx, fmt.Sprintf("Error reading peering %q: %s", d.Id(), readErr), map[string]interface{}{peeringLoggingKey: d.Id()})
		if isResourceNotFound && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("Removing peering %q in TF state because peering could not be found on the server", d.Id()), map[string]interface{}{peeringLoggingKey: d.Id()})
			d.SetId("")
			return nil, nil
		}
		return nil, fmt.Errorf("error reading peering %q: %s", d.Id(), readErr)
	}

	peeringJson, err := json.Marshal(peering)
	if err != nil {
		return nil, fmt.Errorf("error reading peering %q: error marshaling %#v to json: %s", peering.GetId(), peering, createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Fetched peering %q: %s", d.Id(), peeringJson), map[string]interface{}{peeringLoggingKey: d.Id()})

	if _, err := setPeeringAttributes(d, peering); err != nil {
		// No resp: a d.Set failure is not an API error, and resp.Body is already consumed.
		return nil, fmt.Errorf("error setting peering attributes %q: %s", d.Id(), createDescriptiveError(err))
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished reading peering %q", d.Id()), map[string]interface{}{peeringLoggingKey: d.Id()})

	return []*schema.ResourceData{d}, nil
}

func setPeeringAttributes(d *schema.ResourceData, peering networkingv1.NetworkingV1Peering) (*schema.ResourceData, error) {
	spec := peering.GetSpec()
	if err := d.Set(paramDisplayName, spec.GetDisplayName()); err != nil {
		return nil, createDescriptiveError(err)
	}
	environmentRef := spec.GetEnvironment()
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	networkRef := spec.GetNetwork()
	if err := d.Set(paramNetwork, []interface{}{map[string]interface{}{
		paramId: networkRef.GetId(),
	}}); err != nil {
		return nil, createDescriptiveError(err)
	}
	oneOfCloud := spec.GetCloud()

	switch {
	case oneOfCloud.NetworkingV1AwsPeering != nil:
		if err := d.Set(paramAws, []interface{}{map[string]interface{}{
			paramAccount:        oneOfCloud.NetworkingV1AwsPeering.GetAccount(),
			paramVpc:            oneOfCloud.NetworkingV1AwsPeering.GetVpc(),
			paramRoutes:         oneOfCloud.NetworkingV1AwsPeering.GetRoutes(),
			paramCustomerRegion: oneOfCloud.NetworkingV1AwsPeering.GetCustomerRegion(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1GcpPeering != nil:
		if err := d.Set(paramGcp, []interface{}{map[string]interface{}{
			paramProject:            oneOfCloud.NetworkingV1GcpPeering.GetProject(),
			paramVpcNetwork:         oneOfCloud.NetworkingV1GcpPeering.GetVpcNetwork(),
			paramImportCustomRoutes: oneOfCloud.NetworkingV1GcpPeering.GetImportCustomRoutes(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	case oneOfCloud.NetworkingV1AzurePeering != nil:
		if err := d.Set(paramAzure, []interface{}{map[string]interface{}{
			paramTenant:         oneOfCloud.NetworkingV1AzurePeering.GetTenant(),
			paramVnet:           oneOfCloud.NetworkingV1AzurePeering.GetVnet(),
			paramCustomerRegion: oneOfCloud.NetworkingV1AzurePeering.GetCustomerRegion(),
		}}); err != nil {
			return nil, createDescriptiveError(err)
		}
	}

	d.SetId(peering.GetId())
	return d, nil
}

func peeringImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	tflog.Debug(ctx, fmt.Sprintf("Importing peering %q", d.Id()), map[string]interface{}{peeringLoggingKey: d.Id()})

	envIDAndResourceId := d.Id()
	parts := strings.Split(envIDAndResourceId, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("error importing peering: invalid format: expected '<environment ID>/<peering ID>'")
	}
	environmentId := parts[0]
	resourceId := parts[1]
	d.SetId(resourceId)
	if err := d.Set(paramEnvironment, []interface{}{map[string]interface{}{
		paramId: environmentId,
	}}); err != nil {
		return nil, err
	}

	// Mark resource as new to avoid d.Set("") when getting 404
	d.MarkNewResource()
	if _, err := readPeeringAndSetAttributes(ctx, d, meta); err != nil {
		return nil, fmt.Errorf("error importing peering %q: %s", d.Id(), err)
	}
	tflog.Debug(ctx, fmt.Sprintf("Finished importing peering %q", d.Id()), map[string]interface{}{peeringLoggingKey: d.Id()})
	return []*schema.ResourceData{d}, nil
}
